### ISSUE TITLE
C++17 migration TODO list

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1022]
We'll migrate to C++17 soon. Let's collate here the various bits and pieces that we will update accordingly. They can be spun off into individual issues as required.

* <s>Replace `util::optional` with `std::optional` — usages of `util::optional<T&>` will need to be replaced with `std::optional<std::reference_wrapper<T>>` and/or the corresponding interfaces changed.></s> [fixed in #1158]
* <s>Replace `util::variant` with `std::variant`</s> [fixed in #1152] <s>and implement `util::either` over `std::variant`.</s> [fixed in #1142]
* Replace `make_foo` helper usage with simple constructors, adding deduction guides as appropriate.
* Remove class constructors that are present only to allow default member values — these will be able to use brace initialization.
* <s>Attend to anything with a `TODO: C++17` comment.</s> [fixed in #1159 (pending review)]
* <s>Use `std::in_place_t` where appropriate in our utility class interfaces.</s> [fixed in #1142]
* <s>Replace `util::size` with `std::size`.</s> [fixed in #1140]
* Replace `std::is_blah<X>::value` predicates with `std::is_blah_v<X>`.
* <s>Replace `util::any` with `std::any`.</s> [fixed in #1152]
* Replace `util::unique_in_place` with `std::unique` or a wrapper around `std::unique`.

**Comment by thorstenhater** [comment]
Also, investigate `std::pmr::` for allocator-aware containers.

**Comment by thorstenhater** [comment]
Hey,

most of this has been done by linting the codebase and will continue to improve, so I am closing this.
