### ISSUE TITLE
Deprecate CUDA 9

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#1035]
Move the minimum supported version of CUDA from 9.2 to 10.0.

This would simplify the project by removing the dependency on NVML, which is required before CUDA 10 to determine GPU uuids used in arborenv.

**Comment by bcumming** [comment]
Is CUDA 10 universally supported on all NVIDIA GPU systems? It is to the best of my knowledge.

**Comment by brenthuisman** [comment]
The difference in hardware support between 9 and 10 is minimal: https://en.wikipedia.org/wiki/CUDA#GPUs_supported

**Comment by bcumming** [comment]
The main benefits of increasing the minimul version of CUDA are:
1. you can use more recent versions of gcc, and hence, by extension, of the C++ standard.
2. access to CUDA features (like no longer needing nvml)
