### ISSUE TITLE
Port Allen institute single cell models

### ISSUE THREAD

**Issue by thorstenhater** [arbor-sim/arbor#1049]
- make a catalogue of the mechanisms commonly used in the Allen Institute's models
- port some of the Allen SDK single-cell models to arbor
- come up with a (semi-)automatic way to ingest these models

**Comment by noraabiakar** [comment]
Partially addressed in #1071 and #1074

**Comment by thorstenhater** [comment]
Done, presented at Bernstein online 2020. Further enhancements in terms of a more portable cell description ongoing.
