### ISSUE TITLE
Remove pas mechanism: gl and el become properties of cable

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#1051]
This has been raised before, but I couldn't find it in a ticket.

Currently we have a `pas` mechanism that mimics NEURONs mechanism for leaky currents. The idea is that we could remove the `pas` mechanism, and make it an intrinsic part of the cable. This would reduce the number of kernel calls, however it would increase the amount of built in state maintained by cells.

In the Allen models, the leaky reversal, `el`, is a "passive" property, like `cm` and `ra`, and `gl` is part of the "genome", so it is not exactly clear how the want to classify these properties.

This would require touch quite a few parts of the code/docs/examples, however none of the changes are complex (good task for a new developer?)

1. remove `pas` mechanism
2. add `gl` and `el` as cable properties
3. add vectors for gl and el to state, similar to those for voltage, current, weights, etc.
4. add calculation of passive current (calculate in the same method/kernel that zeros the current vector before each time step?)
5. remove leaky current contribution (`el` and `gl`) from the `hh` mechanism
6. fix all of the unit tests, examples and nsuite benchmarks
7. update docs.

I am for the change. Opinions?

**Comment by halfflat** [comment]
Just to summarize my comments on the slack channel:

I'm broadly against it, unless the performance advantages are substantial:
* It is privileging a particular sort of membrane current dynamics.
* From a modelling point of view, leak currents aren't _really_ passive: they are not an electrical property per se, but an approximation to bulk ion channel behaviour.
* Pulling it down into the guts of the cell complicates an already rather complicated bit of the code (the fvm cell discretization), as well of course as the current calculation at matrix build time.

I would prefer to obtain the performance benefits through the bundling of mechanisms when we get runtime code generation into Arbor, while acknowledging that's going to be some time off into the future.

Could we estimate the performance benefits by comparing e.g. cells with hh dynamics vs cells with hh-without-leak-current + separate pas?

**Comment by thorstenhater** [comment]
I am closing this based on 
- increased complexity.
- not zero overhead (if you do not need `pas` you still pay for it).
- priviledging a kitchen sink approximation.

The performance benefits are there, but considering models like those
in the BBP or Allen databases which use ~20 mechanisms, the relative
improvements are low. 

@bcumming @halfflat  Feel free to re-open if this is still an issue.
