### ISSUE TITLE
Expunge spherical somata from morphology.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1060]
What does NEURON do, when given a spherical soma and apical and basal dendrites from an SWC file. Where does it attach what, when it discretizes?

The spherical root special case in the Arbor morphology code complicates a bunch of things, and still leaves various cases open. Should apical dendrites be attached to 'the other end' of the root (soma) branch? How much special casing would we need when reading SWC files?

Spherical roots, when discretized, are treated as squat cylinders in the current Arbor implementation, and that's unlikely to change. So let's simplify things:

1. Morphologies are described by cable segments only, which are in turn defined unambiguously by pairs of parent-adjacent samples. Anything to do with spherical roots is expunged.
2. Sample trees with a single sample are ill-defined.
3. Conversion from a spherical soma to a squat cylinder cable is done in SWC parsing, if required.
4. If we want to support SWC directly in the C++ library, we can interpret it effectively as we currently do: anything attached to a spherical root is attached at the same point.
5. More elaborate interpretations or outright manglings of SWC data are relegated to client-side; whatever NEURON does, if it's not trivial, can go in the Python library.

**Comment by halfflat** [comment]
So, what to do about branches that don't directly attach to a spherical soma?

This is a useful thing, but was already special cased for somata. A possible fix:
* In the sample tree, adding a point to a parent starts a new branch if the parent point already has a child.
* The first point of a new branch, geometrically, is the first point that creates a branch when added to the tree (i.e. _not_ the parent point).
* When translating SWC, extra points are added when new branches are made to preserve the current semantics.

**Comment by bcumming** [comment]
It would be a pretty big change, however it removes a lot of ambiguity, is ultimately more flexible.

And by golly, it would reduce so much complexity and so many corner cases.

There would be a lot of refactoring in the unit tests, leading to a reduction in tests and lines of code!

**Comment by bcumming** [comment]
I have split the detached branch feature raised by @halfflat in a comment to a new ticket #1061.
