### ISSUE TITLE
Handle branches detached branch geometry

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#1061]
We support branches attached to spherical somas that do not start at the edge of the sphere, which is reasonable because it allows us to accurately model the location where a branch attached to a non-spherical soma that is being approximated with a sphere.

However, we do not support such detached branch starts for cable-cable fork points, where it may be useful. For example, consider a model with small spurs rendered explicitly, which create very odd artifacts with our current approach if they were "correctly" located in space.

We will lose this feature at the some when we remove spherical root segments (#1060). We should take the opportunity to add first-class support, instead of the current ad-hoc implicit support that we will be losing.

@halfflat and I think that the best approach would be to start a branch at the location of the *first sample after the fork" from which it branches. A collocated sample could be used to indicate an attached cable.

**Comment by bcumming** [comment]
On reflection, the approach of only permitting "detachment" after a fork point is not general, and does not permit detached dendrites/axons at the soma under certain conditions.

By starting branches at the first sample point after the fork, detachments can only be created directly after fork points. This won't allow a dendrite to be detached from the soma for a simple ball and stick model, which is treated as a single cable. More generally, we won't be able to have detached cables at the distal end of a soma with only one cable attached.

One could insert artificial zero-length branches at such locations, however that is an ugly hack.

I think I have a generic solution: if a sample is collocated with its parent, and has the same radius, then it indicates a jump. This approach will allow for detachments at arbitrary locations (which might arise between two cable segments that approximate more complex underlying geometry.

It also does not affect using collocation to indicate a change in radius.

Finally, it allows one child branch of a fork to be detached, while the other is attached (e.g. very useful for dendritic spurs).

**Comment by halfflat** [comment]
I feel this too is a bit of a hacky approach, to be honest. Why not change the sample tree API, now that it is not tied directly to SWC conventions?

For arbitrary disconnections at fork points, we could allow branches to have one distinct child branch, and have the sample tree API allow one to say explicitly when one is creating a new branch. Implicit branching is still possible (when one adds a branch to the middle of an existing branch), or branches could be made strictly explicit, where samples would only be allowed to be attached to branch final points.

For arbitrary disconnections anywhere, the sample tree API could take segments, i.e. pairs of sample points; a convenience method could just continue from the parent. In fact, we could do both this _and_ explicit branches, and I think that would give us the most flexibility.

Would anything actually break if a branch can have just one child branch? Everything coped with soma ball-and-stick models, so I suspect not.

**Comment by bcumming** [comment]
I suspect that there would be breakages. The old ball and stick code was held together with a lot of if-else sticky tape that has been removed in #1060.

Using branches to indicate "gaps" in the tree also feels hacky to me. At the moment branches are sequences of samples that must have either root, terminal or fork points at their ends, and can contain none of those in between, which is a nice concrete definition in my mind.

I would prefer an approach of having branches being sequences of segments instead of sequences of samples. One can create segments implicitly, by appending a single sample, or explicitly by passing a pair of samples that define the new segments.

Keeping the interface for the sample_tree so that it works only with segments/samples and does not explicitly work with branches is by far my preference.

Maybe it has to become a `segment_tree`?

**Comment by halfflat** [comment]
Discretization won't care about single branch children, as far as I am aware; I'm mostly concerned about the GPU tree solver.

The motivation for explicit branching was to cover the case where people expect the soma and a dendrite to be different branches, and if we allow that there, then maybe we should allow that at any point.

But leaving out that case and just allowing arbitrary disconnected segments covers everything else.

**Comment by bcumming** [comment]
The GPU tree solver might need some small fixes, however it can already handle branches with one parent internally, because they occur when it performs rebalance-and-split of trees.

With a 'regional' method for prescribing discretisation strategies, there is no motivation for having soma and all attached dendrites/axons as separate branches. Model descriptions that do not depend on what Arbor's back end calls a branch are our aim, and allowing users to start creating branches on top of segments and samples muddies the waters IMO.

**Comment by bcumming** [comment]
After starting work on the `segment_tree`, I have realised that we no longer need the `segment_tree` at all.

The `morphology` derived from a `sample_tree` was a combination of `sample_tree` and the interpretation of the root sample as a sphere, which was the main motivation behind separating the two.

However, a `segment_tree` unambiguously generates the same `morphology`, so we can roll them into one data structure. It is possible to update all of the meta data about branch counts, which segments are assigned to which branch, etc, in constant time after every `append` operation.

This simplifies the code, and the workflow significantly.
