### ISSUE TITLE
Extend morphology placement interface to query whole geometry.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1068]
For the use case of plotting the whole of a morphology, we should be able to query `place_pwlin` for the full piecewise-linear description of the geometry.

With segments replacing samples as the underlying representation, this can be achieved by running over all segments in a morphology and calling `place_pwlin::at` on the ends, or by having `place_pwlin` provide an interface for this directly.

This would be useful in a more faithful translation of the simple NERON LFP demo (which plots a schematic of the morphology).

**Comment by noraabiakar** [comment]
Closed in #1124
