### ISSUE TITLE
Warning: uninitialized variables 

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#1076]
Compiling the generated vectorized c++ code of mechanisms can generate warnings of variables being used undefined. 
This is common when initializing a variable depends on a condition, for example:
```
if (a < 0) {
   b = 1
} else {
   b = 2
}
```
This gets translated into the following vectorized code (simplified):
```
{
    auto mask_vec = vec_a < 0;
    where(mask_vec, vec_b) = 1;
    where(mask_vec, !vec_b) = 2;
}
```
`vec_b` is originally not initialized before being used as an argument to the `where` function call, and the compiler generates a warning. The use of an uninitialized variable is not incorrect in this case, but the warning can be eliminated by initializing temporary variables to zero before their first use.

**Comment by halfflat** [comment]
Unfortunately we don't have a handy attribute for this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55288
