### ISSUE TITLE
Fix recipe docs for probes

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1080]
As per the title, the C++ API documentation for recipe is out of date. So we should update it.

**Comment by halfflat** [comment]
Documentation structure is currently in flux; we will return to this after reorg.

**Comment by brenthuisman** [comment]
`doc/cpp/probe_sample.rst` exists and seems quite complete. I even see some definitions that didn't get a `glossary` directive, so were not seen in the recent update.

Let's close.
