### ISSUE TITLE
Tidy SWC, morphology generation helpers.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1085]
As a result of the recent morphology revamp, we've got some overlapping code and vestigial code when it comes to morphology generation from SWC or for test cases.
* `swc_record` has the `coord()` member that returns a value of type `arb::point<arb::swc_record::coord_type>`. Nothing else uses `arb::point`; we have `arb::mpoint` for morphology points in other contexts.
* `segments_from_points` in `test/common_cells.hpp` is almost exactly the same code as `swc_as_segment_tree`; building up a segment tree (or morphology) from a bunch of points is useful, so a common functionality should be present in the library.
* `soma_cell_builder` used in the test code is there to ease the transition from the tests that were based on cell models with spherical somata. It has some weirdnesses, such as a `location` method that tracks whether or not one is looking for a location on a soma that's a subpart of a larger branch, and scales accordingly. We could simplify things by modifying the tests to remove this special dependence on somata, or go the other direction and provide a richer interface that would be sufficient to provide the functionality required to parse and represent NeuroML morphologies.

Proposed plan:
1. Nuke `arb::point`, make a library version of `segments_from_points`, implement SWC reader and types in terms of `mpoint` and the library `segments_from_points`-like function.
2. Replace test cells that use `soma_cell_builder` with cells without an explicit soma, and/or use `segments_from_points`, or draw from a small list of well-defined cell morphologies.
3. Replace `common_morphologies` test cells with a more useful list that captures some of the cases in (2) above.

In another tranche of work, make a NeuroML morphology reader that has an independently useful back-end that we can deploy in unit tests and C++ examples independently of NeuroML (or other XML guff).

**Comment by halfflat** [comment]
Is the remaining work covered by #1102? Check, and if so, we can close this.

**Comment by akuesters** [comment]
[NA] #1085 is partially covering #1102 but not completely; can probably be tackled at same time

**Comment by thorstenhater** [comment]
This seems done, there are no references to `arb::point` anywhere` and the dependencies are closed by now.
