### ISSUE TITLE
"spherical soma" support in swc files

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#1089]
An swc file is a list of samples with tag meta-data and a parent-child ordering.
The only consistent interpretation is to treat the samples as the end points
of segments, for a fully connected segment tree with no detached segments,
with each segment's tag inherited from its distal sample.

To generate a segment tree that models a spherical soma centered around the 
first sample, where that sample is the only sample with swc-record (tag) 1,
there has to be some "interpretation" of the samples.

Here is a proposal for one such interpreter:

* Construct a cylinder with `length=2*radius` centered on the root sample,
  with tag 1.
* Start dendrites, axons and apical dendrites at the first sample
  that has the root as its parent.
* The axons and apical dendrites would be attached to the proximal end of the soma
  with a gap connection.
* The dendrites would be attached to the distal end of the soma with a gap connection.
* Throw an error if tag other than 1, 2, 3, 4 is encountered.
* Throw an error if the root sample does not have tag=1
* Throw an error if a non-root sample has tag 1

**Comment by halfflat** [comment]
I don't think that apical/basal dendrites should be treated differently: it'll be surprising to people coming from other software that consumes these sorts of SWC.

What NEURON does is very weird, but if we're going to support 1-point somata SWC files, we should probably aim to mimic it. Otherwise we're just adding to the problem.

**Comment by bcumming** [comment]
This would be in the form of a special function:
```
auto tree = sample_tree_from_swc_spherical_soma(fname);
```

**Comment by halfflat** [comment]
Can this be relegated to the python layer?

**Comment by halfflat** [comment]
Another option is to mutate the SWC into something that is sane. (As discussed elsewhere) this would require translating branches in space.

**Comment by halfflat** [comment]
My main motivation for keeping this out of the library, is that it forces users to be unambiguous in their intent. It also saves us from having to support an interface with a lot of baked-in magic.

**Comment by bcumming** [comment]
But what does NEURON do? Which end does it attach to? There is no documentation, the answers on the forum are vague, and I can't understand the hoc code that performs the interpretation. It is pretty clear that most users don't understand what it is doing.

I think that we are better of coming up with a sane interpretation, and documenting it clearly.

Sure, I am happy to put this in the Python layer!

Regarding mutation: folk might be relying on the samples being in their "true" position as specified in the swc, e.g. for LFP calculations, so operations like shifting all the samples in a sub-tree so that their root aligns with an end of the soma wouldn't be expected.

**Comment by halfflat** [comment]
To mimic NEURON, we'd have to launch an investigation (seriously!).

My preferred approach: let's not accept them, but provide an alternate interface for people to describe morphologies which are disconnected in representation, such as NeuroML. One-point soma SWC is not fit for purpose.

**Comment by bcumming** [comment]
I agree that one-point SWC is a very bad choice: but it is used by AllenSDK and SONATA, so we can't just throw it out.

How about in Python land `load_swc_sonata()`, where we get to define exactly how the SWC files are going to be interpreted, and we document it properly.

**Comment by halfflat** [comment]
Okie doke! But I still think they need to be interpreted in the same way as they would in their NEURON workflows, or else we're not solving the problem at hand.
