### ISSUE TITLE
Help (Question): Chain HH cell and passive cable

### ISSUE THREAD

**Issue by subash774** [arbor-sim/arbor#1092]
Hi,
Thanks for such clean and well documented code. I am new to computational neuroscience and this librabry has helped me understand more than some of the text books. 

My aim is to create a simulation model where I chain a number of passive cables to HH cell and observe the effect on voltage output. I know arbor has recipes but what's the most efficient way of creating a HH cell and then chaining that to a passive cable model? (Using Python) Also are there quick ways to create HH cells and passive cable with leakage?

Thanks in advance! Your help would be appreciated.

**Comment by noraabiakar** [comment]
Hi and thank you!

Using the python interface, you can build a single cell model without explicitly writing a recipe.

You can start by either exporting a morphology from an swc file and building a cell from it (see: https://github.com/arbor-sim/arbor/blob/master/python/example/single_cell_swc.py) or you can build a cell directly by first creating a soma then attaching branches (cables) to it (see: https://github.com/arbor-sim/arbor/blob/master/python/example/single_cell_builder.py). I think what you're looking for is the latter example.

In both cases, you can then label regions of a morphology (such as soma and dendrites) and use these labels to `paint` on mechanisms such as `pas` or `hh` (you can find our built-in mechanisms here: https://github.com/arbor-sim/arbor/tree/master/mechanisms/default). You can also label specific locations on the morphology and use them to `place` synapses, stimuli or probes. Once your cell is ready, you can build a `single_cell_model`; attach your voltage/current probes to it; and run the model.

We are working on adding more extensive documentation that will hopefully make it easier to start working with arbor. I hope the examples I linked are clear enough for now, but if not I'm happy to answer any other questions you may have.

**Comment by subash774** [comment]
@noraabiakar That's great, thank you so much! I'll give it a go and bother you again if I have any other questions. 
Also, is there a way to modify ```hh``` parameters? I can see them defined in the mod file but is there a python interface to modify them?

Thanks again, really appreciate it.

**Comment by noraabiakar** [comment]
You can modify mechanism parameters while painting them on the cell, for example:
`cell.paint('soma', mech('hh', {"gnabar": 0.1, "gkbar":0.02}))`
Hope that helps!

**Comment by noraabiakar** [comment]
Also, we have pretty good `help` functions in the python interface, you can try doing:
```
import arbor
help(arbor.single_cell_model)
help(arbor.cable_cell)
```

**Comment by subash774** [comment]
Ahh that's great, thanks!

**Comment by subash774** [comment]
@noraabiakar Sorry to bother you again, got a couple of very stupid questions. 
- How does probe values effect the output?
- How does the locations work? My architecture looks like this: HH cell ----------- dendrite of length 1mm ------- HH cell
what is the location of dendrite?

**Comment by noraabiakar** [comment]
No problem!

> How does probe values effect the output?

`m.probe('voltage', loc(0,0.5), 10000)` : 
* 'voltage' is the probed quantity, currently we can only probe the voltage using the python interface, this will be extended to include other measured quentities.
* `loc(0,0)` is the location to measure the voltage, the `0` is the index of the cable of the cell. This is almost always the soma of the cell. The `0.5` is the position along the cable, this value has to be between [0,1]. 
For example if this is your cable:
```
 --------------------
^          ^         ^
0         0.5        1
```  
* `10000` is the sampling rate in Hz for `loc(0,0)`, so if you run the simulation for 1 second you'll get 10000 voltage measurements at `loc(0,0)`, 1 every 0.1 ms. For finer grained measurements you can increase this value (the default `dt` is 0.025ms, so going beyond 40 KHz won't help). 

> How does the locations work? My architecture looks like this: HH cell ----------- dendrite of length 1mm ------- HH cell
what is the location of dendrite?

As explained above, `arbor.location` indicates the cable id, and the position along the cable. In your example, if you construct the cell from left to right:
```
    ----|---------------|-----
id:  0          1          2
```
If you want to measure the voltage at the midpoint of the middle branch (the midpoint of the dendrite) you would measure at `location(1,0.5)`

**Comment by subash774** [comment]
That makes a lot of sense! Thank you so much. 
BTW, the example for python : https://github.com/arbor-sim/arbor/blob/master/python/example/single_cell_builder.py seems to have an error. ```add_cable``` requires a parent. I'd submit pull request but idk what the best way to do it is. I fixed mine by having a ```add_sphere``` before the cable and pointing to that for parent.

**Comment by noraabiakar** [comment]
Thanks for pointing that out! We've changed a few things recently and the examples seem to be out of date. I'll fix and update them.

**Comment by subash774** [comment]
```
x = b.add_sphere(radius=1,name="x")
# Start with a spherical soma (HH cell) with radius 7 μm,
# approximated with a cylinder of: length = diameter = 14 μm.
s  = b.add_cable(parent=x, length=14, radius=7, name="rav", ncomp=1)
```
I only added the sphere there so it'd work, is that the right way?

**Comment by noraabiakar** [comment]
So, I think you installed arbor using pip? In which case you would have version 0.3 of arbor. So we should be using the examples from https://github.com/arbor-sim/arbor/tree/v0.3 instead of master. The examples in master will not work with arbor v0.3. 

Sorry for pointing you to the wrong file earlier, this is the correct one: https://github.com/arbor-sim/arbor/blob/v0.3/python/example/single_cell_builder.py

You can then write the following directly, and start attaching cables.
```
# Start with a spherical soma (HH cell) with radius 7 μm, implemented as a sphere
s = b.add_sphere(radius=7,name="rav")
```

**Comment by subash774** [comment]
Yepp, all good now. Thanks!

**Comment by subash774** [comment]
Hi,
There seems to be no documentation on what the parameter ```ncomp``` in ```arbor.flat_cell_builder.add_cable``` is? I see that the convention seems to be that ```ncomp``` is the same as the cable length but what exactly is ```ncomp```?

**Comment by subash774** [comment]
Hi @noraabiakar, sorry to bother you again,
Just realised that I need a bit more than just a passive cable. Is there a way for me to define my own cable with more properties? I'm trying to model a myelin sheath so I need some extra params, is that possible?

**Comment by noraabiakar** [comment]
How are you planning on modeling the myelin sheath, what extra parameters/properties do you need?

**Comment by subash774** [comment]
Can I email you on your profile address?

**Comment by brenthuisman** [comment]
@subash774 This issue is stale. Please reopen if it wasn't resolved satisfactorily.
