### ISSUE TITLE
Python site-packages directory unavailable in Debian (derived) distro's

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1100]
The Cmake script wishes to install the Python package to `${ARB_PYTHON_PREFIX}/lib/python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}/site-packages`, e.g. `/usr/local/lib/python3.6/site-packages/arbor` on Ubuntu 18.04. This probably works everywhere, except Debian derived distro's, see <https://wiki.debian.org/Python#Deviations_from_upstream>.

`make install` therefore exits with an error on Ubuntu and Debian. A solution could be (and perhaps should be?) to install the package as a user package. I don't know if that conflicts with anything else, hence me bringing the issue up.

I've seen the config option to set your own ARB_PYTHON_PREFIX, but might it be nicer to set it to `python3 -m site --user-site` by default rather than `/usr/local`?

**Comment by bcumming** [comment]
Picking the correct location to install Python packages is a lose-lose game. You get it working on Debian, and it will break on OS X, and so on for ever.

When folk type `cmake; make install` the expectation is that the library won't be installed as user, which installing at `--user-site` kinda breaks. When installing packages with pip, global is the default, and user is opt in (crazy, bug that's how it is). It also requires a call out to `python` from CMake, which experience has taught me is another spot where our build scripts can and will break for somebody else.

CMake also does a pretty terrible job of finding paths, e.g. it doesn't detect that you are in a venv, and set the destination path appropriately.

With all this in mind, after much deliberation and gnashing of teeth, we decided that the best approach was to just make folk explicitly state where they want it installed. We could beef up the docs, to better explain the options available to them.

**Comment by brenthuisman** [comment]
Thanks for the thorough reply!

Do we know what sort of environments typical (new) users work in? How things were for me was that administrators generally don't install things on request, and users don't have write access outside of `~` (of course) and pip isn't necessarily available, even locally. So, you need to build anything yourself, in `~`. As such, a local install under a single switch might be helpful.

**Comment by halfflat** [comment]
One item in the aforementioned deliberations that led to the current state is that CMake has a standard way of specifying where the installation root is, i.e. `CMAKE_INSTALL_PREFIX`, and we should use these standard mechanisms to describe behaviour as much as possible. `ARB_PYTHON_PREFIX` is required for those cases where one wants or needs to install the python components in a different location.

For the user who is simply using the python interface, `pip` will do the trick with the standard command line options for a user directory install.

I'm fairly convinced that adding any additional path-related install configuration is only going to muddy the waters. The existing options, I believe, cover all the use cases.

**Comment by brenthuisman** [comment]
This may be different on the type of systems neuroscientists, I don't know. I'm putting it on my list of things to find out. During my masters and phd, configuring paths to install somewhere in `~` was one of the first (undocumented) things a student would have to discover. (pip wouldn't be available).

**Comment by halfflat** [comment]
That said, I just gave things a go, and specifying `CMAKE_INSTALL_PREFIX` _does not_ change the python install path. For me, this is surprising behaviour.

**Comment by halfflat** [comment]
Just to expand on that: with my sysadmin hat on, if I tell a package to install itself under directory DIR, with root permissions, I'd be mightily irked to find it had used those permissions to install bits of itself in other parts of the file system too. It's a bad default for `stow`-based package management, and it complicates deinstallation.

**Comment by brenthuisman** [comment]
Regarding FindPython in CMAKE: Pybind seems to be using it: https://github.com/pybind/pybind11/pull/2370, and based on the fixed issues proper support for envs/conda is also present. Worth a second look?

**Comment by brenthuisman** [comment]
Latest Setuptools release breaks pip on Debian/Ubuntu entirely: https://github.com/pypa/setuptools/issues/2350
It no longer uses Debian/Ubuntus patch distutils, resulting in pip not using the `dist-packages` dir, similar to this issue. The good news: newer versions of `pip` should be defaulting to `--user` if they find they can't write to the system package directory.

**Comment by bcumming** [comment]
After further discussion, and some digging into the innards of Python, we have arrived at the following method for finding an installation path that matches that which would be used by pip (at least if we assume pip isn't going to do something irrational like installing as `--user` if it discovers it doesn't have write permissions in the default path):
```Python
python3 -c "import sysconfig; print(sysconfig.get_path('purelib', scheme='posix_prefix'))"
```
This has been tested on different Linuxes, OS X, with/without virtual envs, using Homebrew/Spack/Conda, and returns a sane default in each case.
Further docs: https://docs.python.org/3/library/sysconfig.html#installation-paths
