### ISSUE TITLE
Replace soma_cell_builder with builder suitable for NeuroML morphology support.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1102]
As part of the implementation of NeuroML 2 morphology reading #1088 and to fix the rather ad hoc 'some cell builder' process (see #1085), it is useful to provide in the main library an alternative cell morphology construction process in terms of labelled segments, which can then be referred to later via region expressions.

The task is to implement a corresponding builder class, where the basic unit of description corresponds to a NeuroML-style segment. These objects can have children attached to points _within_ the segment, and not just the ends, and so do not correspond directly to the `msegment` already present in Arbor morphology descriptions: we'll need a new name for these, at least as far as the Arbor API is concerned.

**Comment by halfflat** [comment]
I'll finish this work when/if #1111 is merged.

**Comment by thorstenhater** [comment]
Soma builder last point of use is in tests, this can be closed until needed again.
