### ISSUE TITLE
Find locations on morphology by point query.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1108]
It can be hard to determine the concrete `mlocation` of a 3-d point on the morphology once it is constructed, without walking the segments in each branch. We should and can add a feature to `placement_pwlin` to provide this feature.

Design decisions/queries:
* Return exactly one location, unless the morphology is completely empty.
* Find closest point on the _axis_ of the branches? i.e. ignore radius? Certainly easier that way.
* Use standard Euclidean metric.

**Comment by halfflat** [comment]
Executive decision: just do linear search; when or if it's evidently too slow, implement an R-tree NN search.

**Comment by brenthuisman** [comment]
What's the specific use case?

**Comment by halfflat** [comment]
The motivation that immediately comes to mind is 'touch' based synaptic placement (candidate synapse placements arising from proximity with other neurons). But more broadly, it should cover anything that derives from the neuron in situ, as opposed to something intrinsic.

**Comment by noraabiakar** [comment]
Fixed in https://github.com/arbor-sim/arbor/pull/1751
