### ISSUE TITLE
modcc/defining a time-dependent non-specific current in NMODL

### ISSUE THREAD

**Issue by espenhgn** [arbor-sim/arbor#1109]
Hi. I'm trying to define a non-specific current in NMODL that depends on time. The following `sinsyn.mod` which creates a sinusoid transmembrane current works fine with nrnivmodl and NEURON:
```
COMMENT
Bla bla
ENDCOMMENT

NEURON {
    POINT_PROCESS SinSyn
    RANGE del, dur, pkamp, freq, phase, bias
    NONSPECIFIC_CURRENT i
}

UNITS {
    (nA) = (nanoamp)
}

PARAMETER {
    del=5     (ms)
    dur=200   (ms)
    pkamp=1   (nA)
    freq=1    (Hz)
    phase=0
    bias=0    (nA)
    PI=3.14159265358979323846
}

ASSIGNED {
    i (nA)
}

BREAKPOINT {
    if (t < del) {
        i=0
    }else{
        if (t < del+dur) {
            i = -pkamp*sin(2*PI*freq*(t-del)*(0.001)+phase)-bias
        }else{
            i = 0
        }
    }
}

NET_RECEIVE(weight (nA)) {
}
```
`modcc` however doesn't like `i (nA)` in the ASSIGNED block:
```
$ modcc -o . -t cpu sinsyn.mod 
internal compiler error: the symbol i already exists @ (line 6,col 25)
```
Removing that results in multiple `the variable 't' is undefined` errors as I presume `t` is not globally defined in arbor as it is in NEURON. `nrnivmodl` will no longer compile the file at this point. 
The error with `modcc` can be silenced by adding `t` to RANGE and PARAMETER but `modcc` ultimately gives a warning with ` there is no SOLVE statement, required to update the state variables, in the BREAKPOINT block`. 
In this case a solve statement `SOLVE states METHOD cnexp` and `DERIVATIVE states {...}`  shouldn't be required, so surely there must be a better way to define this. Any suggestions?

**Comment by bcumming** [comment]
Hello @espenhgn.

Arbor does use a slightly different dialect of NMODL, as you have discovered.

* it doesn't make sense for currents to be `ASSIGNED`, so it is disallowed.
* we don't expose `t` as a magic variable, like `v` or `celcius`, however we can expose it easily enough.
* The `there is no SOLVE statement...` statement should just be a warning, not an error. We have other mechanisms that don't have `SOLVE` statements, which just give this warning (that we should really disable).

https://github.com/arbor-sim/arbor/blob/master/mechanisms/default/pas.mod

@noraabiakar will implement the `t` variable, and work with you on getting your mechanism working.

**Comment by espenhgn** [comment]
@bcumming , thanks for the prompt response. I indeed got a warning and not an error with the missing SOLVE statement. I corrected my above explanation.

**Comment by espenhgn** [comment]
to add: exposing the time variable sounds like a good idea (even if my particular use case lacks any sort of biological plausibility).

**Comment by bcumming** [comment]
Looking at it, I wonder if we should add support for stimuli with custom time-varying currents. At the moment we support only square wave currents in our current clamp.

**Comment by espenhgn** [comment]
> Looking at it, I wonder if we should add support for stimuli with custom time-varying currents. At the moment we support only square wave currents in our current clamp.

Having support for arbitrary variable input currents (and voltage clamps for that matter) would indeed be very welcome, for instance to replicate experimental protocols for cell stimuli. The Allen Institute uses different noise stimuli for instance: http://celltypes.brain-map.org/experiment/electrophysiology/628700262

**Comment by noraabiakar** [comment]
Hello, 
The PR for exposing the current time of the simulation in the NMODL variable `t` has been merged. The mechanism can now be compiled. However, I had to make a couple of changes: in addition to removing `i` from the `ASSIGNED` block, we need to add `t` in the `PARAMETER` block.
```
COMMENT
Bla bla
ENDCOMMENT

NEURON {
    POINT_PROCESS SinSyn
    RANGE del, dur, pkamp, freq, phase, bias
    NONSPECIFIC_CURRENT i
}

UNITS {
    (nA) = (nanoamp)
}

PARAMETER {
    del=5     (ms)
    dur=200   (ms)
    pkamp=1   (nA)
    freq=1    (Hz)
    phase=0
    bias=0    (nA)
    PI=3.14159265358979323846
    t
}

ASSIGNED {}

BREAKPOINT {
    if (t < del) {
        i=0
    }else{
        if (t < del+dur) {
            i = -pkamp*sin(2*PI*freq*(t-del)*(0.001)+phase)-bias
        }else{
            i = 0
        }
    }
}

NET_RECEIVE(weight (nA)) {
}

```

**Comment by espenhgn** [comment]
Thanks @noraabiakar . I'll try it out!

**Comment by bcumming** [comment]
Hey @espenhgn, were you able to use the new feature?

**Comment by espenhgn** [comment]
Hi @bcumming; Sorry, I didn't get around to it yet due to some other obligations. I'll look into it, but I think we can close this issue for now and rather reopen it if I still have problems. 

Thanks a lot!
