### ISSUE TITLE
Unify printing, tracing, logging utilities: part III. [2]

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#111]
Point estimate: 2
Feature: #65

Make a common set of pretty-printing routines that:
* provides at least one adaptor for printing container contents;
* presents a common mechanisms for colour or highlighting output;
* makes colour/highlighting sequences terminal aware (i.e. by default don't use colour output when not printing to a tty or to a terminal that does not support colour.)

**Comment by halfflat** [comment]
There has been some work done on this:
* `arbor/io/sepval.hpp` provides the container adaptor,
* pretty printing for SIMD values is provided by `arbor/io/serialize_hex.hpp`.

A ticket #514 has been made just for pretty printer consolidation.

**Comment by thorstenhater** [comment]
Hey, this is a smaller package of #1451. I'll close this to avoid duplication.
