### ISSUE TITLE
Documentation won't build without an extra python module

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1128]
After checking out master, updating submodules etc. and configuring, building the documentation with
```
make html
```
gives the error:
```
Scanning dependencies of target check-sphinx
Scanning dependencies of target check-sphinx_rtd_theme
Finding Sphinx
Checking for Read the Docs Sphinx theme
Built target check-sphinx
Built target check-sphinx_rtd_theme
Scanning dependencies of target html
Generating Sphinx documentation
--- generating images ---

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/lib/python3/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "XXX/arbor/doc/conf.py", line 50, in <module>
    import make_images
  File "XXX/arbor/doc/scripts/make_images.py", line 2, in <module>
    import svgwrite
ModuleNotFoundError: No module named 'svgwrite'
```

Should doc generation run things in its own virtualenv?
And should the module be somehow bundled when we make releases, so that internet access is not required at point-of-install?

**Comment by bcumming** [comment]
This isn't an issue on readthedocs because the following:
https://github.com/arbor-sim/arbor/blob/master/.readthedocs.yml
Points to the following requirements.txt
https://github.com/arbor-sim/arbor/blob/master/doc/requirements.txt

**Comment by bcumming** [comment]
I don't fancy creating a virtual env each time I set up doc building locally. It would add time to building (well, at least the first time), and it is just putting lipstick on the Python packaging pig.

**Comment by halfflat** [comment]
Should then there be a test for it at CMake config time? (Like we do for Sphinx, for example.)

**Comment by halfflat** [comment]
We had a similar issue with Julia packages for the validation tests. back when they were being built in Arbor.
