### ISSUE TITLE
[Arbor 0.3.1-dev] No add_sphere attribute in flat_cell_builder()

### ISSUE THREAD

**Issue by lungsi** [arbor-sim/arbor#1129]
**Bug** :bug:
`flat_cell_builder()` in Arbor 0.3.1-dev does not have the attribute `add_sphere`. As a result, the [ball-and-stick example](https://arbor.readthedocs.io/en/latest/single_cell.html?) fails.

**To Reproduce**
| Arbor 0.3                   | Arbor 0.3.1-dev                                                                |
| :---------------------- | :------------ |
| `pip install arbor`       | `pip install git+https://github.com/arbor-sim/arbor.git` |
|  `import arbor`           | `import arbor`   |
| `builder = arbor.flat_cell_builder()`   | `builder = arbor.flat_cell_builder()` |
| `p = builder.add_sphere(radius=10, name='soma')`   | `p = builder.add_sphere(radius=10, name='soma')` |
| **No error**   | **Error**</br>---------------------------------------------------------------------------</br>AttributeError                            Traceback (most recent call last)</br>\<ipython-input-3-11dd81bb0702\> in \<module\></br>----> 1 p = builder.add_sphere(radius=10, name='soma')</br>AttributeError: 'arbor._arbor.flat_cell_builder' object has no attribute 'add_sphere'|

**Expected behavior**
| Arbor 0.3                   |
| :---------------------- |
| `pip install arbor`       |
|  `import arbor`           |
| `builder = arbor.flat_cell_builder()`   |
| `p = builder.add_sphere(radius=10, name='soma')`   |
| `q = builder.add_cable(parent=p, length=100, radius=4, name='dend')` |
| `p = builder.add_cable(parent=q, length=50, radius=(4,2), name='dend')` |
| `p = builder.add_cable(parent=q, length=50, radius=(4,2), name='dend')` |

**Screenshots**
![arbor_bug_add_sphere](https://user-images.githubusercontent.com/12233689/92357285-df23d300-f0e7-11ea-9581-f53d34a70392.PNG)

**System:**
 - OS: Ubuntu 20.04
 - Python 3.7
 - Arbor 0.3.1-dev (installed with `pip install git+https://github.com/arbor-sim/arbor.git`)

**Additional context**
As shown in the screenshot, `flat_cell_builder()` has attributes: `add_cable`, `add_label`, `build`, `labels`, `morphology`, and `segments`.

**Comment by bcumming** [comment]
Thanks for the detailed report @lungsi.

That documentation still needs to be updated, because Arbor does not support spherical somas, because try as we might, we could not consistently represent them using cylinders. Instead, you can add a branch with diameter and length equal to the diameter of the sphere.

For example:

```Python
import arbor
builder = arbor.flat_cell_builder()

# Create a cylinder with the same area as a spherical soma of radius 5 um
builder.add_cable(parent=arbor.mnpos, length=10, radius=5, name='soma')

# Attach two dendrites of length 100 um to the distal end of the soma cylinder
builder.add_cable(parent=0, length=100, radius=5, name='dend')
builder.add_cable(parent=0, length=100, radius=5, name='dend')

# Attach an axon to proximal end of the soma
builder.add_cable(parent=arbor.mnpos, length=30, radius=3, name='axon')
```

**Comment by bcumming** [comment]
I wouldn't rely on the `flat_cell_builder`, because it is likely to change, or be replaced before version 0.4.

The `segment_tree` interface, described in detail here https://arbor.readthedocs.io/en/latest/morphology.html#examples is stable, and won't change.

I will update the documentation now, with a warning in the text.

**Comment by bcumming** [comment]
The docs have been updated with a working `flat_cell_builder`. Does that work for you?
If you are serious about building morphologies, I strongly recommend that you use the `segment_tree` interface for now.
