### ISSUE TITLE
[Documentation Errata] Cannot create mechanism instance and set range simultaneously.

### ISSUE THREAD

**Issue by lungsi** [arbor-sim/arbor#1149]
**Documentation Errata** 
Cannot create an instance of `arbor.mechanism` (of desired channel), and set the conductance (range) during the creation of the instance as demonstrated in the [documentation](https://arbor.readthedocs.io/en/pydoc/mechanisms.html?#mechanism.values) 

**To Reproduce**
Doing
```
m4 = arbor.mechanism('passive/el=-45', {'g', 0.1})
```
returns
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-6144f3fe1526> in <module>
----> 1 m4 = arbor.mechanism('passive/el=-45', {'g', 0.1})

TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. arbor._arbor.mechanism(arg0: str)
    2. arbor._arbor.mechanism(name: str, params: Dict[str, float])

Invoked with: 'passive/el=-45', {0.1, 'g'}
```

**Expected behavior**
Based on the [documentation](https://arbor.readthedocs.io/en/pydoc/mechanisms.html?#mechanism.values) `m4 = arbor.mechanism('passive/el=-45', {'g', 0.1})` should have returned no errors as with the method of setting the range after creating the instance, i.e. no errors using the method below
```
m4 = arbor.mechanism('passive/el=-45')
m4.set('g', 0.1)
```

**Screenshots**
N/A

**System:**
 - OS: Ubuntu 20.04
 - Python 3.8
 - Arbor 0.3.1-dev (installed with `pip install git+https://github.com/arbor-sim/arbor.git`)

**Additional context**
N/A

**Comment by lungsi** [comment]
```
m4 = arbor.mechanism('passive/el=-45', {'g':, 0.1})
```
**should be**
```
m4 = arbor.mechanism('passive/el=-45', {'g': 0.1})
```

**Comment by halfflat** [comment]
Thanks for the report!
It's definitely a documentation bug, so I'll reopen it.
