### ISSUE TITLE
Single ion channels in default mechanism catalogue

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1156]
The 'hh' mechanism bundles its leak, Na+ and K+ currents in one mechanism, but a bit of flexibility in composing ion channels in a model would be welcome.

We can keep things simple, and restrict them to HH-style dynamics, and use the NeuroML `ionChannel` descriptions as a starting point.

**Comment by halfflat** [comment]
Options:
* Leave all this until we have an arblang target?
* See how the NeuroML NMODL work goes, and use that until we have a better solution?
* Make some channels suitably parameterized that could form part of further NeuroML support, without waiting for a full LEMSy translator or similar?

**Comment by thorstenhater** [comment]
:wave: we have external support for NML2, an arblang prototype, and quite good docs on how to write NMODL. 
Also, our stance on the included mechs has changed over the ABI merge, as users can easily add whatever they
need on their own.

I think we can safely close this. Feel free to re-open.
