### ISSUE TITLE
Modcc: better handling of integer powers

### ISSUE THREAD

**Issue by thorstenhater** [arbor-sim/arbor#1178]
Add optimisation to modcc: x^n where n is an integer constant (>0?) should be done using exp-by-squaring. This avoid spurious calls to exp *and* optimises mul-count in x^n for large n.

**Comment by noraabiakar** [comment]
I think this may be more trouble than it's worth in modcc. `std::pow` is likely doing a good job and it makes the generated code more readable.

**Comment by thorstenhater** [comment]
Ok, agreed.
