### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1224]
This issue has been updated.

- [ ] Enumerate and write down processes.
    - [x] How to add documentation?
    - [ ] How to add a test
    - [ ] How to add a model/simulation (to examples)
- [x] Issues template.
- [x] Issues beginner tag. 
  - [x] We should start using the tag and use in backlog review.
- [x] PR template.
- [ ] Remaining Github 'community health' items:
    - [ ] Code of Conduct. Do we need this or do we wait for a major incident?
    - [x] Content Reports: I can't find a clear description of what this is, I'm guessing a way to flag contributions to us/Github as unwanted.
- Good to know: Nest calls an overview of all of the above their [developer space](https://nest.github.io/nest-simulator/index). Maybe it's a good thing to have something like this to point at. #1437 is a way to have something similar.

A list of resources when considering the codifying contributing to Arbor (the above list can be amended):

[1] https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-up-your-project-for-healthy-contributions
[2] https://github.com/arbor-sim/arbor/community
[3] https://github.com/stevemao/github-issue-templates/
[4] https://nest.github.io/nest-simulator/development_workflow
[5] https://raw.githubusercontent.com/microsoft/vscode/master/.github/pull_request_template.md

**Comment by brenthuisman** [comment]
Update: I've been through the motions of the CII best practices badge, see [1]. Relevant for this discussion is the following 'fail':

* The project SHOULD respond to a majority (>50%) of enhancement requests in the last 2-12 months (inclusive).

We don't have an explicit time frame for handling Issues / Enhancement requests. We don't collects stats, but also don't have many Issues filed by external users yet. Personally I have noticed PR review can fall a little by the wayside. Maybe some explicit desired timeline would be helpful to give external users a good impression. Also, Backlog Pruning...

[1] https://bestpractices.coreinfrastructure.org/en/projects/4476

**Comment by thorstenhater** [comment]
I think we went as far as we can for now!
