### ISSUE TITLE
[tests] How to test a locset expression that uses a label.

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1230]
Related to issue #1229 , I wanted to add a test that checks on of the expressions that is failing in the Arbor gui. I'm taking this one: `(radius-lt "dend" 0.5)")`. Here's what I have so far:

```
    using pvec = std::vector<msize_t>;
    using svec = std::vector<mpoint>;
    auto sm = segments_from_points(svec{ {0,0,0,1}, {10,0,0,1} }, pvec{mnpos, 0});
    {
        region dend = reg::cable(0, 0.2, 0.3);

        label_dict dict;
        dict.set("dend", dend);

        auto ltdend = reg::radius_lt(region("dend"), 0.5);
        mprovider mp(morphology(sm), dict);
        EXPECT_EQ(to_string(ltdend), "(radius-lt \"dend\" 0.5)");   // TEST1
        EXPECT_TRUE(region_eq(mp, ltdend, "(radius-lt \"dend\" 0.5)"));     //TEST2
    }
```

Both TEST1 and TEST2 fail with same error:
```
C++ exception with description "error in label description at 1:1: Unexpected symbol 'dend' in a region or locset definition. If 'dend' is a label, it must be quoted "dend"." thrown in the test body.
```

I think TEST1 is supposed to fail, because it is not aware of any label_dict to which "dend" was added. TEST2 may just be wrongly copypasted together by me. How should I fix this?

**Comment by bcumming** [comment]
I am surprised that TEST1 fails with an exception: are you certain? If you comment out TEST2, does it still fail with an exception?

It fails for TEST2 because we try to parse `(radius-lt "dend" 0.5)`, which is an invalid region expression, because it should be `(region "dend")`, not `"dend"`.

**Comment by brenthuisman** [comment]
The source of the error is `auto ltdend = reg::radius_lt(region("dend"), 0.5);` Just adding this anywhere produces the error in the first post.

**Comment by bcumming** [comment]
Ah, right, now I see the problem. Using `region("dend")` tries to create a region by parsing the the string `"dend"`, which isn't a valid region expression. If you are constructing an expression using the C++ DSL, you have to use `reg::named` and `ls::named` to refer to a labelled region or locset respectively.

In this case:

`reg::radius_lt(reg::named("dend"), 0.5)`

**Comment by brenthuisman** [comment]
Thanks, that works!

**Comment by bcumming** [comment]
That's because `(radius-lt \"dend\" 0.5)` is not a valid expression: `"dend"` is a string, not a region.
You need to say `(radius-lt (region "dend") 0.5)`.
The docs are incorrect:
`"soma": a shortcut for the region with the label “soma”.`
should be removed.

**Comment by bcumming** [comment]
I checked the git blame for that line in the docs, and it was added by you @brenthuisman.
The original version only had `(region "soma")`.

**Comment by brenthuisman** [comment]
Hmm, that must be because git understandably failed to track one of my many changes during the docs restructure. I never touched those pages ;)
