### ISSUE TITLE
Morphology writers

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1233]
Add support for writing morphology representations in arborio:

1. <s>`save_swc_XXX` counterparts to `load_swc_XXX` functions, which will roundtrip morphologies provided they abide by the constraints of the corresponding representation.</s>

2. Writing morphologies (and maybe regions, too, via segmentGroups) to NeuroML. Handling regions, at least where they do not align exactly with segments, will require subdividing segments, presumably linearly.

3. (New) Specify and implement an S-expr representation for segment trees, and make the corresponding reader and writer. While regions etc. already have a perfectly good representation, should we also have a representation of their concrete realisations, so that they can be more easily shared across other sims?

**Comment by bcumming** [comment]
Very good idea!
However, in the past you and I have decided that `write_swc` should not be implemented in Arbor
1. We can't represent our morphology representations using swc (except for a handful of corner cases)
2. We really don't want to have solve the "reverse interpretation" problem of converting the different soma representations into swc samples.
2. Users should not be encouraged to use SWC.

**Comment by halfflat** [comment]
The discouraging people from using SWC at all I think is the strongest argument here :)

**Comment by thorstenhater** [comment]
Hey,

ACC was decided to be our internal format of choice and we do not consider ourselves a neuroscience I/O library.
Closed until considered interesting.
