### ISSUE TITLE
Proposal: remove time parameter from mechanisms.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1252]
Time was added as a visible value to NMODL mechanisms in order to incorporate time-dependent current sources. But apart from the impact of #1251, there are a couple of reasons to seek an alternative approach:

1. The integration can't see any discontinuities in the input current source, which prevents us from adjusting integration steps to match any such discontinuities.
2. It's insufficient for representing arbitrary time-dependent input currents, without also providing facilities for loading into the mechanism arbitrarily large representations of these current values.

I'd prefer that we extend the existing stimulus interface to encompass this use case:
* Provide stimulus options that correspond to common experimental stimulus protocols.
* Provide a stimulus current class that can represent e.g. arbitrary piecewise-linear current curves.

**Comment by espenhgn** [comment]
Please add a feature for voltage clamps which allows for arbitrary long sequences of piece-wise constant holding potentials as well.

**Comment by halfflat** [comment]
I think I'll make voltage clamps a new, separate issue!

**Comment by halfflat** [comment]
As part of #1262 work, current stimuli are being moved out of mechanisms. The current WIP implementation supports piece-wise linear stimulus currents defined by an envelope, or a fixed frequency stimulus with an amplitude governed by a piece-wise linear envelope.

**Comment by halfflat** [comment]
Stimuli as mentioned above have been moved library-side in PR #1407 — if the functionality there is insufficient to cover the cases currently implemented in NMODL, we'll have to look at this further.
