### ISSUE TITLE
Probes for LIF cells.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1263]
LIF cells currently are unprobeable. Apart from the functionality itself, probe implementations on more than one cell kind will help ensure that the probe APIs remains general.

Proposed probe types:
* Membrane voltage.
* (Maybe) exponential moving average inter-spike delay.

**Comment by thorstenhater** [comment]
This issue requires a bit of thought:
LIF cells are integrated by analytical solution between steps, so probing in between requires interpolating 
into said solution.
