### ISSUE TITLE
Extracellular electric stimulation

### ISSUE THREAD

**Issue by espenhgn** [arbor-sim/arbor#1270]
**Is your feature request related to a problem? Please describe.**

Feature, not a problem. Extracellular electric stimulation of individual neurons and circuits in vitro and in vivo are quite commonplace. Any plans of incorporate a feature which would facilitate mimicking such experimental setups? 

**Describe the solution you'd like**

An option to impose the (time-varying) electric potential immediately outside each CV as a boundary condition instead of the typical assumption of zero extracellular potential while solving for the membrane voltages, equivalent to the `extracellular` mechanism in NEURON. The very same electrostatic forward models as defined by for instance LFPykit mapping transmembrane currents to recorded potentials at some electrode(s) can be used to map stimulating electrode currents to the extracellular potential outside each compartment.

**Comment by thorstenhater** [comment]
Hi @espenhgn,

since #2033 we allow more or less direct manipulation of the membrane potential based
on density mechanisms. I am not sure we will ever support an 'extracellular mechanism'
in the style of Neuron; coreNeuron doesn't have it either and this always scares me away
from trying:

> Extracellular potentials do a great deal of violence to one’s intuition and it is important that the user carefully consider the results of simulations that use them. It is best to start out believing that there are bugs in the method and attempt to prove their existence.

See https://www.neuron.yale.edu/neuron/static/py_doc/modelspec/programmatic/mechanisms/mech.html?highlight=extracellular

If voltage processes are enough, could you close this?

**Comment by espenhgn** [comment]
Thanks, I don't need this right now, so I'm closing this for now. But I've asked @torbjone for a second opinion.

**Comment by torbjone** [comment]
Hi @thorstenhater,
that is a great quote, and I've felt this violence to my brain several times :-)

I'm not sure if the alternative works, but it could relatively easily be tested against analytic formulas etc., although I will probably not look into that unless there is a specific need.

Best,
Torbjørn

**Comment by thorstenhater** [comment]
The main problem seems to be that the equivalent electric circuit (eec) of the cable model is heavily complicated
by the extracellular 'mechanism'. The EEC is shown in NRN docs as this:
```
          Ra
o/`--o--'\/\/`--o--'\/\/`--o--'\/\/`--o--'\o vext + v
     |          |          |          |
    ---        ---        ---        ---
   |   |      |   |      |   |      |   |
    ---        ---        ---        ---
     |          |          |          |
     |          |          |          |     i_membrane
     |  xraxial |          |          |
 /`--o--'\/\/`--o--'\/\/`--o--'\/\/`--o--'vext
     |          |          |          |
    ---        ---        ---        ---     xc and xg
   |   |      |   |      |   |      |   |    in  parallel
    ---        ---        ---        ---
     |          |          |          |
     |          |          |          |
     |xraxial[1]|          |          |
 /`--o--'\/\/`--o--'\/\/`--o--'\/\/`--o--'vext[1]
     |          |          |          |
    ---        ---        ---        ---     the series xg[1], e_extracellular
   |   |      |   |      |   |      |   |    combination is in parallel with
   |  ---     |  ---     |  ---     |  ---   the xc[1] capacitance. This is
   |   -      |   -      |   -      |   -    identical to a membrane with
    ---        ---        ---        ---     cm, g_pas, e_pas
     |          |          |          |
-------------------------------------------- ground
```
and the implementation is done via inserting extra rows into the Hines matrix. These
extra rows violate the tree structure of the matrix, necessitating use of a different
solver.

**Comment by espenhgn** [comment]
Hi. I'm not sure if we need to account for this additional circuitry of the extracellular mech in NEURON, which I believe was mainly incorporated to allow for models of mutual interactions between parallel cables via the extracellular potentials say in axonal fiber tracts, but was later used as a bit of a hack.

For our intended purpose, we may look at perturbing the membrane potential perhaps via 
```
NEURON {
    VOLTAGE_PROCESS ve
    GLOBAL ...
}

PARAMETER {
    ...
}

BREAKPOINT {
     v = v + ve
}
```
where `ve` would correspond to the imposed extracellular potential on the outside boundary for a given time segment.

**Comment by thorstenhater** [comment]
Similar to this, yes. If you need time dependent `ve` this could something to consider:
```
NEURON {
    VOLTAGE_PROCESS ve
    GLOBAL ...
}

PARAMETER {
    dt : timestep
    alpha
}

STATE { t }

INITIAL { t = 0 }

BREAKPOINT {
     SOLVE dT METHOD cnexp
     LOCAL ve : target voltage
     ve = ... : Some function of t
     : Nudge v towards ve
     v = v - alpha*(v - ve)
}

: This gives us t
DERIVATIVE dT { t' = dt }
```

For an unrelated project I have implemented the method by Rattay (1986) based on the
derivative of `U` along the dendrite; maybe I can open the non-specific parts of this.

**Comment by torbjone** [comment]
Just a note on the last point: As I understand the method of Rattay, it essentially assumes an infinite dendrite/axon, and does not take into account the effect at the dendritic/axonal end points. In my experience, the end points are actually where the effect of the external extracellular potential is strongest, so for all cases I have worked with, this approach based on the derivative of U didn't really make sense to me.

**Comment by thorstenhater** [comment]
Ok,  this discussion has become really interesting source of information. I see the problem with the endpoints, but
technically you can still compute $U''(x)$ along the dendrite even if it's ending at $x$.

What alternate method could one use? My overview the field is limited to the technical side.
