### ISSUE TITLE
Compiler error when writing to ion concentrations

### ISSUE THREAD

**Issue by thorstenhater** [arbor-sim/arbor#1276]
**Describe the bug**
Putting an ion concentration into `WRITE`, but not into `STATE` will cause C++ compile
errors when `ARB_VECTORIZE=ON`.
See here https://github.com/arbor-sim/arbor/wiki/Arbor's-NMODL-guidlines

Example (Edit: I added the correct file from @noraabiakar's comment below)
```
:TITLE Ca Pool
TITLE Mod file for component: Component(id=CaPoolTH type=fixedFactorConcentrationModel)
NEURON {
    SUFFIX CaPoolTH
    USEION ca READ ica WRITE cai VALENCE 2
    RANGE resting_concentration
    RANGE decay
    RANGE rho
}
UNITS {
    (A)     = (amp)
    (mM)    = (millimolar)
}
PARAMETER {
    resting_concentration =  0.0       (mM)
    decay                 = 11.5943    (ms)
    rho                   = 2.38919E-4 (mM m2 /A /s)
}
STATE    { concentration (mM) }
INITIAL  { concentration = cai }
BREAKPOINT {
    SOLVE states METHOD cnexp
    if (concentration < 0) { concentration = 0 }
}
DERIVATIVE states {
    concentration' = rates(ica)
    cai            = concentration
}
FUNCTION rates(ica) {
    rates = -0.01*ica*rho - (concentration - resting_concentration)/decay
}
```

**Expected behavior**
An error is thrown, both with and without vectorization if not all of the following is true
- `Xi` appears in the `STATE` block
- `Xi` is initialised with a valid expression, ie not depending on `Xi` or other unintialised values.
- Per symmetry, the same holds or `Xo`

**Comment by noraabiakar** [comment]
Actually modcc *does* throw an error for this file:
```
error: mech.mod (line 24,col 21) 
the variable 'cai' must be a state variable to be differentiated
```
However, in the previous iteration of the file:
```
:TITLE Ca Pool
TITLE Mod file for component: Component(id=CaPoolTH type=fixedFactorConcentrationModel)
NEURON {
    SUFFIX CaPoolTH
    USEION ca READ ica WRITE cai VALENCE 2
    RANGE resting_concentration
    RANGE decay
    RANGE rho
}
UNITS {
    (A)     = (amp)
    (mM)    = (millimolar)
}
PARAMETER {
    resting_concentration =  0.0       (mM)
    decay                 = 11.5943    (ms)
    rho                   = 2.38919E-4 (mM m2 /A /s)
}
STATE    { concentration (mM) }
INITIAL  { concentration = cai }
BREAKPOINT {
    SOLVE states METHOD cnexp
    if (concentration < 0) { concentration = 0 }
}
DERIVATIVE states {
    concentration' = rates(ica)
    cai            = concentration
}
FUNCTION rates(ica) {
    rates = -0.01*ica*rho - (concentration - resting_concentration)/decay
}
```
We don't attempt to differentiate `cai` so no error is thrown. I think that we can throw an error either if `cai` is written in the code, or if it classified as WRITE.

**Comment by noraabiakar** [comment]
Upon revisiting this issue, I think modcc's behavior is adequate. The original code snippet generates an exception. The modified code snippet from the previous comment doesn't generate an exception, nor should it. 
#1528 examined the behavior of both arbor and neuron with respect to how they update ion concentrations, and the results are consistent. `Xi/Xo` need to be in the `STATE` block only if the quantity is being differentiated. 

`Xi`, `Xo` initialization is a separate issue. Neuron allows ion concentration initialization from nmodl, arbor only allows it from the simulator side. I don't quite understand what this line: `Xi is initialised with a valid expression, ie not depending on Xi or other unintialised values.` means.

**Comment by thorstenhater** [comment]
Clarification
```
Xi = Xi 
```
assigns file local `Xi` to global `Xi`. But as `Xi` is uninitialised, the local `Xi` is undefined.
Setting 
```
Xi = 42.0
```
is well-defined and thus works.

**Comment by thorstenhater** [comment]
This isssue was not questioning whether this should produce a well-defined mechanism, but I think it's a problem that the error is thrown when compiling the transpiled C++ rather than earlier, when analysing the NMODL. Per original issue text this happens iff VECTORIZE=ON.

**Comment by noraabiakar** [comment]
I just tested this again. The original mechanism throws an error when compiled with modcc: 
`the variable 'cai' must be a state variable to be differentiated`.
Can you reproduce this and point out what error was thrown?

**Comment by noraabiakar** [comment]
I think you meant the second mechanism I posted, not the original one.

**Comment by thorstenhater** [comment]
I meant the original issue description, like the comment says.

**Comment by thorstenhater** [comment]
The issue is still valid is stated: building the mechanism results in a C++ compiler error, iff `VECTORIZE=ON`. 
`modcc` should raise an error, not `c++`. For reference

```
[ 80%] Building CXX object CMakeFiles/test-catalogue.dir/generated/test/test_old_cpu.cpp.o
/private/var/folders/qd/zftlxfrn4zd2fdg6p3fcxfgh0000gn/T/tmpioby7sjc/build/generated/test/test_old_cpu.cpp:87:24: error: use of undeclared identifier 'w_'
        t_cai = S::fma(w_, cai, t_cai);
```

**Comment by thorstenhater** [comment]
Seems resolved, closing this.
