### ISSUE TITLE
Documentation: update citation guidelines

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1297]
The RTD documentation only mentions the article citation, and the README offers only Zenodo DOIs for the software (as opposed to the published article).

We should make it easy for others to cite the software itself, as well as the article discussing it, by providing a full example citation and cut-and-pasteable BibTeX entry.

**Comment by brenthuisman** [comment]
1. Let's have Nora's name fixed.
2. Bibtex entry for Zenodo.
