### ISSUE TITLE
Consistent spelling of 'discretise' across comments, code, API

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1305]
If we're adopting EU style guidelines for spelling, which prefer 'discretise' over 'discretize', the code and API should be updated to suit. (The code/API usage of 'discretize' and 'discretization' is my fault!)

In order to minimise (see what I did there) user confusion, we'd ideally avoid ambiguous spellings in API methods etc., if we can find a good alternative.

**Comment by brenthuisman** [comment]
As @noraabiakar noted, we even use en_US for the API. Also, 'centre' vs 'center'.

My beef with EU guidelines, or using en_GB, is that a lot of APIs use en_US, so by deviating from that informal consensus we're creating the possibility for hard-to-spot typos. I prefer consistency over a particular spelling. I also dislike not having a en_EU dictionary, because that means for some words I'll have to *remember* where it deviates from en_GB, and I hate remembering things. Having a contributor spell check is fine, but having them go though more than that is really not pleasant. That burden should be on us (we could schedule a quarterly spell check PR for instance), or on language assistance from Ebrains, if sticking to the guideline is that important (which I sincerely doubt).

Considering the above, I propose the following:
1. let's use en_US
2. done!

**Comment by halfflat** [comment]
Just for clarification: the -ize stuff is OED spelling, that happens to align with US spelling on this point :)

**Comment by halfflat** [comment]
'center' is always going to look wrong to me, and I think it's best avoided altogether, if we can simply use e.g. 'midpoint' instead.

**Comment by brenthuisman** [comment]
I'm OK with avoiding words that are spelled differently, 'center' has made it's way into every example however. And frankly, I've only ever encountered it spelled 'centre' in Britain!

As long as there's no en_EU or OED dict to point spellcheckers too, I don't think it can be considered a requirement for contributions. Requiring knowledge of OED rules is not productive. Moreover, this is the first time I've actually had someone argue for that in the context of EU funded projects. I have not found an actual requirement of this, is there?

**Comment by halfflat** [comment]
In the very PR up for review, there is a "centre" to "center" change. "Centre" is the standard spelling outside of the US, and is the spelling that should be used in EU documents. The only question at hand is: do we follow these style guidelines in documentation and code as well?

Two main motivations for doing so:
* consistency across documents, and
* closer adherence with the varieties of English used in Europe.

You also cannot rely upon automatic spelling dictionaries; they are routinely incomplete and broken. It's not a matter of remembering 'OED rules', it's a matter of picking the correct spelling of a word from the various alternatives, based on concerns such as clarity, consistency, register, and local norms. Sometimes this will mean looking something up in a dictionary.

The only reason to use US spellings, as far as I can see, is alignment with other software, including standard libraries, that uses that spelling. US English is the exception, not the rule: despite its visibility, especially in software, most English used and taught around the world is much closer to UK varieties.

**Comment by brenthuisman** [comment]
There is no such thing as standard spelling outside the US. If anything, it would be US spelling.

If you check the page the PR changed, it included _both_ spellings simultaneously before. Every other occurrence in Arbor's codebase (examples) is spelled 'center', hence this change.

A debate on what's taught were has no bearing on this discussion.

**Comment by thorstenhater** [comment]
I would propose a _consistent_ guideline, splitting that between API and docs is fine for me.
There is always a gap between long-form prose and short-hand notation. Further, should we
be required to submit parts of the documentation as an official document, that would be made
very easy. Also, I personally prefer UK english over US, but please not the EU pidgin.

There is no need in rejecting contributions over these minutiae, we should have them fixed 
automatically.

**Comment by halfflat** [comment]
While I strongly agree with @thorstenhater, I just want to make the distinction between Euro English and EU Style Guide English: the former is a pidgin, and the latter lines up pretty much with 'official' English used in England.

**Comment by brenthuisman** [comment]
Conclusion after lengthy debate:

- Avoid words with different spelling if possible
- Use en_GB
- Irregular or semi-regular audits of the docs can include corrections of existing spelling in the above direction.

**Comment by brenthuisman** [comment]
For reference, my personal viewpoint is more or less the one Wikipedia arrived at:
https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style#National_varieties_of_English

**Comment by thorstenhater** [comment]
Hey, 

the docs are consistent in EU spelling and the API as well, but in US. I think US is expected for code and noone complained so far, so let's get rid of this. As always, feel free to reopen.
