### ISSUE TITLE
Search does not terminate for unexisting search terms

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#1307]
The search on readthedocs.io does not terminate for a search requests without results, e.g. "foobar": https://arbor.readthedocs.io/en/latest/search.html?q=foobar&check_keywords=yes&area=default

**Comment by noraabiakar** [comment]
This seems to be a problem with the Sphinx version. The search functionality of this [build](https://arbor.readthedocs.io/en/doc-test/search.html) of latest Arbor with Sphinx version 3.2.0 works.

**Comment by noraabiakar** [comment]
I think this is related to the theme we use. I opened an issue with sphinx_rtd_theme: https://github.com/readthedocs/sphinx_rtd_theme/issues/1037

**Comment by thorstenhater** [comment]
This seems to be the default behaviour of readthedocs ... tried with several projects now. I think it's not worth for us to do something here.
