### ISSUE TITLE
Deal with loops and autapses

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1309]
Creating cells that features loops or [autapses](https://en.wikipedia.org/wiki/Autapse) has come up. Currently not supported, or possible (Arbor's morphology is a acyclic directed graph). A gap_junction from a cell unto itself might be a sufficient alternative, but might not be.

**Comment by halfflat** [comment]
Just for reference, afaik NEURON deals with this via gap junctions.

**Comment by halfflat** [comment]
Random NEURON forum post: https://www.neuron.yale.edu/phpBB/viewtopic.php?t=1949

**Comment by halfflat** [comment]
Proposal: we find a real example that we can verify works in Arbor — or doesn't work in Arbor, and then we fix it.

**Comment by thorstenhater** [comment]
Here _might_ be an example; did not check the paper
https://senselab.med.yale.edu/ModelDB/ShowModel?model=183718

**Comment by thorstenhater** [comment]
Can be handled by self-connections or closed-loop gap junctions.
