### ISSUE TITLE
Link in python/readme.md invalid

### ISSUE THREAD

**Issue by laserrapt0r** [arbor-sim/arbor#1314]
**Describe the bug**
The link "Read the Docs" in python/readme.md is invalid 

**To Reproduce**
go to python/readme.md and click on Read the Docs

**Expected behavior**
Link to https://arbor.readthedocs.io/en/latest/python/ instead of https://arbor.readthedocs.io/en/latest/python.html

**Screenshots**
![image](https://user-images.githubusercontent.com/68563050/104837108-cc4db600-58b2-11eb-8670-4766ac603cb6.png)

**System (please complete the following information):**
any system

**Additional context**
none

**Comment by brenthuisman** [comment]
Thanks for the report, @laserrapt0r ! Merging a fix should be soon!
