### ISSUE TITLE
NSUITE should be buildable with the current release

### ISSUE THREAD

**Issue by thorstenhater** [arbor-sim/arbor#1316]
I propose to tighten the integration of NSUITE with arbor so that NSUITE releases work with Arbor releases and similar for the current head. This would make it easier to track performance for each release and eliminate the hassle of porting NSUITE.

To this end, I suggest making NSUITE part of the `bors try` (or an extra `bors nsuite`) request and thus the GitLab CI pipeline.

**Comment by brenthuisman** [comment]
#849

**Comment by thorstenhater** [comment]
As a first solution:
- Add Github CI to nsuite,
- Run nightly with arbor/master

**Comment by thorstenhater** [comment]
That PR has been merged, closing.
