### ISSUE TITLE
S-expressions for `cv_policy`. 

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#1334]
This could possibly look like: 
```
1. (explicit locset-expr optional-region-expr) // Generates cv_policy_explicit(locset, region)
2. (single optional-region-expr)               // Generates cv_policy_single(region)
3. (max-extent float optional-region-expr)     // Generates cv_policy_max_extent(float, region)
4. (fixed-per-branch int optional-region-expr) // Generates cv_policy_fixed_per_branch(int, region)
5. (every-segment optional-region-expr)        // Generates cv_policy_every_segment(region)
6. (join (cv-exp0) (cv-exp1))                  // Generates cv-exp0 + cv-exp1
7. (replace (cv-exp0) (cv-exp1))               // Generates cv-exp0 | cv-exp1
```
This would aid in developing a format for describing cabel-cell.

**Comment by thorstenhater** [comment]
Hi,

looks good, but here's a few nitpicks and questions

- 2. and 5. seem to be identical
- Why the need for replace? 
  - I would expect an overwrite to be simply done by setting twice on the same region, if
possible at all. 
  - In a declarative format like this I am unsure of the value of assignment.
- A word of what these expressions do would be appreciated, although this information can extracted from the API.

I have asked more, internal questions elsewhere and might update this as needed.

**Comment by noraabiakar** [comment]
My first comment had a typo and wasn't very clear, so I've edited it to fix the mistakes and add some clarifications. 
* You're right, 2 and 5 were identical, that's been fixed. 
* The `replace` represents the `|` operator:  `cv-exp0 | cv-exp1` generates a policy from `cv-exp0` except in the domain of the `cv-exp1`, where the `cv-exp1` policy is used.

**Comment by noraabiakar** [comment]
It's been suggested on the slack that `patch` might be a better choice than `replace`.

**Comment by bcumming** [comment]
Instead of `join` and `replace` as operations, how about just using the same operators `+` and `|`, e.g.
```
(| (fixed-per-branch 4 (tag 3)) (single))
```

**Comment by thorstenhater** [comment]
Visually a bit straining (Imagine picking it under `((((|(((...`), but I like the symmetry with our C++ API.

**Comment by akuesters** [comment]
missing #1765
