### ISSUE TITLE
Documentation recategorization

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1353]
Nora and I propose the following actions to arrive at a slightly reordered and better organized documentation, ready for future contributions and updates.

* New pages for every cell kind/description. Under Concepts, alongside Cable Cell. The current Cell page can stop after introducing the Cell description concept, and refer to the Cell kinds.
* Move Cable Cell component pages in hierarchy under Cable Cell
* New page: Cable cell probing and sampling
    * probes go here
    * sampling API goes here (public part from internals/sampling)
    * Definitions erroneously are now in python/simulation.rst.
* Move content: HPC Distributed context,Dry-run -> into CPP->Hardware
    * +refactor of CPP->Hardware
    * update Concepts->Hardware to reflect above content, is stub right now
    * This cancels the HPC section
* New section: File formats
    * NeuroML (moved from C++)
    * NMODL (moved from Internals)
    * SWC (break out of Cable Cell Morphology)
    * etc.
* Internals
    * keep simd
    * maybe some of the sampling API stays.
    * ~Delete "Utility wrappers and containers" -> we use C++17 now.~
    * (later: #1344 ?)
* Concept block
* API block
    * Python
    * CPP
    * File formats
* Problem: current Sphinx RTD theme mixes page and project TOC. This interferes with deeper hierarchies (see C++ -> Cable Cell)
    * Change theme. Furo does not mix page and project TOC.
    * Handled with separate PR: https://github.com/arbor-sim/arbor/pull/1362

The discussion on tutorials are split off this issue, now at: https://github.com/arbor-sim/arbor/issues/1369

Preview the recategorization at: https://arbor-rtd-dev.readthedocs.io/

**Comment by halfflat** [comment]
Regarding the utility wrappers and containers: the `unique_any` and `any_ptr` classes are our own, and are still relevant. They don't correspond to any C++17 standard library functionality.

**Comment by bcumming** [comment]
I agree with the reorganization at a high level. I would suggest that the first step would be to reorganise the content without significant changes or additions to the content. That way we can separate discussion about the content from discussion about structure of the docs.

The one part of the reorganisation I want to comment on specifically is the tutorial and how-to/example part.

## Tutorial

I would like to have the tutorial docs be a series of tutorials that build on and extend the results of the previous tutorial.

* The tutorial focusses on building a network of *cable cells*, starting with a single cell model.
* The tutorial does not have to cover everything. I would try to avoid anything that gets in the way of understanding how to build a model.
  * it doesn't have to cover the profiling tools (they can go in an example)
  * it doesn't have to cover domain decomposition (have an example that shows domain decomposition approaches)
  * it doesn't have to cover hardware: the tutorial can show how to run the model using multiple threads, and provide a link to an example that shows how to add MPI and GPU support. Optionally, there could be one final step in the tutorial that shows how to use MPI/GPU, but it should come after the basics of building a model has been shown, to avoid mixing model description and hardware concepts.

## Examples/How-To

Each Example should be self contained, and illustrate practically how to use the Arbor interface. We can create examples that try to address commonly asked questions from users.

The examples don't need detailed descriptions in the documentation:
* The example should be self-documented
* The docs can have a list of examples/how-tos with a brief description and a link to the source
* We could also refer to examples from elsewhere in the docs, e.g. `The examples/mpi_output.py example shows an approach for handling sampler output for distributed models` could appear in the documentation for the samplers. 

Some examples could include
* An example that shows how to load from swc files, and goes through the different options available
* An example of NeuroML input
* An example that shows how to read a json description from Allen DB and map it onto Arbor
* An example that shows how to create a single cell model in Arbor-GUI
* An example that shows how to use the built in profiling/metering tools
* an example that shows how to provide a custom domain decomposition

**Comment by brenthuisman** [comment]
This friday Nora and I have a meeting scheduled where we'll come up with a more planned out series of tutorials. We've a few 'lines' in mind along which we want to develop the concepts and increase the complexity, and then perhaps have a few tutorials tying things together. We'll take this comment into account.

This issue is about the slight reorg only, indeed, we're not proposing to make changes to the content in the PR that will address this, those come later.
