### ISSUE TITLE
Documentation: tutorial structure, howtos

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1369]
## Proposal

First, to bring a bit more structure to the tutorials, here is what Nora and I came up with:

### Tutorial

Have a few topics which build up in complexity. Reduce the introduction of concepts already introduced, unless it can be done very briefly, otherwise link to the (section in) the tutorial where it was introduced. Make the "Concepts covered in this example:" box more focussed, but do not *implicitly* rely on previously intro'ed concepts.

Topics:
* cell
    * simple cell
    * complex cell
    * cell from a database? (allen)
* network
    * simple network (take a simple cell already intro'd)
      * https://github.com/arbor-sim/arbor/pull/1313
    * complex network (mix multiple types of cells, take ones intro'd)
    * populations of cells
* probe
    * use C++ probe-demo for inspiration
    * how to gap junction?
    * how to probe everything on a cell?
* IO
    * An example of NeuroML input
    * SWC modes
* Performance
    * Run with mpi, on gpu. Can be brief.
    * built in profiling/metering tools
    * a custom domain decomposition
    * Perhaps tutorial where we use profiling to find a bottleneck, which we then solve with a customized domain decomp or hints?
      * https://github.com/brenthuisman/arbor/tree/ex_hardware

### Howtos/Examples

We couldn't come up with a good threshold for when something stops being a tutorial and starts being a howto. Here are a few proposed definitions:

* A howto is everything that doesnt need/deserve documentation.
* Dont need to go into every detail in a howto
* A howto is not a contrived example but a possible real world one
* A tutorial covers Arbor concepts, a howto does not.

For the time being, we propose to solve it by advertising a link to `/examples` (on GH) front and center on the Tutorial overview page. A howto will not have a page in the docs, but will have a link and short description on the Tutorial overview. They will be referred to as examples. I will exercise editorial prerogative to promote an example to tutorial. It may not be very important to make the distinction sharper than this, but, if you feel it needs to be, and you have a good criterion, then please reply ;)

Proposed Examples (insofar they don't already
* examples
    * An example that shows how to read a json description from Allen DB and map it onto Arbor
      * https://github.com/brenthuisman/arbor/tree/ex_allen
      * Describing the provenance of the data does require some detailing, as well as setting up a complex decor. Maybe it can be our most complex cell tutorial?
    * run sth from a online database. A non-Allen example?
    * An example that shows how to create a single cell model in Arbor-GUI
    * OpenWorm: https://github.com/KirHarms/neuro_sim_c_elegans/blob/main/DD1_sim_with_recipe.py
    * https://github.com/arbor-contrib/hodgkin-huxley-sensitivity-analysis

## Older ideas:

- [x] Example 1 (already there): Single dendrite model
Focuses on the basics, explains the code, adds some simple dynamics: HH and a current clamp.
Additional section at the end about discretization: The whole cable has the same current/conductance/voltage, what if we want these parameters to vary across the cable? 
      -  Have more segments and use cv_policy_every_segment
      -  Have only one segment and use cv_policy_max_extent
- [x] Example 2: Soma + Y dendrite tree
Focuses on the more complex morphology, with discretization, and use simple region and locset expressions: tags and terminal, maybe try to join some simple expressions (on_branches + tag)
Additional section on SWC: How to get the same morphology using SWC
- [x] Example 3: Soma + slightly branchier dendrite tree and an axon - This will be the final iteration of the morphology.
Again, morphology + discretization explained 
More complex regions and locset expressions. Try to cover and explain as many as possible.
Additional section on SWC: Again, how to get the same morphology using SWC .
- [x] Example 4: Same morphology as (3) + setting parameters.
Set parameters at the global, cell, and regional level.
Additional section on what can be set and at which level. 
- [ ] Example 5: Same morphology as (3) + different catalogues and nernst
Additional section on how the reversal potential can only be manipulated using special mechanisms. 
- [ ] Example 6: Same morphology as (3) + new ions and setting mechanism parameters
Use new ions (other than the default ca, na, k)
Set mechanism global/range parameters. 
- [ ] Example 7: Same morphology as (3) + different stimuli
- [ ] Example 8: Same morphology as (3) + different probes
- [x] Example 20: An AllenDB model (single cell).

**Comment by halfflat** [comment]
Proposal for aiding correctness of (at least) Python example walkthroughs:
* We use some form of literate programming for the Python examples in the source tree.
* These examples are run in CI (as they are currently).
* The documentation building transforms the literate Python code into the corresponding example doc page.

**Comment by brenthuisman** [comment]
Use https://docs.python.org/3/library/doctest.html ?
