### ISSUE TITLE
Support CONDUCTANCE keyword in modcc?

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1380]
We currently (ha) compute the conductance by symbolic differentiation of the current assignment expression. Notwithstanding other issues in this process (see #794), the resultant expression may be very expensive, and not amenable to automatic algebraic simplification. In these instances, a user supplied CONDUCTANCE could supply a 'good enough' approximation at much lower computational cost.

The CONDUCTANCE keyword was added to NMODL by the BBP in order to improve upon the numerical difference scheme that was previously used, and now is optional with the use of the NMODL Framework (see: https://bluebrain.github.io/nmodl/html/notebooks/nmodl-sympy-conductance.html).

**Comment by thorstenhater** [comment]
We _parse_ and then igore `CONDUCTANCE` statements for now. Our best practices tell users to write
```
  LOCAL g
  g = ...
  i = g*(v - e)
```
instead of `i = (...)*(v - e)` to avoid overheads.

**Comment by thorstenhater** [comment]
Given these ideas, I think it's better not to force users to supply their and instead rely on automatic differentiation and some optimisation to obtain the same effect.

Closed until further notice.
