### ISSUE TITLE
modcc: adding statements before the `SOLVE` statement in the `BREAKPOINT` block

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#1384]
When we perform function inlining, we have to create some local variables and initialize them to zero. These statements go on the top of the statements list. This causes a compiler bug if there is a function call in the `BREAKPOINT` block of an nmodl file: 
```
BREAKPOINT {
SOLVE state method cnexp
i = foo(g) * (v -e)
}
FUNCTION foo(x) {
foo = x + 5
}
```
After foo is inlined, the BREAKPOINT block looks as follows (pseudo-code)
```
local t_
t_ = 0
solve(state, cnexp)
t_ = g + 5
i_ = t_ * (v - e) 
```
Right now, we only allow local declarations before a `SOLVE` statement. The compiler will complain about the assignment `t_ = 0`. We should either allow initializing local variables before a `SOLVE` statement, or remove the requirement that the `SOLVE` statement be first in a `BREAKPOINT` block.

If we remove the requirement that `SOLVE` has to be first, then all code before that statement is part of the current update, and only the `SOLVE` statement will be part of the state update. For example: 
```
BREAKPOINT {
g = 9
SOLVE state method cnexp
i = foo(g) * (v -e)
}
```
If the `SOLVE` statement reads `g`, the state update will not see that it was written to `9`. Only the current update will. This behavior is consistent with NEURON (tested with `nrnivmodl`).

**Comment by halfflat** [comment]
Would it be possible to do the inlining after separating out the SOLVE? We can certainly match NEURON behaviour, but I really feel that this is a NEURON misfeature.

**Comment by noraabiakar** [comment]
Probably, but it'll take a fair bit of work to make sure we don't break anything, I don't trust our unit tests to catch all potential bugs resulting from a quick fix.

**Comment by noraabiakar** [comment]
But we can just check that the SOLVE is the first statement (without separating it out) before we start function inlining.

**Comment by halfflat** [comment]
If it's a lot of work, then let's just go bug-for-bug compatibility with NEURON and flag the issue for consideration down the road. And of course, document it :)
