### ISSUE TITLE
Specialized sampler callback for LFP calculations.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1385]
In #1115 a number of options were floated for local field potential calculations. While Option 1 has been implemented using the generic sampling infrastructure available in the C++ and Python interfaces, @espenhgn has pointed out that the memory usage could become prohibitive in long simulations, and that the second option, viz. a specialized sampler callback for LFP calculations, would be more robust.

This would comprise a specialized callback that takes transmembrane current samples from one or more cells, initialized with a linear response matrix computed by the client code for summing the corresponding field contributions at electrode sites. The sampler would record the electrode contributions either in sum, or individually from each cell (for reproducibility), to some in-memory data store for global reduction and analysis at simulation end.

**Comment by thorstenhater** [comment]
Subsumed by #1857
