### ISSUE TITLE
make_static_property_type(): failure in PyType_Ready()

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1398]
**Describe the bug**
When building arbor from source and importing it the following error occurs:
```
(arb-cat) robin@TNG2019:~/git/arbor/build$ python
Python 3.9.1 (default, Feb 18 2021, 16:03:49)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arbor
terminate called after throwing an instance of 'std::runtime_error'
  what():  make_static_property_type(): failure in PyType_Ready()!
Aborted
(arb-cat) robin@TNG2019:~/git/arbor/build$ pip show arbor
WARNING: Package(s) not found: arbor
```

**To Reproduce**
1. Presumably it's related to my pyenv setup, so get pyenv
2. Make a virtualenv in pyenv
3. Clone arbor, make build folder inside of it
4. Set the local pyenv version to your virtualenv with `pyenv local arbor-test`
5. `cmake -DARB_WITH_PYTHON=ON -DCMAKE_INSTALL_PREFIX=/home/robin/arbor-master ..`
6. `make install -j`
7. `python -c "import arbor"`

**System (please complete the following information):**
 - OS: Windows Subsystem for Linux running Ubuntu 20.04
 - Arbor 0.5, Conda Python 3.9

**Comment by brenthuisman** [comment]
Which WSL are you using? So far, we've only tested WSL1, with success (even though it's not part of our CI yet).

**Comment by Helveg** [comment]
WSL2

**Comment by brenthuisman** [comment]
The error string occurs exactly once in the pybind codebase:
https://github.com/pybind/pybind11/blob/e57dd4717e3df2a9740addacdb4c1df67d772ef0/include/pybind11/detail/class.h#L70
I guess we made it into the danger zone, I however have no idea how we got there. I'll have to find some time to spool up the ol' Windows machine to check this out. Also, I should resume finding a way to do WSL CI (tips welcome!).

**Comment by Helveg** [comment]
Perhaps ask upstream?

**Comment by noraabiakar** [comment]
@Helveg This error doesn't occur when you pip install arbor?

**Comment by brenthuisman** [comment]
@Helveg Another thing you could try is the binary wheel (scroll down for the artifact): https://github.com/brenthuisman/arbor/actions/runs/596173260
Let me know if either that or `pip install arbor` works.

**Comment by Helveg** [comment]
Side question, why does pip not find the arbor package? Are the arbor bindings simply placed in the site-packages? That is insufficient, I'd like the bindings to be actually pip installed, rather than being just importable.

**Comment by brenthuisman** [comment]
CMake install indeed does no more than copy files into `site-packages`. We have `setup.py` for a pip install. Is that sufficient or is that not what you mean?

**Comment by Helveg** [comment]
@brenthuisman Binary wheels from the build artifact works fine.

@noraabiakar `pip install arbor==0.5` also works fine, iirc that uses cmake under the hood right?

**Comment by Helveg** [comment]
> CMake install indeed does no more than copy files into `site-packages`. We have `setup.py` for a pip install. Is that sufficient or is that not what you mean?

Hmm, do I have the same full features available using `setup.py` as with the CMake approach? I think that in the end all that is missing is the `arbor-*.egg-info` or dist info folder package metadata that pip uses. That should be able to be generated somewhere during the CMake process by `setuptools` or `distutils` or smth tho right?

**Comment by brenthuisman** [comment]
Yep, a pip install runs `setup.py`, which in turn runs the CMake install with a particular configuration.

If that and the binary wheel don't have this problem, you may have configured CMake with another version of Pybind11? Can you give the full config you pass to CMake? In particular, do you `ARB_USE_BUNDLED_LIBS=ON`? If not, your own Pybind11 may be picked up.

**Comment by Helveg** [comment]
> Can you give the full config you pass to CMake?

Uhhhh, step 5? I'm a dummy on this topic but I think that's all the cmake'ing I did.

**Comment by brenthuisman** [comment]
Ah, I saw `...` but I now see I saw incorrectly ;) Try with `-DARB_USE_BUNDLED_LIBS=ON` and let me know if the problem persists. (Do you have Pybind11 elsewhere in your system?)

**Comment by Helveg** [comment]
```
robin@TNG2019:~/git$ apt list python3-pybind11
Listing... Done
python3-pybind11/focal,now 2.4.3-2build2 all [installed]
```

I don't remember precisely but a Cmake error I got instructed me to install that. I'll uninstall and use `-DARB_USE_BUNDLED_LIBS=ON` instead

**Comment by brenthuisman** [comment]
It appears Ubuntu comes with a version of `pybind11` that icompiles and then crashes with Arbor. Probably it is an older version that we haven't tested. As proposed in a separate issue, this should be solved by defaulting ARB_USE_BUNDLED_LIBS to ON.

**Comment by Helveg** [comment]
I did succesfully build Arbor by uninstalling that `-DARB_USE_BUNDLED_LIBS=ON` so this issue is closed. The other actionable points have been taken up in other issues so I think everything here is done :)
