### ISSUE TITLE
modcc: COMMENT and ENDCOMMENT unknown

### ISSUE THREAD

**Issue by w-klijn** [arbor-sim/arbor#14]
When attempting to load a file containing the a COMMENT block modcc throws an error:

./modcc -t cpu -o file.txt generic_neuron_iaf_cell.mod
error: generic_neuron_iaf_cell.mod:(line 3,col 1)

**Comment by w-klijn** [comment]
[generic_neuron_iaf_cell.txt](https://github.com/eth-cscs/nestmc-proto/files/514036/generic_neuron_iaf_cell.txt)

**Comment by bcumming** [comment]
the solution for now is to remove the COMMENT block manually.
