### ISSUE TITLE
`area` in nmodl

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#1400]
Some nmodl mechanisms refer to the `area`: the surface area of a CV. We should investigate is the use of the `area` is necessary in these mechanisms, and expose it to nmodl if it is.

**Comment by halfflat** [comment]
I'm somewhat horrified that compartment area plays a role in mechanism descriptions. Could you add a pointer to one or two examples?

**Comment by noraabiakar** [comment]
The example I have seen was automatically translated from NeuroML and the area ultimately cancels out: 
```
PROCEDURE rates(ica) {
    LOCAL surfaceArea, iCa
    surfaceArea = area 
    iCa = -1 * (0.01) * ica * surfaceArea 
    rate_concentration = (iCa/surfaceArea) *  rho  - ((concentration - restingConc  ) / decayConstant)
}
```
My initial reaction was that it shouldn't be used in a mechanism, but wasn't sure is there were any valid use cases for it.

**Comment by halfflat** [comment]
As a design goal, we are aiming to remove exposure of discretization details, especially at the level of membrane dynamics. Correspondingly, we are not going to expose `area` — even if there is a request for the feature! — unless there really is no alternative design available for the corresponding use case.
