### ISSUE TITLE
Python installation through setup.py improvements

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1405]
* [x] NeuroML should be enabled by default in `setup.py`, as well as any other file formats that may be supported.
  * auditwheel correctly bundles libxml when Arbor is compiled with NeuroML=ON
* ~[ ] modcc should be build and installed. build-catalog eventually as well.~
  * ~https://stackoverflow.com/questions/4840182/setup-py-and-adding-file-to-bin~
  * Outdated
* [x] Should `setup.py` default to ARB_VECTORIZE=ON?
  * This requires AVX
  * After discussion: No.
* [ ] CMake option to install the Python package as user package, and use `python3 -m site --user-site` in such case, overriding any supplied prefix. What we do now [only works by coincidence on the major distros](https://docs.python.org/3/install/index.html#alternate-installation), not by design: there is no such thing as a user-platform-package-dir.

**Comment by halfflat** [comment]
My only concern is how we should handle a missing libxml2 dependency. Should we assume it is ubiquitous? Try it and see?

On the ARB_VECTORIZE front. would turning on vectorization (or setting ARB_ARCH for that matter) interact at all with wheel generation?

**Comment by brenthuisman** [comment]
Once #1399 is merged and we provide these binary wheels, `setup.py` users won't need to have any dependency, and CMake users can be expected to know how to obtain libxml.

It has been a while, but I don't even remember having to obtain it on my distro (Fedora). Maybe it came with `build-essential`/`@development-tools`?

**Comment by brenthuisman** [comment]
Found a new bug when installing the package with OpenSuse.

`python3 -c 'import sysconfig; print(sysconfig.get_path("platlib",vars={"platbase":"~/.local"}))'` returns a directory that Python does not in fact use on OpenSuse systems. It returns `/home/brent/.local/lib/python3.8/site-packages` but uses `/home/brent/.local/lib/python3.8/site-packages`. OpenSuse people insist that the `lib`/`lib64` division was only supposed to exist for system packages, not user packages, and you should not expect the result I am expecting using `sysconfig.get_paths`. `python3 -m site --user-site` does give me the right path, and is what they recommend using. 

I'm adding CMake option to install a user package, in which case we can ignore the prefix in favor of using `site`.

**Comment by brenthuisman** [comment]
See also: https://docs.python.org/3/install/index.html#alternate-installation. It's deep into pedantic territory, but it is by coincidence our current code works on major platforms, not design.
