### ISSUE TITLE
CMake install docs for Python environments

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#1409]
The process for python users who want to compile Arbor and its Python wrapper using CMake, then install the Python package can be surprising if they expect everything to get installed according to their local environment (e.g. in a venv).

This can be fixed by setting the `CMAKE_INSTALL_PREFIX` to the appropriate Python environment path, which will install all of Arbor in the expected location.

Add a note to the installation docs that explains this clearly here: https://arbor.readthedocs.io/en/latest/install/build_install.html#python-frontend

**Comment by thorstenhater** [comment]
Escaped auto-close.
