### ISSUE TITLE
Clean up s_expressions parsing

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#1419]
The region/locset s-expression parsing code currently lives in the arbor library and is being used in our internal implementations (see `region.cpp` and `locset.cpp`).
The cable-cell format parser (#1336) will need to use part of that code, resulting in `s_expr.hpp` becoming part of the public interface and possibly some code duplication. 
I propose that we stop using the string-to-s-expression parsers in the core arbor library, move all of that functionality into arborio, and only allow string-to-s-expression parsing in the python wrapper.

**Comment by thorstenhater** [comment]
- We recently will have added S-Exp for CV policies, so another candidate for clean-up
- The S-Exp parsers share parts of the internal machinery, which should go into an (internal) header
- The exception hierarchy should be unified and cleaned up

I do not think `s_expr.hpp` will need to be public, as it's only used by the implementation.

**Comment by thorstenhater** [comment]
Consensus from our last discussion: S-Exp parsing should be in one place, specifically ``arborio``. 
@bcumming: Does that work for you, too?

**Comment by bcumming** [comment]
I think it makes sense to put it all in one place, to avoid replication, and ArborIO makes sense.
We can hide a lot of the s-expression mechanics in the ArborIO implementation, and not expose them through it's public api.

**Comment by thorstenhater** [comment]
Ok, will add that to #1511.
