### ISSUE TITLE
brunel.py returns zero spikes

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1420]
**Describe the bug**
In PR #1404 (hope it's clear now that it's a draft) I've converted `brunel.cpp` to `brunel.py`. This is meant to show help show how recipes can be designed with cell populations and test implemented but largely untested Python bindings for non cable cells.

It appears a bug or at least issue has been found. Running `brunel.cpp` and `brunel.py` with the same parameters results in ~13k and 0 spikes returned. I've been unable to get a single spike out of `brunel.py` so far.

Here is what I've tested:
* triple check inputs: are all parameters (including lif_cell parameters set identically).
  * Includes a check that `lif_cell_group` is instantiated with the correct cell descriptions.
* Check that `sample_subset` produces vectors/lists of the same length and same sort of contents in both languages.
* Check `connections_on`
* Python's spike recording policy is correctly set to `all`
* Python's `simulation.record()` indeed only ever copies zero length `spikes` into `spike_record_`.
* Check that in `lif_cell_group::advance_cell` event_lane is usually of length 0, occasionally of length 1.
  * This means there are spikes being propagated, right?
* Changing from poisson schedule to a regular schedule of (0,1,100) generates in both cpp and py 0 spikes.

**Additional context**
As I understand it, there is an artificial `event_generator` attached to each lif_cell, and each lif_cell has a threshold voltage parameter `V_th` above which it should fire. The only difference with other cable cell Python examples is that a decor-placed spike_generator is not present; instead we have the `V_th` parameter.

**Comment by noraabiakar** [comment]
Issue was different unit being used in C++ and python version of arbor API.

**Comment by brenthuisman** [comment]
Closed by #1404
