### ISSUE TITLE
AEP: Onboarding new developers: A guided tour of Arbor

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1437]
For users we start to have a good selection of tutorials. For developers however we don't have much in the way of an overview of Arbors internals or design considerations. In the group meeting this week a potential solution was suggested: A guided tour of Arbor.

**Comment by brenthuisman** [comment]
A meager attempt that was unfortunately not merged on account of introducing a dependency involved some diagrams generated by graphviz.

In addition to wanting to use _something_ for a graphical overview of the user facing API, I'll _definitely_ need it for this overview/tour. I chose `graphviz` because it's well supported by Sphinx, and other similar plugins also relied on external tools to actually generate the SVG, with the exception of [pysvg-py3](https://github.com/alorence/pysvg-py3) (doesn't look very good) or [svgling](https://github.com/rawlins/svgling) (does look good, but perhaps a bit too limited, because it seems to be strictly hierarchical). Either way I'm inclined to respectfully ignore these concerns and introduce a new dependency.

**Comment by thorstenhater** [comment]
I cannot remember whether I mentioned that before, but graphviz/dot does not produce graphics in a quality I would want to show to a new user (or anyone in this context). It's fine for automatically generated images, but not here. If we are going to have a tour for onboarding people, we should take the time to make a bespoke graphic.

**Comment by brenthuisman** [comment]
That is an option, but then we need to accept we check in such artifacts and we might need to accept placeholders, because I can't promise print-quality output, but I don't want that to be a reason to hold a PR back. No diagram < graphviz diagram < bespoke diagram.

**Comment by thorstenhater** [comment]
1. We have SVGs already in the repo.
2. Is there a pressing need to have that _now_ instead of having something that is _good_?
3. I would argue bad diagram < no diagram on grounds of confusion.

**Comment by brenthuisman** [comment]
1. True, so I guess a handful here are OK too.
2. I can't map these kinds of things out in text. Just does not compute. And I find them terribly difficult to understand without as well.

**Comment by thorstenhater** [comment]
I do not see how 2. invalidates or addresses my concern. Placeholder graphics are fine for the drafting phase, but the finished product should have appropriately polished graphics. As mentioned earlier today these are the people making our community, so we wannt to make a good impression.

**Comment by brenthuisman** [comment]
After some inperson discussion with @thorstenhater we've agreed that Inkskape-generated svgs are acceptable and most likely to generate sufficiently pretty output, so I'll use that to prototype any diagram that seems helpful in explaining Arbors structure.

**Comment by thorstenhater** [comment]
:+1:
