### ISSUE TITLE
Follow neuromorpho guidelines from soma representations

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#1445]
There is a set of rules for reconstructing soma morphologies from swc and asc files here: http://neuromorpho.org/SomaFormat.html, that describes how to handle somas described with cylinders, countours and single points.

I think that Neuron attempts to follow these rules, however in the past there were issues in at least with how this was performed in practice for SWC files.

Possible action items:

* fix asc file reader to orient the soma along the y axis, not z axis
* look at making the Allen SWC reader follow these conventions.
* revisit the NEURON SWC interpretation, because NEURON's behavior was fixed recently (though I still don't think that the intention of the loader is documented).

**Comment by halfflat** [comment]
I'd also add a link/summary to our documentation, to justify and argue for our interpretations of morphological descriptions.
