### ISSUE TITLE
Add phase to sinusoidal stimulus current specification.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1454]
From a chat with @espenhgn, it looks as though the currently implemented current stimulus is sufficient, with the possible exception of adding an additional phase parameter for the sinusoidal component.

Task is to add this parameter, update tests, docs, etc.

Edit: we're also consistently using kHz for frequencies in other parts of the API now, so we should do so here too. This can be rolled into the same piece of work.

**Comment by espenhgn** [comment]
For future reference; the way I've used sinusoid input current in Arbor was by adding an NMODL file to a now somewhat outdated branch of Arbor: https://github.com/espenhgn/arbor/blob/sinsyn/mechanisms/default/sinsyn.mod 

The mod file is used in a simple simulation here: https://github.com/LFPy/LFPykit/blob/master/examples/Example_Arbor.ipynb

A somewhat odd choice incorporated in that .mod file however is shifting the time `t` by the onset delay `del`. Seems redundant as the phase was set as free parameter already.

**Comment by halfflat** [comment]
I am only guessing that they were aiming to have the phase parameter correspond to the phase at the onset time. I probably will not implement it that way in Arbor though, because it makes less sense with a more general amplitude envelope.
