### ISSUE TITLE
Allow reading from Buffer Object in PyArborio

### ISSUE THREAD

**Issue by thorstenhater** [arbor-sim/arbor#1459]
Currently we have interfaces in ArborIO's Python wrapper that allows reading from a file like this
```Python
morph = arborio.load_XYZ('filename')
```
The more pythonic version is to read from a buffer/file descriptor-like object, which has a tiny bit
of boilerplate, but is more flexible
```Python
# read from file
with open('filename') as fd:
    morph = arborio.load_XYZ(fd)
# read from somewhere
my_string = foo() # HTTP? Redis?
morph = arborio.load_XYZ(StringIO(my_string))
```

**Comment by Helveg** [comment]
Most Pythonic is to allow both :)
