### ISSUE TITLE
maintain spack config in master

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#1465]
Add the spack `package.py` file for Arbor to the repository for two reasons:

* keep the package information up to date, so that we have a working up-to-date package description on hand to push to the main spack repository when we tag a release
* to test the spack config as part of CI.

https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/arbor/package.py

**Comment by schmitts** [comment]
Just a heads up. At some point we may need to decide if we want to be compatible against the develop or the main branch of spack.

**Comment by bcumming** [comment]
To the best of my knowledge `develop` is the main branch of spack (they don't have a `master` or `main` branch).
The tagged releases are tags off the `develop` branch.
