### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [arbor-sim/arbor#1473]
(base) [jw@cn06 build]$ make VERBOSE=1 -j1
/usr/bin/cmake -S/data/jw/arbor -B/data/jw/arbor/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /data/jw/arbor/build/CMakeFiles /data/jw/arbor/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/data/jw/arbor/build'
make  -f modcc/CMakeFiles/libmodcc.dir/build.make modcc/CMakeFiles/libmodcc.dir/depend
make[2]: Entering directory '/data/jw/arbor/build'
cd /data/jw/arbor/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/arbor /data/jw/arbor/modcc /data/jw/arbor/build /data/jw/arbor/build/modcc /data/jw/arbor/build/modcc/CMakeFiles/libmodcc.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/arbor/build'
make  -f modcc/CMakeFiles/libmodcc.dir/build.make modcc/CMakeFiles/libmodcc.dir/build
make[2]: Entering directory '/data/jw/arbor/build'
make[2]: Nothing to be done for 'modcc/CMakeFiles/libmodcc.dir/build'.
make[2]: Leaving directory '/data/jw/arbor/build'
[ 12%] Built target libmodcc
make  -f modcc/CMakeFiles/modcc.dir/build.make modcc/CMakeFiles/modcc.dir/depend
make[2]: Entering directory '/data/jw/arbor/build'
cd /data/jw/arbor/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/arbor /data/jw/arbor/modcc /data/jw/arbor/build /data/jw/arbor/build/modcc /data/jw/arbor/build/modcc/CMakeFiles/modcc.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/arbor/build'
make  -f modcc/CMakeFiles/modcc.dir/build.make modcc/CMakeFiles/modcc.dir/build
make[2]: Entering directory '/data/jw/arbor/build'
make[2]: Nothing to be done for 'modcc/CMakeFiles/modcc.dir/build'.
make[2]: Leaving directory '/data/jw/arbor/build'
[ 14%] Built target modcc
make  -f mechanisms/CMakeFiles/bbp_catalogue_cpp_target.dir/build.make mechanisms/CMakeFiles/bbp_catalogue_cpp_target.dir/depend
make[2]: Entering directory '/data/jw/arbor/build'
cd /data/jw/arbor/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/arbor /data/jw/arbor/mechanisms /data/jw/arbor/build /data/jw/arbor/build/mechanisms /data/jw/arbor/build/mechanisms/CMakeFiles/bbp_catalogue_cpp_target.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/arbor/build'
make  -f mechanisms/CMakeFiles/bbp_catalogue_cpp_target.dir/build.make mechanisms/CMakeFiles/bbp_catalogue_cpp_target.dir/build
make[2]: Entering directory '/data/jw/arbor/build'
make[2]: Nothing to be done for 'mechanisms/CMakeFiles/bbp_catalogue_cpp_target.dir/build'.
make[2]: Leaving directory '/data/jw/arbor/build'
[ 14%] Built target bbp_catalogue_cpp_target
make  -f mechanisms/CMakeFiles/build_catalogue_bbp_mods.dir/build.make mechanisms/CMakeFiles/build_catalogue_bbp_mods.dir/depend
make[2]: Entering directory '/data/jw/arbor/build'
cd /data/jw/arbor/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/arbor /data/jw/arbor/mechanisms /data/jw/arbor/build /data/jw/arbor/build/mechanisms /data/jw/arbor/build/mechanisms/CMakeFiles/build_catalogue_bbp_mods.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/arbor/build'
make  -f mechanisms/CMakeFiles/build_catalogue_bbp_mods.dir/build.make mechanisms/CMakeFiles/build_catalogue_bbp_mods.dir/build
make[2]: Entering directory '/data/jw/arbor/build'
make[2]: Nothing to be done for 'mechanisms/CMakeFiles/build_catalogue_bbp_mods.dir/build'.
make[2]: Leaving directory '/data/jw/arbor/build'
[ 21%] Built target build_catalogue_bbp_mods
make  -f mechanisms/CMakeFiles/default_catalogue_cpp_target.dir/build.make mechanisms/CMakeFiles/default_catalogue_cpp_target.dir/depend
make[2]: Entering directory '/data/jw/arbor/build'
cd /data/jw/arbor/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/arbor /data/jw/arbor/mechanisms /data/jw/arbor/build /data/jw/arbor/build/mechanisms /data/jw/arbor/build/mechanisms/CMakeFiles/default_catalogue_cpp_target.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/arbor/build'
make  -f mechanisms/CMakeFiles/default_catalogue_cpp_target.dir/build.make mechanisms/CMakeFiles/default_catalogue_cpp_target.dir/build
make[2]: Entering directory '/data/jw/arbor/build'
make[2]: Nothing to be done for 'mechanisms/CMakeFiles/default_catalogue_cpp_target.dir/build'.
make[2]: Leaving directory '/data/jw/arbor/build'
[ 21%] Built target default_catalogue_cpp_target
make  -f mechanisms/CMakeFiles/build_catalogue_default_mods.dir/build.make mechanisms/CMakeFiles/build_catalogue_default_mods.dir/depend
make[2]: Entering directory '/data/jw/arbor/build'
cd /data/jw/arbor/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/arbor /data/jw/arbor/mechanisms /data/jw/arbor/build /data/jw/arbor/build/mechanisms /data/jw/arbor/build/mechanisms/CMakeFiles/build_catalogue_default_mods.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/arbor/build'
make  -f mechanisms/CMakeFiles/build_catalogue_default_mods.dir/build.make mechanisms/CMakeFiles/build_catalogue_default_mods.dir/build
make[2]: Entering directory '/data/jw/arbor/build'
make[2]: Nothing to be done for 'mechanisms/CMakeFiles/build_catalogue_default_mods.dir/build'.
make[2]: Leaving directory '/data/jw/arbor/build'
[ 26%] Built target build_catalogue_default_mods
make  -f mechanisms/CMakeFiles/allen_catalogue_cpp_target.dir/build.make mechanisms/CMakeFiles/allen_catalogue_cpp_target.dir/depend
make[2]: Entering directory '/data/jw/arbor/build'
cd /data/jw/arbor/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/arbor /data/jw/arbor/mechanisms /data/jw/arbor/build /data/jw/arbor/build/mechanisms /data/jw/arbor/build/mechanisms/CMakeFiles/allen_catalogue_cpp_target.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/arbor/build'
make  -f mechanisms/CMakeFiles/allen_catalogue_cpp_target.dir/build.make mechanisms/CMakeFiles/allen_catalogue_cpp_target.dir/build
make[2]: Entering directory '/data/jw/arbor/build'
make[2]: Nothing to be done for 'mechanisms/CMakeFiles/allen_catalogue_cpp_target.dir/build'.
make[2]: Leaving directory '/data/jw/arbor/build'
[ 26%] Built target allen_catalogue_cpp_target
make  -f mechanisms/CMakeFiles/build_catalogue_allen_mods.dir/build.make mechanisms/CMakeFiles/build_catalogue_allen_mods.dir/depend
make[2]: Entering directory '/data/jw/arbor/build'
cd /data/jw/arbor/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/arbor /data/jw/arbor/mechanisms /data/jw/arbor/build /data/jw/arbor/build/mechanisms /data/jw/arbor/build/mechanisms/CMakeFiles/build_catalogue_allen_mods.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/arbor/build'
make  -f mechanisms/CMakeFiles/build_catalogue_allen_mods.dir/build.make mechanisms/CMakeFiles/build_catalogue_allen_mods.dir/build
make[2]: Entering directory '/data/jw/arbor/build'
make[2]: Nothing to be done for 'mechanisms/CMakeFiles/build_catalogue_allen_mods.dir/build'.
make[2]: Leaving directory '/data/jw/arbor/build'
[ 36%] Built target build_catalogue_allen_mods
make  -f mechanisms/CMakeFiles/build_all_mods.dir/build.make mechanisms/CMakeFiles/build_all_mods.dir/depend
make[2]: Entering directory '/data/jw/arbor/build'
cd /data/jw/arbor/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/arbor /data/jw/arbor/mechanisms /data/jw/arbor/build /data/jw/arbor/build/mechanisms /data/jw/arbor/build/mechanisms/CMakeFiles/build_all_mods.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/arbor/build'
make  -f mechanisms/CMakeFiles/build_all_mods.dir/build.make mechanisms/CMakeFiles/build_all_mods.dir/build
make[2]: Entering directory '/data/jw/arbor/build'
make[2]: Nothing to be done for 'mechanisms/CMakeFiles/build_all_mods.dir/build'.
make[2]: Leaving directory '/data/jw/arbor/build'
[ 36%] Built target build_all_mods
make  -f arbor/include/CMakeFiles/generate_version_hpp.dir/build.make arbor/include/CMakeFiles/generate_version_hpp.dir/depend
make[2]: Entering directory '/data/jw/arbor/build'
cd /data/jw/arbor/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/arbor /data/jw/arbor/arbor/include /data/jw/arbor/build /data/jw/arbor/build/arbor/include /data/jw/arbor/build/arbor/include/CMakeFiles/generate_version_hpp.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/arbor/build'
make  -f arbor/include/CMakeFiles/generate_version_hpp.dir/build.make arbor/include/CMakeFiles/generate_version_hpp.dir/build
make[2]: Entering directory '/data/jw/arbor/build'
[ 36%] Generating _always_rebuild
cd /data/jw/arbor/build/arbor/include && true
[ 36%] Generating version.hpp-test
cd /data/jw/arbor/build/arbor/include && ../../../arbor/include/git-source-id 0.5.1-dev native RELEASE > version.hpp-test
[ 36%] Generating arbor/version.hpp
cd /data/jw/arbor/build/arbor/include && /usr/bin/cmake -E copy_if_different version.hpp-test arbor/version.hpp
make[2]: Leaving directory '/data/jw/arbor/build'
[ 36%] Built target generate_version_hpp
make  -f arbor/CMakeFiles/arbor.dir/build.make arbor/CMakeFiles/arbor.dir/depend
make[2]: Entering directory '/data/jw/arbor/build'
cd /data/jw/arbor/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/arbor /data/jw/arbor/arbor /data/jw/arbor/build /data/jw/arbor/build/arbor /data/jw/arbor/build/arbor/CMakeFiles/arbor.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/arbor/build'
make  -f arbor/CMakeFiles/arbor.dir/build.make arbor/CMakeFiles/arbor.dir/build
make[2]: Entering directory '/data/jw/arbor/build'
make[2]: Nothing to be done for 'arbor/CMakeFiles/arbor.dir/build'.
make[2]: Leaving directory '/data/jw/arbor/build'
[ 92%] Built target arbor
make  -f sup/CMakeFiles/arbor-sup.dir/build.make sup/CMakeFiles/arbor-sup.dir/depend
make[2]: Entering directory '/data/jw/arbor/build'
cd /data/jw/arbor/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/arbor /data/jw/arbor/sup /data/jw/arbor/build /data/jw/arbor/build/sup /data/jw/arbor/build/sup/CMakeFiles/arbor-sup.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/arbor/build'
make  -f sup/CMakeFiles/arbor-sup.dir/build.make sup/CMakeFiles/arbor-sup.dir/build
make[2]: Entering directory '/data/jw/arbor/build'
[ 92%] Building CXX object sup/CMakeFiles/arbor-sup.dir/json_meter.cpp.o
cd /data/jw/arbor/build/sup && /usr/bin/c++  -I/data/jw/arbor/sup/include -I/data/jw/arbor/arbor/include -I/data/jw/arbor/build/arbor/include -O2 -DNDEBUG -Wall -Wno-maybe-uninitialized -march=native -std=c++17 -o CMakeFiles/arbor-sup.dir/json_meter.cpp.o -c /data/jw/arbor/sup/json_meter.cpp
/data/jw/arbor/sup/json_meter.cpp:2:10: fatal error: nlohmann/json.hpp: No such file or directory
    2 | #include <nlohmann/json.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [sup/CMakeFiles/arbor-sup.dir/build.make:95: sup/CMakeFiles/arbor-sup.dir/json_meter.cpp.o] Error 1
make[2]: Leaving directory '/data/jw/arbor/build'
make[1]: *** [CMakeFiles/Makefile2:667: sup/CMakeFiles/arbor-sup.dir/all] Error 2
make[1]: Leaving directory '/data/jw/arbor/build'
make: *** [Makefile:149: all] Error 2
(base) [jw@cn06 build]$ 

Installing "nlohmann/json" via conda did not help.

**Comment by halfflat** [comment]
If it isn't already configured this way, could you try reconfiguring and rebuilding the project with the `-DARB_USE_BUNDLED_LIBS=ON` flag added to the invocation of cmake?

**Comment by bcumming** [comment]
@LutzWeischerFujitsu, can you pleae provide the command used to configure CMake?

Arbor bundles the pybind11 and nlohmann/json dependencies as git submodules, so if you have done a recursive git clone, you can enable using these with the `-DARB_USE_BUNDLED_LIBS=on` option that @halflat mentions.

For reference:

https://arbor.readthedocs.io/en/latest/install/build_install.html#building-and-installing-arbor

**Comment by LutzWeischerFujitsu** [comment]
:-)

**Comment by brenthuisman** [comment]
@LutzWeischerFujitsu Can I consider your build issue solved?

(I'm also a Fedora user, so rest assured any build issues won't go undetected for long :wink: )

**Comment by LutzWeischerFujitsu** [comment]
Yes. Thanks. Nice to have seen SVE mentioned in the build log.

**Comment by brenthuisman** [comment]
By the way, we don't run our unit tests on AArch64. Would be nice if you could let us know if they all pass, we don't have the hardware currently to run them.

**Comment by LutzWeischerFujitsu** [comment]
Yes, done on an A64FX. Tried manual build, including test, as well as using setup.py.

**Comment by brenthuisman** [comment]
Excellent, that's great to know, thanks for reporting back!

Let us know of any other issues you discover.

**Comment by bcumming** [comment]
@LutzWeischerFujitsu, Arbor has support for SVE intrinsics, whereby SVE intrinsics are generated for the computational kernels.

To enable them requires two CMake flags be set: `-DARB_VECTORIZE=on -DARB_ARCH=armv8.2-a+sve`. If you are compiling on a node with A64FX the second argument might not be required, because the default `native` architecture should pick up the A64FX architecture.

You inspired us to check, and we fixed a small issue with our SVE backend in #1477 .

**Comment by LutzWeischerFujitsu** [comment]
I tried again with new git clone and this time 'cmake -DARB_ARCH=native -DARB_VECTORIZE=ON -DARB_WITH_PYTHON=ON -DARB_USE_BUNDLED_LIBS=ON ..': 

...
In file included from /data/jw/arbor/arbor/backends/multicore/shared_state.hpp:13,
                 from /data/jw/arbor/arbor/backends/multicore/fvm.hpp:12,
                 from /data/jw/arbor/arbor/backends/multicore/mechanism.hpp:15,
                 from /data/jw/arbor/build/mechanisms/generated/allen/NaV_cpu.cpp:5:
/data/jw/arbor/arbor/include/arbor/simd/simd.hpp:40:6: note: candidate: 'template<class Impl, class Other> void arb::simd::assign(arb::simd::detail::simd_impl<Impl>&, const Other&)'
   40 | void assign(detail::simd_impl<Impl>& a, const Other& b) {
      |      ^~~~~~
/data/jw/arbor/arbor/include/arbor/simd/simd.hpp:40:6: note:   template argument deduction/substitution failed:
/data/jw/arbor/build/mechanisms/generated/allen/NaV_cpu.cpp:6487:160: note:   mismatched types 'arb::simd::detail::simd_impl<Impl>' and 'arb::allen_catalogue::simd_value' {aka 'svfloat64_t'}
 6487 |         assign(conductivity_, S::mul(simd_cast<simd_value>(indirect(pp->gbar+index_, simd_width_)), simd_cast<simd_value>(indirect(pp->O+index_, simd_width_))));
      |                                                                                                                                                                ^
...

**Comment by noraabiakar** [comment]
The bug fix was just merged, so the error should be fixed now.

**Comment by LutzWeischerFujitsu** [comment]
Yes. :-)
