### ISSUE TITLE
Add epoch end time to spike callbacks

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1480]
Motivation is the exposure of spike information through the In-situ pipeline project:
* A spike callback is set up to take locally generated spikes, and present them via a reporting interface.
* A front-end communicates with the per-node spike collectors to present answers to queries for spikes across the simulation.

One node in the Arbor simulation might, over the course of an epoch, not generate any spikes at all. Without any other information or synchronization, the front-end cannot differentiate between that node having no spikes for a time interval, and that node not yet having finished making those spikes available to the reporter.

Proposed solution:
* Local and global spike callbacks also include the end-of-epoch time, that is, they also provide a time _t_ with a guarantee that there will be no more spikes reported with spike time less than _t_ unless the simulation is reset.

Open question:
* How to report that a simulation is reset and restarted?

**Comment by thorstenhater** [comment]
Hi @halfflat,

the coupling framework has been completely revamped so I am going to close this as obsolete.
