### ISSUE TITLE
Cable cell probing and sampling

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1484]
After closing #1353, we did not make a new ticket to track having "Cable cell probing and sampling" pages across concepts/API. This page should describe experimental/artificial in and outputs.

### Status
* Concepts is blank
* C++ has more than Python API, including schedules, which are on Python's Recipe page
* Should "Event generator and schedules" be on this page?
* A new example?

**Comment by thorstenhater** [comment]
done by PR #1898
