### ISSUE TITLE
Allow synapse mechanism to restrict number of incoming connections

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#1487]
Multiple connections to the same synapse are allowed and correct if the dynamics of the mechanism are linear. However, for synapse mechanisms that are not, subtle bugs may occur if multiple connections are instantiated. This could be avoided if the mechanism could announce the allowed number of multiple connections (or a flag: zero or one, exactly one, or any number).

**Comment by noraabiakar** [comment]
I think this has been solved by #1504

**Comment by schmitts** [comment]
Not really. Maybe @halfflat can explain the original problem in different words.

**Comment by thorstenhater** [comment]
@schmitts @halfflat Any updates?
