### ISSUE TITLE
Repurpose sup/path.hpp for Mac OS 10.14 std::filesystem workaround

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1507]
Motivation: using `std::filesystem::path` in interface expected a path both indicates through the type the expected semantics of the argument, and also allows a common interface in the future across non-POSIXy platforms such as Windows, where `std::string` is insufficient for capturing all valid paths.

We already have a partial work-alike for `std::filesystem::path` in `sup/`, which was used in the now removed glob code.

Proposal:
* We move the current path work-alike into `arbor/compat/path.hpp`, namespacing as appropriate.
* The CMake tests for the presence of `std::filesystem` are restored. They are then used to provide a preprocessor define used by `compat/path.hpp`: if we have `std::filesystem` , we alias `arb::compat::path` to `std::filesystem::path`, else to our own implementation.
* We use `arb::compat:path` in all our path interfaces, and document that this will be an alias for `std::filesystem::path` on all platforms where we were able to find it.

Open question:
* Python interfaces: should we be interpreting path arguments as 'path-like' objects? If I understand how things work correctly post PEP 529, on Windows we will always see utf-8 encoded data in any `bytes` objects that we get from e.g. `__fspath__()`; we can continue to assert that any string that Arbor sees, even from Python path representations, is in UTF-8, and build `std::filesystem::path` objects accordingly.

For the C++ arborio APIs, we could stick to parsing data that is already read into a (UTF-8 encoded) `string` or `string_view` — nothing we're parsing, I think, should be expected to be so large compared to its parsed representation that we have to worry about the memory. This sidesteps any problems of platform-specific IO.

**Comment by thorstenhater** [comment]
Hi, 

I am closing this, 10.14 will drop from support rather sooner than later and we can live with the status quo, as we have learned from the last year.
