### ISSUE TITLE
Modcc: Incorrect handling of written ion concentration parameters

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#1528]
A comparison of the behavior of arbor and neuron on a mechanism with `USEION ca WRITE cai`: `cai` is a `STATE` variable, an `ASSIGNED` variable, or neither; `cai` is integrated in a `DERIVATIVE` block, or assigned to a value in a `BREAKPOINT` block.
- Arbor: 
    - `cai` is a `STATE` variable: 
        - `cai` is integrated: The internal concentration of `ca` is accumulated in `write_ions`.
        - `cai` is assigned to a value:  a range variable is assigned to the value, and the range variable is then accumulated to the internal concentration of `ca`  in `write_ions`.
    - `cai` is an `ASSIGNED`  variable: 
        - `cai` is integrated: `ERROR`: `cai` must be a `STATE` variable to be integrated.
        - `cai` is assigned to a value: `ERROR`: `cai` can't be redeclared (in `ASSIGNED`).
    - `cai` is neither a `STATE` nor `ASSIGNED` variable:
        - `cai` is integrated: `ERROR`: `cai`  must be a `STATE` variable to be integrated.
        - `cai` is assigned to a value: The  concentration of `ca` is accumulated by that value immediately during mechanism init and/or update current. 

- Neuron: 
    - `cai` is a `STATE` variable: 
        - `cai` is integrated: The internal concentration of `ca` is accumulated in `nrn_state`. (Similar to arbor).
        - `cai` is assigned to a value: The internal concentration of `ca` is assigned to a value in `nrn_state`. (Different behavior than arbor)
    - `cai` is an `ASSIGNED` variable: 
        - `cai` is integrated: `ERROR`: `cai`  must be a `STATE` variable to be integrated. (Similar to arbor).
        - `cai` is assigned to a value:  The internal concentration of `ca` is assigned to a value in `nrn_state`. (Different behavior than arbor)
    - `cai` is neither a `STATE` nor `ASSIGNED` variable:
        - `cai` is integrated: `ERROR`: `cai` must be a STATE variable to be integrated. (Similar to arbor).
        - `cai` is assigned to a value: `ERROR`: `cai` not declared. (Different behavior than arbor).
        
Arbor handles direct assignments to ion concentrations differently from Neuron's method, which is the more correct of the two. 
We should either not allow direct assignments, or handle them similar to Neuron. (However, we don't necessarily need to abide by the `ASSIGNED`/neither `ASSIGNED` nor `STATE` distinction).

**Comment by halfflat** [comment]
The accumulation part is only to cover the case where an ion-writing mechanism only partially covers a CV; this is a situation NEURON does not have to deal with, so the case when `cai` is a `STATE` variable is essentially equivalent.

I think the only substantial difference is in the interpretation of `ASSIGNED` which, to be honest, has been somewhat idiosyncratic in `modcc` across the board, and perhaps should be revisited in a broader context.

**Comment by noraabiakar** [comment]
Okay, I had misunderstood why the accumulation is needed. Thanks for the clarification!

I'm closing the issue. I don't think the misinterpretation of the `ASSIGNED` block is worth fixing at the moment, and it's in the documentation that ion variables shouldn't be in the `ASSIGNED` block.

**Comment by noraabiakar** [comment]
I will just add one more note on the behavior of Arbor in the cases: 
1. `cai` is a `STATE` variable and it is assigned to a value. 
2. `cai is not a `STATE`  variable but it is assigned to a value.
The generated code is different: case (1) will update the internal concentration in `write_ions`, while case (2) will update it in init/update_current. But the result should be the same: this is because `write_ions` is performed after both init and current/state updates. So, (in a sane model where ion interactions make sense), whether or not `cai` is a `STATE` variable shouldn't matter.
