### ISSUE TITLE
Add CI for Arbor's Spack package

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#1534]
Arbor's Spack package https://github.com/arbor-sim/arbor/blob/master/spack/package.py needs CI to ensure that it is ready to be PRed to upstream Spack with every release of Arbor. A github action that pulls Spack develop branch, updates the Arbor package and performs a build (`spack dev-build`) is probably sufficient.

**Comment by bcumming** [comment]
Do we want to target the `develop` branch and the latest tagged release (https://github.com/spack/spack/releases/tag/releases%2Flatest) of spack, using the spack `package.py` in Arbor?

**Comment by schmitts** [comment]
Typically `develop` is in a usable state and would suffice. If we aren't short in CI resources, we can do the latest release of Spack in addition.

**Comment by schmitts** [comment]
https://spack.readthedocs.io/en/latest/repositories.html#overriding-built-in-packages

and

https://spack-tutorial.readthedocs.io/en/lanl19/tutorial_developer_workflows.html#development-iteration-cycles

will be helpful.

**Comment by schmitts** [comment]
parsing `march` is not enough as some targets use `mcpu`, cf. https://github.com/arbor-sim/arbor/blob/master/cmake/CompilerOptions.cmake#L115 @bcumming and @halfflat are working on an alternative to pass in user defined optimization falgs.
