### ISSUE TITLE
`catalogue` iteration and the 'MechCatIterator`

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1547]
While using the catalogues there are some UX issues due to the limited available information on the `catalogue` and `mechanism_info` objects:

The way to iterate over a catalogue feels incomplete. It is iterable, which is good (so `iter(cat)` works), but as a dictionary style object it is strange that the `values`, `keys` and `items` iterators are unavailable. The obtained `MechCatIterator` is also a very strange object AND attribute? Why is it available as an attribute of a `catalogue`? As an attribute it is completely unusable from Python:

```python
>>> cat.MechCatIterator
<class 'arbor._arbor.catalogue.MechCatIterator'>
>>> list(cat.MechCatIterator)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'pybind11_type' object is not iterable
>>> list(iter(cat.MechCatIterator))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'pybind11_type' object is not iterable
>>> next(cat.MechCatIterator)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'pybind11_type' object is not an iterator
>>> cat.MechCatIterator.__iter__
<instancemethod __iter__ at 0x7f9b6e45a160>
>>> cat.MechCatIterator.__iter__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __iter__(): incompatible function arguments. The following argument types are supported:
    1. (self: arbor._arbor.catalogue.MechCatIterator) -> arbor._arbor.catalogue.MechCatIterator

Invoked with:
>>> iter(cat.MechCatIterator)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'pybind11_type' object is not iterable
>>> iter(cat.MechCatIterator())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: arbor._arbor.MechCatIterator: No constructor defined!
```

It would be nicer if this `MechCatIterator` was not available in the `__dict__` of a `catalogue` or was at least prefixed with an underscore if absolutely required.

**Comment by thorstenhater** [comment]
I agree, this is awkward on multiple fronts. We can expose `values`, `items`, and `keys` quite easily, and should do so, to be a better python citizen. 

`MechCatIterator` however is a different story. We need this construction to hold onto a python reference until iteration is done. Assume iteration is started and the original catalogue is garbage collected (might happen if the catalogue is a temporary). Then the iterator holds a dangling C++ reference to the catalogue, which results in catastrophe. So, the iterator needs to bump the python reference count. I can try to move it from the `MechCat` class to the module and 'hide' it.

**Comment by thorstenhater** [comment]
Good news: MechCatIterator is now attached to the module instead of class.
Bad news: Now there's three of them `MechCat{Key|Value|Item}Iterator`.
