### ISSUE TITLE
`catalogue` and `mechanism_info` inspection

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1548]
The `catalogue` object has just 4 public attributes: `derive`, `extend`, `is_derived` and `MechIterator`. None of these help inspect a catalogue or its contents in a structural way, while a catalogue contains different categories of mechanisms. Some convenience functions to list all the mechanisms, all the density mechanisms or all the point mechanisms would be nice.

On to the `mechanism_info`, it contains all the NMODL attributes like `ions`, `globals`, ... but it does not contain:

* Its own name
* Whether it is derived or not (maybe we're supposed to do that through the catalogue's `is_derived` function?)
  * Its base mech if it is derived
  * How it deviates from what it is derived
* Its catalogue
* A function to derive a new mechanism from this one

**Comment by thorstenhater** [comment]
Hey, this has been partially explored before, here are some points from that discussion
- A mechanism can be in multiple catalogues, ...
- ... under different names.
- The name in the catalogue might not be the same as the NMODL SUFFIX. If that is what you are looking for, it can be easily added.


MechCatIterator will be gone soon via #1564.

**Comment by Helveg** [comment]
Instead of all of the catalogues or all of the names, but maybe just the catalogue and name that was used to construct the instance, could that be a solution?

**Comment by thorstenhater** [comment]
The point was that neither the name of the mechanism nor that of the catalogue hold any meaning.
For what functionality do you need this?

**Comment by Helveg** [comment]
I don't remember 🤷
