### ISSUE TITLE
s-expression parser should accept both `"` and `'`

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1549]
I'm a PEP8 guy, I don't want to mix `"` and `'` characters around my strings, also my automatic formatter will change them back to `"` and escape the `"` inside the strings, hella ugly. Could the s-expression parser accept both `"` and `'` instead of only `"`?

```
>>> arbor.label_dict({"x": "(tag 1)", "y": "'x'"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError:
----- internal error -------------------------------------------
Error parsing the label: 'y' = ''x''

error in label description at 1:1: Unexpected character '''..

Please file a bug report with this full error message at:
    github.com/arbor-sim/arbor/issues
----------------------------------------------------------------
```

**Comment by Helveg** [comment]
Small pile on:

```
>>> arbor.label_dict({"x": "(tag 1)", "y": '"x"'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError:
Error adding the label 'y' = '"x"'
The defninition of 'y = "x"' does not define a valid region or locset.
```

> defninition

And why is it not valid to create an alias?

**Comment by bcumming** [comment]
**Linting**

The DSL defines strings as quoted with `""`, i.e. `(region "axon")` is valid, and `(region 'axon')` isn't. This is based on how s-expressions are typically defined. Adding support for `'` as well as `"` would require modifying the underlying DSL to have two ways to express the same thing, which I am not so fond of doing to make representation in one language a bit easier.

**Aliases**

When a label is defined, it is given a name and a definition. The definition is inspected to determine if it is a region or a locset, so it can be stored appropriately in the dictionary. In the example you give, the label is `"y"` and the definition is `"x"`, which is a string, and it isn't possible to determine if it is a region or a locset.

Additionally, it helps to be able to read a definition and understand what it is without other context. So, reading `(region "x")`  makes it clear that we are referring to a region labelled `"x"`. It might be a bit more annoying to type the long hand, but we hope it reduces errors and makes the intent of the programmer/model builder clearer.
