### ISSUE TITLE
Very large resistivity needed to mimic an insulator

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#1552]
A (very?) large resistivity is needed to mimic an insulator. Not sure if really a bug. Comparison with some other simulator or solving the math by hand needed.
[arbor_insulator.py.gz](https://github.com/arbor-sim/arbor/files/6546954/arbor_insulator.py.gz)
![arbor_insulator](https://user-images.githubusercontent.com/1502412/119666553-c30ec000-be35-11eb-9e11-0db969391d94.png)

**Comment by thorstenhater** [comment]
Hi @schmitts,

do you have an idea whether this is a bug, a missing feature, and how others in the field handle this?
Where would an insulator need to be modelled?

**Comment by schmitts** [comment]
@thorstenhater a comparison with some other simulator would be necessary. I'll try to put it together.

**Comment by thorstenhater** [comment]
Hi @schmitts,

any news here? Just a thought: Wouldn't an insulator imply your are actually looking at two
cells? Or at least a different morphology, where the insulating segment is simply removed.
For the latter, we recently added some editing capabilities.

**Comment by schmitts** [comment]
To debug these sorts of things, it would be really good to be able to query the total quantitites (capacity, axial resistance) per and between segments. We've discussed this with @halfflat in the chat, cf. https://gitter.im/arbor-sim/community?at=62907770da83520ac34f5e89.

**Comment by thorstenhater** [comment]
As discussed, insulators are either huge resistivities or simply non-existent in the morphology.
