### ISSUE TITLE
`RuntimeError: Error parsing the label: ` in python functions and example files 

### ISSUE THREAD

**Issue by espenhgn** [arbor-sim/arbor#1557]
**Describe the bug**
Python examples are using seemingly deprecated location label syntax, for instance:
```
% cd <arbor>/python/example
% python single_cell_detailed_recipe.py single_cell_detailed.swc
Traceback (most recent call last):
  File "/Users/espenhagen/Repositories/arbor/python/example/single_cell_detailed_recipe.py", line 29, in <module>
    labels['soma'] = '(tag 1)'
RuntimeError: 
----- internal error -------------------------------------------
Error parsing the label: 'soma' = '(tag 1)'

bad any cast

Please file a bug report with this full error message at:
    github.com/arbor-sim/arbor/issues
----------------------------------------------------------------
```

Several such cases may also be present as defaults in arbor itself, for example: 
```
>>> help(arbor.cv_policy_single)

Help on built-in function cv_policy_single in module arbor._arbor:

cv_policy_single(...) method of builtins.PyCapsule instance
    cv_policy_single(domain: str = '(all)') -> arbor._arbor.cv_policy
```
hence
```
>>> arbor.cv_policy_single()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Invalid region description: '(all)' is neither a valid region expression or region label string.
```

**Additional context**
conda env/installation:
```
conda create -n arbor2 python=3.9 pip numpy pandas seaborn cmake c-compiler cxx-compiler nlohmann_json sphinx svgwrite -c conda-forge -y
conda activate arbor2
cd <arbor>
git checkout a304d5ac7
pip install -v .
... 
% python -c "import arbor; print(arbor.__version__, arbor.__file__)"
0.5.1-dev /Users/espenhagen/miniforge3/envs/arbor2/lib/python3.9/site-packages/arbor/__init__.py # seems correct
```

**Comment by schmitts** [comment]
I'm trying to reproduce your conda installation. Are you sure it's what you've done 1:1? `conda activate arbor2` would need to be `conda activate python=3.9`. Also without `git submodule init && git submodule update` installation fails for me (can't find pybind11).

With these changes `python single_cell_detailed_recipe.py single_cell_detailed.swc` works.

**Comment by espenhgn** [comment]
Sorry, it should've been `conda create -n arbor2 python=3.9 pip ...` above. I didn't do a fresh clone of the arbor repo hence the submodules were already in place in my case.

I made a clean clone of arbor into another destination; checked out revision a304d5ac7; initialized and updated the submodules and trashed/rebuilt the conda environment and still see the same error. 

Additional conda info:
```

**Comment by schmitts** [comment]
I'm still suspecting and environment issue. Can you please - in a fresh shell - do the following?

```console
conda env remove -v --name arbor2
conda create -n arbor2 python=3.9 pip numpy pandas seaborn cmake c-compiler cxx-compiler nlohmann_json sphinx svgwrite -c conda-forge -y
conda activate arbor2
git clone https://github.com/arbor-sim/arbor
cd arbor
git submodule init
git submodule update
pip install -v .
cd python/example
python single_cell_detailed_recipe.py single_cell_detailed.swc
```

**Comment by espenhgn** [comment]
That still doesn't work; I even went through the trouble of creating a new user, installed miniforge and arbor locally. The examples still fail. The issue seems to arise on my M1 (arm64) mac, only. I had no issues testing the current master on an older mac w. Intel hardware, as well as on an Ubuntu VM. 

To me it appears as though something subtle got introduced in the last month or so causing this issue, as per 93faa63281961333120b3288c8cf8a7b27d6d0ac everything worked fine. Perhaps someone with an M1 mac can verify?

**Comment by espenhgn** [comment]
On my end 595e4e3a (#1505) works, e8b08ca8 (#1510) and newer is broken. Reverting e8b08ca8 onto the current master (https://github.com/arbor-sim/arbor/commit/a304d5ac74b9fa1db4c0b0f48f05e81f77b54e09) works.

**Comment by schmitts** [comment]
Thanks for your efforts! I'll escalate your issue.
