### ISSUE TITLE
Spatially inhomogeneous density mechanism parameterization

### ISSUE THREAD

**Issue by espenhgn** [arbor-sim/arbor#1582]
Following up to discussion started at https://github.com/arbor-sim/arbor/discussions/1581

Certain ion channel such as Ih may depend on position/distance to a particular cell location, see e.g., Kole et al., 2006: https://doi.org/10.1523/JNEUROSCI.3664-05.2006 (supporting model: http://modeldb.science/showmodel?model=64195).
Currently there's no trivial way to parameterise a channel/density mechanism (e.g., it's conductance `g`) as function of position. It would be great if a feature to define such parameters in the form of a function using basic math operations could be added, something along the lines of:
```
m = arbor.mechanism('Ih', {'g': '0.01*exp(("mlocation" - "mlocation_0")/100.) + 0.1'})
```
I'm guessing the most common use case would be to measure distance as the intracellular distance between every possible location and some reference location (cf. NEURON's `distance` function), however, a use case I have in mind would rather use the actual segment location in space (its `mpoint` I presume). Hope this description was clear enough.

**Comment by halfflat** [comment]
I just had a look at the model on ModelDB, and while we cannot yet support the stochastic activation components of the model, we have been thinking about how we might support inhomogeneous parameters for a while, and this is a good use case for us to start on an implementation.

We've been discussing a possible representation on our development channel, and I hope to write this up as a more fleshed out proposal in the next day or two.

**Comment by espenhgn** [comment]
Hi Sam. The stochastic activation of that model is not really something I'm concerned about right now (although it is certainly important for some models!). Here's another arbitrary example that investigates sub-cellular distributions of another type of channel: http://modeldb.yale.edu/156039
