### ISSUE TITLE
Support for parameter sweeps

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#1584]
TBD

**Comment by brenthuisman** [comment]
Being able to dispatch sets of parameters to different nodes would help parameter optimization studies, e.g. https://github.com/Meta-optimization/L2L and https://www.cse-lab.ethz.ch/korali/

**Comment by thorstenhater** [comment]
Hey,

I am closing this, it seems out of scope for the Arbor library and rather part of a concrete application based on Arbor.
There's some work being done on optimisation using Arbor, see there #1839. If you have something else in mind, please
re-open.
