### ISSUE TITLE
TypeError on doing Tutorial "A ring network"

### ISSUE THREAD

**Issue by lungsi** [arbor-sim/arbor#1585]
**Describe the bug**
While going through the steps for [Tutorials » A ring network](https://docs.arbor-sim.org/en/latest/tutorial/network_ring.html), at [execution](https://docs.arbor-sim.org/en/latest/tutorial/network_ring.html#the-execution)
```
# (12) Create a default execution context, domain decomposition and simulation
context = arbor.context()
decomp = arbor.partition_load_balance(recipe, context)
sim = arbor.simulation(recipe, decomp, context)

# (13) Set spike generators to record
sim.record(arbor.spike_recording.all)

# (14) Attach a sampler to the voltage probe on cell 0. Sample rate of 10 sample every ms.
handles = [sim.sample((gid, 0), arbor.regular_schedule(0.1)) for gid in range(ncells)]

# (15) Run simulation
sim.run(100)
print('Simulation finished')
```
it returns the error
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-4cdb07478f3e> in <module>
      2 context = arbor.context()
      3 decomp = arbor.partition_load_balance(recipe, context)
----> 4 sim = arbor.simulation(recipe, decomp, context)
      5 
      6 # (13) Set spike generators to record

<ipython-input-8-f7b5ca1997b2> in connections_on(self, gid)
     29       w = 0.01
     30       d = 5
---> 31       return [arbor.connection((src,0), (gid,0), w, d)]
     32 
     33    def num_targets(self, gid):

TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. arbor._arbor.connection(source: arbor._arbor.cell_member, dest: int, weight: float, delay: float)

Invoked with: (3, 0), (0, 0), 0.01, 5
```

**Additional context**
OS: Ubuntu 20:04
Arbor: 0.5.1.dev0
Python: 3.8.5

**Comment by brenthuisman** [comment]
On which checkout are you? On the latest the script ring A-OK here. I don't recognize the signature there, the `dest: int` should be a `cell_member` as well. Is the script modified?

**Comment by noraabiakar** [comment]
Hi, 
Our API has changed a bit since our last release, and we've evidently forgotten to update our tutorial page. Thanks for pointing that out!
That page is based on this example: https://github.com/arbor-sim/arbor/blob/master/python/example/network_ring.py, if you use the snippets from there, your problem should be solved. 
Basically what changed is that the target of an `arbor.connection` used to be an `arbor.cell_member` (which is a `(gid, index)` pair). Now it's just the `index` because the `gid` is known (it's the `gid` in `connections_on(gid)`).

**Comment by lungsi** [comment]
> On which checkout are you? On the latest the script ring A-OK here. I don't recognize the signature there, the `dest: int` should be a `cell_member` as well. Is the script modified?

I got Arbor from main branch `pip install git+https://github.com/arbor-sim/arbor.git`


> Hi,
> Our API has changed a bit since our last release, and we've evidently forgotten to update our tutorial page. Thanks for pointing that out!
> That page is based on this example: https://github.com/arbor-sim/arbor/blob/master/python/example/network_ring.py, if you use the snippets from there, your problem should be solved.
> Basically what changed is that the target of an `arbor.connection` used to be an `arbor.cell_member` (which is a `(gid, index)` pair). Now it's just the `index` because the `gid` is known (it's the `gid` in `connections_on(gid)`).

Thanks! this solved it. I can do tutorial (or run the script) without error.

**Comment by brenthuisman** [comment]
Ah, yes, now I see. I forgot to look into network_ring.py.

This PR is going to fix the problem: https://github.com/arbor-sim/arbor/pull/1575
