### ISSUE TITLE
Mechanism ABI update wishlist

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1608]
Various things I'd like across the new mechanism ABI implementation, but which can wait until after the first version is merged:
* Work around the ABI types populating top level C++ namespace: with some `#include` hackery, we should be able to have a C++ header that puts all these names just in `arb::` while the C header is effectively unchanged.
* Remove `fvm_foo_type` aliases: just use `arb_value_type` and friends.
* When allocating mechanism storage, use a common method for determining offsets to vectors within the block of allocated storage so that we don't need to hold onto an extra list of pointer data CPU side in the GPU shared-state.
* Move dereferencing of the time vector pointer to the mechanism side, rather than using shims in `mechanism::initialize()` and friends.

**Comment by thorstenhater** [comment]
Closing this, all that can be sensibly done is done.
