### ISSUE TITLE
Rename spike_detector to something more descriptive

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#1642]
The term `spike_detector` is confusing. Proposed renamings:

* `membrane_threshold_detector`
* `mtd`

**Comment by thorstenhater** [comment]
I agree that the name leaks the implementation details. But, a term should be 
- descriptive 
- not too longer
- not an acronym

I have no good solution to offer, sadly, so suggest away ;)

**Comment by schmitts** [comment]
`membrane_voltage_crossing_threshold_from_below_detector`

**Comment by thorstenhater** [comment]
That's literally the name of the C++ class

**Comment by schmitts** [comment]
> That's literally the name of the C++ class

Then let's rename the Python wrapper and make `spike_detector` issue a deprecation warning for a while until we delete it.

**Comment by thorstenhater** [comment]
There you go.
