### ISSUE TITLE
Support for stochastic ODE

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#1643]
For a stochastic contribution in a synapse mechanism I need a random number. So for, no random number is available. Request: add a random number.

**Comment by halfflat** [comment]
Our admittedly vague proposal for adding random sources in the first instance is to model them as random processes, accessed via special function-like symbols in NMODL. This approach should work fine for modelling randomness that is not spatially correlated in point processes, but would require both more work and a more precise definition for spatially correlated noise in a density mechanism.

Could you describe the use case in more detail, perhaps with a mathematical model?

**Comment by schmitts** [comment]
At the moment we don't expect to have correlated noise. We would only need an independent random number (uniform between 0 and 1) per synapse.

**Comment by halfflat** [comment]
It will be simplest if we can restrict these random processes so that in the first instance at least, they are only used in NET_RECEIVE blocks: treating them correctly inside ODE descriptions or current contributions requires some very careful definitions, especially when it comes to uniform white noise.

Can you describe the synapse model?

**Comment by schmitts** [comment]
Cf. https://www.nature.com/articles/s42003-021-01778-y equation (11). We need the random noise in every time step.

**Comment by halfflat** [comment]
In NMODL, we could introduce a term that corresponds to the Gaussian white noise term in the cited equation, that will in turn trigger an SDE interpretation. And then as a first minimal effort, we integrate those in this sort of first order Euler scheme. The other part of the problem will be associating independent RNG seeds or keys with each of these synapses.

**Comment by schmitts** [comment]
Discussing with @jlubo. Is the main difficulty that the noise depends on the time step? Cf. "Exact numerical simulation of the Ornstein-Uhlenbeck process and its integral" https://pdfs.semanticscholar.org/57a2/3a111b40528af0cb1ba86f90d75e8d11a21d.pdf?

**Comment by schmitts** [comment]
@noraabiakar suggested to generate the source from the `mod` but add randomness manually.

**Comment by halfflat** [comment]
Regarding the time step, yes, that's the proximate implementation concern. But more broadly, if we keep the mechanism descriptions 'mathematical' in NMODL and in the future, arblang, then we can provide better implementations of the solution over time, and we have the option of doing other analyses on the governing equations without having to work backwards from a specific numeric solution.

**Comment by thorstenhater** [comment]
Done as per #1884
