### ISSUE TITLE
Amplified stimulus with current clamp at edge of cylinder

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#1645]
When placing a current clamp at the edge of a cylinder, the stimulus response is greater compared to placing the current clamp to "edge - epsilon".

The attached example puts out a plot `cylinder_edge.svg`.

Modify line 88 to see the effect.

[cylinder_edge.py.gz](https://github.com/arbor-sim/arbor/files/7121434/cylinder_edge.py.gz)

**Comment by halfflat** [comment]
I don't have the SWC file used in the demo, but I've been able to recreate the problem: segment 1 in the morphology is a zero-length segment, and there is a bug in `(on-components 1 reg)` where it can create multiple, coincident locations if `reg` contains a zero-length cable after thingification.

**Comment by schmitts** [comment]
[ball_and_stick.swc.gz](https://github.com/arbor-sim/arbor/files/7126358/ball_and_stick.swc.gz)

So sorry!

**Comment by halfflat** [comment]
No worries! I'll get this fix in.
