### ISSUE TITLE
Recipe `probes` function is called for `source_cell` gids

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1649]
**Describe the bug**
It's strange that the recipe calls the `probes` function for gids that are `source_cells` and are not allowed to return anything but an empty list from that function call (or an error is raised)

**Comment by thorstenhater** [comment]
Hi,

as far as I am concerned, this is not a bug, but a consequence of the lazy approach to building models.
Sure, it's a bit more work for user, but the performance gain for parallelisation in the setup phase is what
motivated this.

If you disagree, please re-open and elaborate.

**Comment by Helveg** [comment]
Just skip the call to the user function if you already know that `num_pribes` is 0?

**Comment by thorstenhater** [comment]
It's called and checked. If not empty, the model is broken, so we throw an error.

**Comment by Helveg** [comment]
But why call it if the only purpose is to validate that the user is able to return an empty array? Is it a mini-game? :p

**Comment by thorstenhater** [comment]
Yes. 
Essentially it's a safety measure. If you mistype thinking `gid = 42` is a cable cell (which is really a LIF) and return us a cable probe, we are going to tell you that instead of silently ignoring it.
