### ISSUE TITLE
AEP: Stochastic differential equations in mechanisms

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#1655]
This issue documents the discussion and ideas for supporting stochastic differential equations for independent point sources of noise. Spatially distributed and correlated noise sources are not discussed here.

### Representation in nmodl: 
Expose a new symbol ζ that represents Gaussian white noise. 
The Stochastic differential equation for one-dimensional (time) processes, can typically be described in the form:
> d X(t) = f(X,t) dt + g(X,t) d W(t)

where W is the Wiener process, but with some abuse of notation, this can be written like an ODE:
>X’ = f(X,t) + g(X,t)ζ(t)

where ζ represents (n-dimensional) Gaussian white noise. The NMODL representation could then piggyback on the ODE representation with a new special symbol representing ζ.

### Solving the SDE: 
Possibilities:
1. The Euler-Maruyama method, described [here](https:///en.wikipedia.org/wiki/Euler%E2%80%93Maruyama_method).
2. A second-order solution such as the Runge-Kutta method for SDEs, described [here](https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta_method_(SDE)).
3. Exact solution 

### Seeding the random number generators: 
The Random123 library can be used to supply normally distributed samples used for solving the SDEs. The seeds of the random number generators can be supplied to the mechanisms as parameters, however, it is better to think of them as properties of the simulation object. 

The user can supply a seed to the simulation object (per cell_group?), the simulator, together with the cell_group can then generate seeds for the needed processes based on the user-supplied seed in combination with (gid, lid) identifiers.

**Comment by noraabiakar** [comment]
@max9901 Is this a good description of what you need? You mentioned some time ago that what you really want out of this feature is the seed generation. Can you describe what you expect there?

**Comment by schmitts** [comment]
@noraabiakar Thanks. Looks good. I've also asked @jlubo for comments.

**Comment by bcumming** [comment]
The requirements for random generators for stochastic processes, where there are multiple instances of processes on multiple cells, are that the generator:
1. can be seeded properly
2. can be used to generate independent non-correlated streams
3. produces high quality random streams that pass statistical tests.
4. can be used to generate reproducible results when then same model running on all architectures, CPU and GPU.

`minstd_rand0` is not high quality (fails basic statistical tests RNG quality), generates highly correlated random streams, and is more challenging too seed. It is very simple, so a GPU implementation could be hand rolled.

Random123 is a counter-based random number generator, that makes it possible to generate reproducible high quality random number streams in parallel, with efficient CPU and GPU implementations. By virtue of using being counter based, seeding the value according cell gid, process id, etc is easier.

**Comment by thorstenhater** [comment]
Except #1987 this is done.
