### ISSUE TITLE
Error on catalogue name collision, docs say it should overwrite

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1663]
**Describe the bug**
https://docs.arbor-sim.org/en/latest/python/mechanisms.html?highlight=catalogue#catalogue.extend says extend will overwrite in case of name collisions but on double extend with the same cat:

```
    catalogue.extend(arbcat, prefix)
RuntimeError: mechanism expsyn_stdp already exists
```

**Comment by schmitts** [comment]
Which (default) behaviour do you like better?

**Comment by Helveg** [comment]
Now that there's `arbor.catalogue()` merging operations are easier and I prefer enforcing proper use of prefixes, so raise the error, but update the docs?
