### ISSUE TITLE
Awkward pybind signatures

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1666]
**Describe the bug**
`arbor.mechanism`'s set of accepted arguments are a bit awkward because the signature with positional arguments has anonymous parameter names. It binds `arg0` instead of `name`:

```
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. arbor._arbor.mechanism(arg0: str)
    2. arbor._arbor.mechanism(name: str, params: Dict[str, float])
```

I suppose this occurs for all functions with similar signatures?

Shouldn't the signatures be:

    1. arbor._arbor.mechanism(name: str)
    2. arbor._arbor.mechanism(name: str, params: Dict[str, float])

I can do `arbor.mechanism("name", {})` and `arbor.mechanism(name="name", params={})` and `arbor.mechanism("name")` but not `arbor.mechanism(name="name")`

**Comment by brenthuisman** [comment]
Afaik this is an effect of Pybind. The issue on this is still open: https://github.com/pybind/pybind11/issues/2619

**Comment by Helveg** [comment]
That issue seems to be about the docstring generation. I can't find where it mentions which arg/kwarg overloads are actually accepted by `pybind`.

**Comment by brenthuisman** [comment]
I understood that the docstring generation is a reflection of the way Pybind implements function overloads, it which case it always generates a `func(*args, **kwargs) -> Any` before the overloads and their signatures. 

But I see now that you're asking why `arg0` is named `arg0`, which is nowhere to be seen in https://github.com/arbor-sim/arbor/blob/master/python/mechanism.cpp#L204
Good question. Let me try something, I'll get back to this.
