### ISSUE TITLE
Drawing of the recipe timeline in recipe docs

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1674]
It would be useful to see the timeline how recipes are consumed, which functions are called in what order, and what things does arbor do in between etc. It would fit nicely as a diagram on the conceptual overview at https://docs.arbor-sim.org/en/latest/concepts/recipe.html

**Comment by brenthuisman** [comment]
I would say this is in line with having options for verbosity/logging, which https://github.com/arbor-sim/arbor/issues/1433 is meant to describe. If Arbor had a logging option, info on how the recipe is consumed/accessed would show up, wouldn't it?

**Comment by Helveg** [comment]
Yes, one could piece together the flow from these logs, if it's available I'll PR a diagram to the docs ;)

**Comment by thorstenhater** [comment]
Hi @Helveg, 

I appreciate your quest for knowledge, but I see this firmly the territory of the `/dev` section of the docs.
Is there a real need for a user to know this? If so, we probably did something wrong ;) What's your concrete
need?

**Comment by Helveg** [comment]
I want to know when I can throw certain caches away, perhaps this is a feature request for recipe lifecycle hooks instead then?

**Comment by thorstenhater** [comment]
Sorry, didn't mean to close.

**Comment by thorstenhater** [comment]
Recipe needs to live until `arb::simulation` has been constructed. As we do not hand back control to you any sooner,
that's the best you can do, I fear. As for trying to implement your internal lifetimes: Likely a bad idea, as that would be
wholy dependent on our implementation details, which we do not plan on exposing and that are subject to change at any
moment.

Cache invalidation seems to be motivated by saving on high-watermark memory consumption. Are you that close to the limit?

**Comment by Helveg** [comment]
Fine :) Keep your secrets.
