### ISSUE TITLE
Python domain decomposition

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1675]
Currently there's only `paritition_load_balance` and the hints that can be given pertain only to group size and backend type, and don't really help me. When I think of "load balancing" I want the default to be to "spread the work each node has to do evenly". And I think that that can be done automatically by arbor.

Some feature requests:
* Option to enable round robin distribution of GIDs over nodes instead of contingent chunks (cells of the same type often have contingent IDs so all big cells are places on the same node).
* Recipe function to give a weight per GID and make sure each node has about the same weight.
* Use data of `gap_junctions_on` to make different groups and distribute groups evenly over nodes.

**Comment by thorstenhater** [comment]
You can define your own load balancers. In particular you can provide lists of groupings for the local node. This should allow you all the flexibility you need.

**Comment by Helveg** [comment]
In Python?

**Comment by thorstenhater** [comment]
Yes
https://docs.arbor-sim.org/en/latest/python/domdec.html#arbor.partition_by_group
