### ISSUE TITLE
Lean into Python test discovery

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1687]
Currently the Python test files contains a lot of duplicated peripheral logic per file such as:

```python
# to be able to run .py file from child directory
import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../../')))

try:
    import options
except ModuleNotFoundError:
    from test import options
```

```python
def suite():
    # specify class and test functions in tuple (here: all tests starting with 'test' from classes RegularSchedule, ExplicitSchedule and PoissonSchedule
    suite = unittest.TestSuite()
    suite.addTests(unittest.makeSuite(RegularSchedule, ('test')))
    suite.addTests(unittest.makeSuite(ExplicitSchedule, ('test')))
    suite.addTests(unittest.makeSuite(PoissonSchedule, ('test')))
    return suite

def run():
    v = options.parse_arguments().verbosity
    runner = unittest.TextTestRunner(verbosity = v)
    runner.run(suite())
```

```python
if __name__ == "__main__":
    run()
```

And the tests are invoked as

```bash
python ../python/test/unit/runner.py -v2
```

which is the most obtuse of them all, all of which in the end seems to just emulate `python -m unittest discover -s test`

Is there anyone with domain knowledge that knows why this is done like this and not just dropped in favor of automatic test discovery? There seems to be nothing out of the ordinary going on in the unit tests that actually warrants this setup.

A big drawback of this setup is that adding new tests is a pain, it has to be added in multiple places and can silently be skipped in CI.

**Comment by thorstenhater** [comment]
Our Python testing story is in shambles, for historic reasons. We really should be using a proper framework,
nose, unittest, or pytest. Any recommendations?

See also (possibly duplicate) https://github.com/arbor-sim/arbor/issues/1463
