### ISSUE TITLE
Combining mechanisms into a single mechanisme for performance increase of the GPU backend.

### ISSUE THREAD

**Issue by max9901** [arbor-sim/arbor#1704]
**Describe the feature you need**
The ability to merge mechanisms into a single kernel. A test of a dendrite segment with 4 mechanisms combined into a single mechanism through the mechanism ABI targeting a GPU back end made the accumulative time spent in kernels twice as fast as the current case.  This feature would be very specifically targeting the GPU back end where most of the speedup is expected. 

**Explain what it is supposed to enable**
Faster simulations in general simply because of less overhead of kernel/function calls. 

**Additional context**
A potential solution would be to have the ability to create an object in Cmake/python that selected multiple single describes mechanisms and merges this into a single mechanism. 

Another option is a standalone python script that takes some nmodl files as arguments and outputs a single nmodl file

**Comment by thorstenhater** [comment]
If you have NML2 mechanisms (and simulations) as input, nmlcc (https://github.com/thorstenhater/nmlcc)
will build bespoke specialised and combined mechanisms for the regions mentioned in the simulation. I have seen
20-30% speed-up comparing HH as 3 channels vs one combined.

**Comment by thorstenhater** [comment]
So, given that you can use this in NML2, we observe <20% speed-up in the best case, I'll consider this closeable.
