### ISSUE TITLE
Fixture dev docs

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1707]
I added a bit of a fixture system and it's already doing a good job at deduplicating prerequisites in the Python unit tests, where can I put the dev docs for it?

**Comment by brenthuisman** [comment]
Documentation for adding testing can go into `doc/contrib/test.rst`.

**Comment by thorstenhater** [comment]
Hi @Helveg,

any updates here?

**Comment by Helveg** [comment]
I left this in my GitHub notifications and will get around to this.. soon? :)

**Comment by brenthuisman** [comment]
Bumpety bump. Release v0.8 is coming up, would be nice to have it in :)

**Comment by Helveg** [comment]
Right, if I have the energy I'll do it tonight! Otherwise, spam me tomorrow morning :) It's also early enough in the game to switch to `pytest` instead of `unittest`. It has much better design :)
