### ISSUE TITLE
Pybind11 submodule commit hash does not match version in `spack/package.py`

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1717]
I think #1711 contained an error: the Pybind11 submodule hash is set to `750e38dcfdac59231a615580d4e6cb3647b31779`, which does not correspond to the version requested in the spackfile, which is v2.8 (corresponding to hash `97976c16fb7652f7faf02d76756666ef87adbe7d`). It looks like the feature merged in #1711 depends on a commit made after v2.8, namely https://github.com/pybind/pybind11/commit/8a7c266d26e5c9de3beb478bedddcee26f026b04

While checking Pybind11 out at v2.8 results in failed builds on my machine, strangely the Spack CI job has no issues with it.

Not sure what the best way to fix this is, there's no new release of Pybind yet that we could update both too. Can we point to a commit hash in the spackfile?

**Comment by thorstenhater** [comment]
I tried to reproduce this locally, I got the missing definition error in an unrelated build and checked out `v2.8` in `pybind11`. The resulting build went through without issue. Although I cannot imagine it mattering, this is on MacOS.

**Comment by brenthuisman** [comment]
It's annoying that the Spack build does not have the error that I have locally, but Githubs CI does agree with my local experience.

In any case: these versions/commit hashes should line up, agreed?

**Comment by brenthuisman** [comment]
I know why the Spack build is passing: it pulls in master, not v2.8, as that version is not yet in the pybind spack file: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-pybind11/package.py

The [docs](https://spack.readthedocs.io/en/latest/packaging_guide.html) do not indicate that you can specify a dependency by commit hash. Indeed, the dependencies are other Spack packages, and we can only select the versions listed in the spack file of the dependency.

So, the Spack package has no fixed pybind dependency at the moment, and without reverting to 2.7.1 (latest atm), we can't do much about it, other than reverting #1711.

I would propose to handle dependency changes a little bit differently from now on: they must be brought up in the Gitter and all team members (and possibly others) granted some time to respond. I think we should use the hive-mind to catch overlooking little mistakes like these. We have a strong reason to ensure spack builds don't use `master` of any particular dependency, since this is the way Arbor will be loaded and build into EBrains. What I'll add to the release checklist, is to verify that the versions listed in the spack file are actually in the spack files of the deps. Because if not, we're going to have weird EBrains builds with different versions of deps depending on date of compilation. Perhaps part of updating the spack file, is filing updates to the main spack repo with the versions we need (I don't see an open PR for Pybind updates for example).

What to do in this particular case: not sure. Based on Pybind release frequency, we can expect 2.9 sometime around the Arbor v0.6 release. There will be a delay in it being merged into its spack file, so it won't be on time to guarantee a predetermined dependency version as of that release, which will be the next one available on EBrains. So, although I really don't want to revert #1711, maybe we should?
