### ISSUE TITLE
Solver 'sparse': error for constant value in ODE

### ISSUE THREAD

**Issue by jlubo** [arbor-sim/arbor#1722]
The error "internal compiler error: zero row in matrix solver" occurs if an ODE of the type `dp/dt = c`, with `c` constant, is to be solved. No issues occur for `dp/dt = -p` or `dp/dt = 0`, for instance. The following mechanism code serves to reproduce the error in arbor v0.5.2:
```
NEURON {
    POINT_PROCESS test
}

STATE {
    z
    p
}

INITIAL {
    z = 0
    p = 0
}

BREAKPOINT {
    SOLVE state METHOD cnexp
}

DERIVATIVE state {

    p' = 1
    z' = p
}
```

**Comment by noraabiakar** [comment]
The real error here is that `p' = 1` is not homogeneous, which is a requirement for our solver. The bug is that the real error is not being propagated. 
(BTW, the above example should be `SOLVE state METHOD sparse` for the internal compiler error to be raised).
