### ISSUE TITLE
Difficult to determine source of `_M_range_check` IndexError

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1727]
**Describe the bug**
I'm getting an unhelpful error during simulation construction.

```
    sim = arbor.simulation(self, dd, context)
IndexError: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
```

It is caused by `cable_cell`s with empty morphologies:

```
cable_cell = arbor.cable_cell(arbor.segment_tree(), arbor.decor(), arbor.label_dict())
```

The error is thrown in `arbor.simulation`. Probably when the cable cell is lowered this tasy C++ error is thrown. It should be an error to pass an empty morphology to `arbor.cable_cell` and be raised there, or this error should at least be caught and wrapped with an explanation

**Comment by thorstenhater** [comment]
Hi,

could you provide a minimal (or at least small) example?

Thanks

**Comment by thorstenhater** [comment]
I am considering to close this. Is this still occuring?

**Comment by Helveg** [comment]
:]
