### ISSUE TITLE
Bad Any Cast Error in C++ examples

### ISSUE THREAD

**Issue by kanzl** [arbor-sim/arbor#1752]
**Describe the bug**

Can't run the C++ examples on my M1 Mac.
The benchmark miniapp produces a bad any cast error and the other examples get error messages similar to this:

`exception caught in gap junction miniapp:
recipe::get_cell_kind(gid=6) -> cell_kind::cable does not match the cell type provided by recipe::get_cell_description(gid=6)`

**Comment by thorstenhater** [comment]
Currently this is -- surprisingly -- related to our linking options. A temporary fix is to add
`-fvisibility=hidden` to the linker options of the examples.

**Comment by boeschf** [comment]
Hi @kanzl, I have a PR prepared for your issue. In order for me to check all cases, could you tell me how you invoked the example exactly? thanks
