### ISSUE TITLE
Document expected units used for each nmodl quantity

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#1753]
The units expected for the conductance, voltage, generated currents, ion concentrations, time, etc are not obvious in nmodl. 
A table of these units should be added to the docs.

**Comment by jlubo** [comment]
Supposing that this is not yet in the documentation, it would also be good to put down a mathematical description of how the membrane voltage is actually computed. For example, considering `dv/dt = i_p + i_d` and describing how the currents `i_d` and `i_p` are computed based on density mechanisms and point mechanisms, respectively.

**Comment by thorstenhater** [comment]
It is there, albeit a bit hidden, look into the two documents under `doc/math`, but be aware that these are a bit dated. Also, refer to the WIP PR on developer docs #1639.

**Comment by jlubo** [comment]
I see. It would be better to have that on the web, too. But I will look into it. Thanks!

**Comment by thorstenhater** [comment]
I agree on that, which is why we started #1639. Feel free to comment/add there as well.
