### ISSUE TITLE
Pybind seems to interpret some `decor.paint` docstrs as default values

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1754]
```
arbor.decor().paint()
```

```
TypeError: paint(): incompatible function arguments. The following argument types are supported:
    1. (self: arbor._arbor.decor, region: str, mechanism: arbor._arbor.density) -> None
    2. (self: arbor._arbor.decor, region: str = 'the region label or description.', Vm: Optional[float] = initial membrane voltage [mV]., cm: Optional[float] = membrane capacitance [F/m²]., rL: Optional[float] = axial resistivity [Ω·cm]., tempK: Optional[float] = temperature [Kelvin].) -> None
    3. (self: arbor._arbor.decor, region: str, *, ion_name: str, int_con: Optional[float] = Initial internal concentration [mM], ext_con: Optional[float] = Initial external concentration [mM], rev_pot: Optional[float] = Initial reversal potential [mV]) -> None
```

Some of them look intended, as they don't have quotes around them, but `region: str = 'the region label or description.'` feels extra wrong. I find these hints, even if they'd be intended pretty cluttering. The user will pretty much always already have most of the signature right, and has given a wrong type, is forgetting one, giving one too many. The arg names and types are much more important than the docstr and the docstr clutters the print.

**Comment by thorstenhater** [comment]
Hi,

I took a longer at what pybind11 does, and this seems to stem from the use of `arg_v` where really an `arg` 
should have been used
1. `arg_v{"name", default, "description"}`
2. `arg{"name"}`

This compiles since the arg type is a `std::string`. So, we need to fix these instances.
