### ISSUE TITLE
`build-catalogue` doesn't build GPU mechanisms

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#1776]
The `build-catalogue` script generates the GPU mechanisms but does not build them.
 
Part of the issue is the missing `-B gpu` flag in the call to `generate_catalogue` (the `ARB_WITH_GPU` cmake flag isn't set in the [arbor-config file](https://github.com/arbor-sim/arbor/blob/master/cmake/arbor-config.cmake.in)). But fixing that will only enable the compilation of the `.cpp` files of the GPU mechanisms, not the `.cu` files, which may need to be compiled by a different compiler.

**Comment by llandsmeer** [comment]
+1 I just finished the jupyter notebook that runs my model on arbor master. Works great on the CPU at 30s/10ms, but on the GPU it fails with `RuntimeError: missing implementation for mechanism ca_conc in catalogue`

**Comment by llandsmeer** [comment]
Even a --gpu flag to *only* build the GPU mechanisms but not the CPU ones would be perfect already - the network does not run on the CPU anyway
