### ISSUE TITLE
Random123 as a submodule 

### ISSUE THREAD

**Issue by max9901** [arbor-sim/arbor#1778]
## Goal
Be able to compile random123 on GPU implementations + make them available for users that custom compile their catalogs.

## Implementation
Add the following sub-module and try to get the source code working with the HIP languages. (PR request to the original repo) 
https://github.com/DEShawResearch/random123 

Change the Cmake build to expose the random123 Header files to the user.

**Comment by brenthuisman** [comment]
Duplicate of #1731

**Comment by brenthuisman** [comment]
Was closed with #1872
