### ISSUE TITLE
modcc: WATCH (v >  thresh) 1000 results in error

### ISSUE THREAD

**Issue by w-klijn** [arbor-sim/arbor#18]
The line WATCH (v >  thresh) 1000

leads to an error:

-bash-4.2$ ./modcc -t cpu -o file.txt generic_neuron_iaf_cell.txt
error: generic_neuron_iaf_cell.txt:(line 87,col 29)
  expected a new line after call expression, found '1000'

I know we do the connecting of these manually, reporting the issue

[generic_neuron_iaf_cell.txt](https://github.com/eth-cscs/nestmc-proto/files/514090/generic_neuron_iaf_cell.txt)

**Comment by bcumming** [comment]
the `WATCH` keyword is not supported by modcc.

@w-klijn, can you do some research to find out what it means?

**Comment by w-klijn** [comment]
WATCH ( bool ) is keyword in the nmodl language

The keyword does not occur in the neuron book. Also google searches did not provide a clear definition.

Based on (1) and (2):

WATCH is a trigger mechanism which is called every timestep. When triggered is the it can send a glag to NET_RECEIVE()
with zero delay: net_send(0, flag)

From the the sources it is not clear if this is within the same timestep or the next time step.


1. http://www.neuron.yale.edu/phpBB/viewtopic.php?f=16&t=1062
" WATCH (vv>Vpeak) 2  : Checks for threshold crossing turning flag to 2 ""

2. http://www.neuron.yale.edu/phpbb/viewtopic.php?f=2&t=2234
"WATCH (v > thresh) 1 : if v >= thresh -> net_send(0,1) -> NET_RECEIVE(w=1)  watch is being : executed in each time step, you :dont have to call it."

**Comment by halfflat** [comment]
I don't think this is a feature that we should support directly as described: the behaviour is too dependent upon the particulars of the time stepping used, and points of state discontinuity are not visible from outside the mechanism.

On one hand, we can support simple neuron models like integrate-and-fire with custom cell groups, provided we have a good API for users and a good starting collection. On the other, membrane threshold detection can be a feature we provide to mechanisms, possibly even via the NMODL WATCH syntax, but it will need support from the integrator for correct numerical behaviour.

This latter support is similar to what we'll need though for any event-driven process that enqueues future state changes for itself.

A related problem: how best (numerically) to handle probabilistic Markov state transition mechanisms that have (e.g.) voltage-dependent transition rates?
