### ISSUE TITLE
Reorganize exceptions: Python

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1812]
As popped up in #1716, there's a bit of a 'split' in the way the Python binding can raise exceptions.

There's the 'old' way, which is throwing `pyarb_error`, defined in `python/error.hpp`. This error inherits from `std::runtime_error`, and is implicitly converted by Pybind. The downside is that using it for all errors, means you can't catch based on type in Python.

The new way is registering a translator for C++ error which are all defined in `arbor/arbexcept.cpp`, `arbor/include/arbor/arbexcept.hpp`. Then, in `python/pyarb.cpp`, a line like `pybind11::register_exception<arb::file_not_found_error>(m, "FileNotFoundError", PyExc_FileNotFoundError);` translates it in to a Python exception class. This is relatively new functionality of Pybind, and it is both more terse, more clear and more useful (Python users can now catch specific exception classes).

I propose the following:

1. Replace throws of `pyarb_error` with more relevant exceptions that currently already exist in `arbor/arbexcept.cpp`, `arbor/include/arbor/arbexcept.hpp`. Most exception types probably already exist. Where necessary, new exception types can be added. It's nice to be able to look in just one place to see if you can re-use a type.
2.  Some exceptions will be related to Python/Pybind/the Arbor-Python-binding, not user input or Arbor. We can add these Python specific exception types to `arbor/arbexcept.cpp`, `arbor/include/arbor/arbexcept.hpp`. They're not much more overhead than a few lines never used in Arbor. But, some philosophical problems may exist. An alternative is to define them in `python/error.hpp`.
3. `python/error.hpp` holds two other things: `assert_throw` (used in tests) and `try_catch_pyexception` (Used by `python/recipe.?pp`). These need to be removed or replaced.
4. If possible, remove `python/error.hpp`

**Comment by thorstenhater** [comment]
Also likely resolved.
