### ISSUE TITLE
Maintenance: Bump versions across the board

### ISSUE THREAD

**Issue by thorstenhater** [arbor-sim/arbor#1815]
We will remove support for the following in ~0.7~ 0.8
- [x] python 3.6. EOL reached
- [x] CUDA 10
- [x] GCC 8
- [x] Clang 8
- [x] Apple 9

and bump these by one each.

**Comment by brenthuisman** [comment]
For Python we don't and shouldn't care about upstream EOL.

We have a set of criteria [laid out here](https://github.com/arbor-sim/arbor/wiki/Testing-and-version-management). At this moment, Ubuntu LTS-1 is 18.04 which comes with Python 3.6. v0.7 might roughly coincide with a new Ubuntu LTS, so I just might allow it :)

In any case, I'd like see, for each tool deprecation, whether or not it has consequences for the platforms we want to support.

**Comment by thorstenhater** [comment]
Re: True, but that was the motivator.

Rest: all HPC systems we have access to are on CUDA11 now and we never liked GCC8 anyhow.

**Comment by brenthuisman** [comment]
Let's first close https://github.com/arbor-sim/arbor/issues/1731.

**Comment by brenthuisman** [comment]
For the moment: having Python 3.6 is helpful at Ebrains.

**Comment by thorstenhater** [comment]
This should absolutely be part of 0.8, these compilers are starting to reek.

**Comment by thorstenhater** [comment]
YES! It's been orverdue to do that.

**Comment by llandsmeer** [comment]
We're on CUDA 11.5 on the development machine, so should be fine
