### ISSUE TITLE
Consider throwing more informative errors

### ISSUE THREAD

**Issue by thorstenhater** [arbor-sim/arbor#1826]
We started throwing `domain_error` in analogy to the STL when simulations receive
negative timesteps. We should extend this to more places as sensible and similarly 
keep a keen eye out on improving exceptions. 

This will likely be an ongoing process, so consider this a tracking issue for a long term
project of lower priority.

**Comment by thorstenhater** [comment]
No.

**Comment by brenthuisman** [comment]
Point 1. in that issue, `Replace throws of pyarb_error with more relevant exceptions` seems like what you ask here. What is different, if anything?

**Comment by thorstenhater** [comment]
If you consider the discussion on #1821, the topic there deals with C++ exceptions and being more on the point.
This issue is an extension of that disccusion. Replacing `pyarb_error` is another discussion, as certain (runtime)
errors only ever happen in Python, eg passing `str` instead of `int`.

The example in #1821 is the best I can currently come up with: Passing an argument that violates a (n implicit) contract.
In Python similar errors might appear, but if the error condition is also valid in C++, it should be there.

**Comment by thorstenhater** [comment]
This is mostly handled by exception translation now.
