### ISSUE TITLE
Hard-coded path to compiler spoils creating custom catalogue

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#1834]
`pip install arbor` (0.6) on Ubuntu 20.04.3 LTS fails to compile custom catalogue:

```
[ 60%] Building CXX object CMakeFiles/mycat-catalogue.dir/mycat_catalogue.cpp.o
Traceback (most recent call last):
  File "/home/sschmitt/HBP/FIPPA/FIPPAgithub/AdEx/venv/bin/arbor-build-catalogue", line 232, in <module>
    sp.run(make_cmd,  shell=True, check=True, stdout=out, stderr=err)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'make' returned non-zero exit status 2.
 Error:

make[2]: /opt/rh/devtoolset-10/root/usr/bin/c++: Command not found
make[2]: *** [CMakeFiles/mycat-catalogue.dir/build.make:80: CMakeFiles/mycat-catalogue.dir/mycat_catalogue.cpp.o] Error 127
make[1]: *** [CMakeFiles/Makefile2:79: CMakeFiles/mycat-catalogue.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

because the path to the compiler is hardcoded:

```
venv/bin/arbor-build-catalogue
110:set(CMAKE_CUDA_HOST_COMPILER /opt/rh/devtoolset-10/root/usr/bin/c++)

venv/lib64/cmake/arbor/arbor-config.cmake
51:set(ARB_CXX /opt/rh/devtoolset-10/root/usr/bin/c++)
```

Removing the prefix:

```
sed -i s#/opt/rh/devtoolset-10/root/usr/bin/##g venv/bin/arbor-build-catalogue venv/lib64/cmake/arbor/arbor-config.cmake
```

allows to compile the catalogue.

**Comment by schmitts** [comment]
Follow-up problem is that the user's compiler might mangle symbols differently:

```
python3: symbol lookup error: ./custom-catalogue.so: undefined symbol: _ZN3arb19mechanism_catalogue3addERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14mechanism_infoE
```

this is because the symbol in Arbor's library looks like so:

```
nm venv/lib64/libarbor.a | grep _ZN3arb19mechanism_catalogue3add
00000000000015e0 T _ZN3arb19mechanism_catalogue3addERKSsNS_14mechanism_infoE
```

**Comment by thorstenhater** [comment]
Yes, that's is sadly the expected consequence of 
1. hard-coding the compiler path (which is fine if you build from source, but not when using wheels from pip)
2. using different compilers with different nam mangling schemes

Here's a solution sketch
- wrap the interface used by the external-catalogue.so in a small set of C functions
  - these are `add` and `register_implementation` from `mechcat.hpp` plus the constructor
- declare those as `extern C` and export them from `libarbor.a`

This _should_ (=subject to research) also do away with the need to link libarbor into all catalogue.so
objects. I think at least @bcumming might appreciate.

**Comment by muffgaga** [comment]
(Just asking: There are not other dependencies (which would not be directly part of this arbor C-API) that might also interfere… (e.g. via conflicting libc ABIs)?)

**Comment by thorstenhater** [comment]
Likely yes, and probably we should a test for proper operation before/while installing. However, I fear, well have to wait for reports to come in and fix them case by case.
