### ISSUE TITLE
`arbor.iclamp` documentation missing

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1835]
* arbor.iclamp documentation missing
~* on_components docs missing. eg `on_components(segment(0), 0.1234)`.~

**Comment by thorstenhater** [comment]
Also missing: threshold detector
https://docs.arbor-sim.org/en/latest/concepts/decor.html#threshold-detectors-spike-detectors
is empty.

**Comment by thorstenhater** [comment]
This has been silently resolved, the docs (now) explain the relevant points.
