### ISSUE TITLE
Add a state that can be accessed from all mechanisms and obeys some ODE

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#1853]
To model proteins, we need a variable that gets written (and read) from multiple synapses.

See https://www.biorxiv.org/content/10.1101/2021.04.15.439982v1

Synapses do need an individual instance because they track their plastic weight.

**Comment by jlubo** [comment]
Thank you @schmitts for opening this issue. 

To elaborate on the problem: we need a neuron-wide variable that is a function of the weights of all synapses that belong to the respective neuron. Each individual synapse needs at least read access to this variable (biologically, the variable represents a protein concentration necessary for altering the late-phase synaptic weight).

**Comment by schmitts** [comment]
Please find attached a mockup of the protein dynamics (without the long-term plasticity via calcium) and a UML sequence diagram of long-term plasticity via calcium and the protein dynamics. We hope that the two make clear where we have coupling between synapses and neurons and how the information flows.

This is a point neuron model, but we think it can be extended to a multi-compartment model. If we piggy back on the electrical discretization (CV), we could have separate protein amount per CV. More flexible would be if the user could choose which synapses contribute to which protein amount.

[UML_sequence_diagram.pdf](https://github.com/arbor-sim/arbor/files/8230092/UML_sequence_diagram.pdf)
[protein_mock.py.gz](https://github.com/arbor-sim/arbor/files/8230096/protein_mock.py.gz)

**Comment by thorstenhater** [comment]
Hey, 

as we've merged #1729, Xd for any convenient ion X should do the trick.

**Comment by schmitts** [comment]
@jlubo Do we have everything we need?

**Comment by jlubo** [comment]
Is it possible to model "ions" that do not interact electrically (I mean, modeling concentrations of uncharged particles)? If so, #1729 appears to be a solution for our issue :) Can't try it out too soon, however.

**Comment by thorstenhater** [comment]
Well, if you never compute a current for it (in a mechanism), nothing will happen to the transmembrane current. Changes to the concentrations do not impact the currents. So, all electrical interactions are your own.

Try it out, and re-open if something is missing.

**Comment by jlubo** [comment]
Okay, thanks!
