### ISSUE TITLE
modcc: variable renaming in AST [6]

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#186]
LOCAL variables with the same spelling can collide in the printing code, and also hide global variables of the same name (see bug #91).

This problem could be resolved through the use of variable renaming at the AST level (or by a richer scope context).

Task is to implement a renaming scheme that preserves NMODL semantics (such as they are) while mapping variables to unique identifiers by the time they are printed.

**Comment by thorstenhater** [comment]
As noted in #91, this is no longer an issue and generated names are clearly disambiguated, so I think this can be closed.
