### ISSUE TITLE
Ergonomics

### ISSUE THREAD

**Issue by thorstenhater** [arbor-sim/arbor#1862]
Working with Arbor at a high level requires quite a bit of redundant(?) typing. I propose to go through
our user facing APIs with a fine comb and think deeply on ergonomics.

Here's a list of examples I remember from the top of my head (mostly Python)

1. A dict should be accepted where a label_dict is expected. 
2. Mechanisms should not distinguish between GLOBAL and PARAMETER, ie `pas/e=42` becomes `'pas, e=42`.
3. SWC loading should give back the standard labels like NML and/or have them pre-defined somewhere.
5. Simplify construction of simulations
   ```py
   ctx = A.context()
   mdl = my_recipe()
   ddc = A.partition_load_balance(mdl, ctx)
   sim = A.simulation(mdl, ddc, ctx)
   ```
   there is no reason(?) to pass `ctx` and `ddc` multiple times. One idea could be this
   ```py
   ctx = A.context()
   mdl = my_recipe()
   ctx.partition_load_balance(mdl) # ctx now holds on to what ddc was above
   sim = A.simulation(mdl, ctx)
   ```
   or even
   ```py
   ctx = A.context()
   mdl = my_recipe()
   sim = ctx.partition_load_balance(mdl) # what else can you do w/ ddc?
   ```
   That doesn't mean the lower levels need to go away.
5. Related, probing is at least a 3 step process.
6. The Python module could use more sub-modules.

**Comment by Helveg** [comment]
Re (6): The main module is now basically a prefix based mixture:

```
{
   "cable":22,
   "cv":7,
   "cell":5,
   "load":5,
   "mpi":5,
   "mechanism":3,
   "partition":3,
   "spike":3,
   "meter":2
}
```

**Comment by thorstenhater** [comment]
Exactly ;)
