### ISSUE TITLE
Allow setting global parameters of mechanisms using ACC

### ISSUE THREAD

**Issue by lukasgd** [arbor-sim/arbor#1869]
`(paint (all) (density (mechanism "pas" ("g" 3e-05) ("e" -75))))`
Produces an error: `mechanism pas has no parameter e`

**Comment by thorstenhater** [comment]
That's not really a bug. Fix by `(paint (all) (density (mechanism "pas/e=-75" ("g" 3e-05))))`.
We know that it's an ugly wart, see the ergonomics discussion here #1862

**Comment by thorstenhater** [comment]
I think this is answered, if not, please re-open.
