### ISSUE TITLE
modcc: support INITIAL blocks for linear kinetic schemes [10]

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#187]
There's no automatic computation of steady-state values (or recognition of CONSERVE statements) for use in INITIAL blocks that refer to a KINETIC scheme.

1. Implement steady-state determination for the linear scheme case.
2. Add parsing and code generation for this use of INITIAL.

**Comment by bcumming** [comment]
This has been fixed by @noraabiakar.
