### ISSUE TITLE
Have `sampling_policy` that collects samples over MPI ranks 

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1892]
For examples and short scripts [1], and possibly larger ones as well, it would be nice to have `arbor.simulation.samples` return data from all ranks, not just its own. In C++, samplers are set with a reference to a `trace_vector`, which after `sim.run()` returns contains data from all ranks. Python's `arbor.simulation` also sets callbacks for the samplers: https://github.com/arbor-sim/arbor/blob/master/python/simulation.cpp#L137 While OK for large simulations, it requires the slightly awkward bookkeeping of sampler handles in addition.

I propose a small extension to Python's `simulation_shim` that takes care of this similar to [`ring.cpp`](https://github.com/arbor-sim/arbor/blob/master/example/ring/ring.cpp#L177 ): by having a single `trace_vector` where all samplers write.

Does it make sense to do this though a new `sampling_policy`? It would be congruent to `spike_recording_policy.all`. On the other hand, in C++ it is already solved/solvable, see https://github.com/arbor-sim/arbor/blob/master/example/ring/ring.cpp#L177 (`voltage` is written to disk at the end, and contains all samples regardless of MPI config), so maybe another way to set this behavior is desired.

[1] Cases in point:
- https://github.com/arbor-sim/arbor/pull/1868
- https://docs.arbor-sim.org/en/latest/tutorial/network_ring_mpi.html#the-results

**Comment by thorstenhater** [comment]
Given the option of parallel I/O or a straightforward MPI solution, I am discarding this for now.

**Comment by halfflat** [comment]
Just saw the closing; I agree. This should be outside the scope of the core library; ultimately we could provide something in the extension library, or maybe even in the python interface, but collective sampling is not a good fit for scalable performance, as far as I can see it.
