### ISSUE TITLE
Bubble up CPP call stack to pyarb errors

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1896]
**Describe the feature you need**
A category of `RuntimeErrors` exist that are transformed into relatively useless one liner messages, and their CPP origin is unknown. The call stack ends on the Python side usually on a pretty large entry point such as `arbor.simulation`. 

**Explain what it is supposed to enable**
Please, to expedite and improve issue reporting, include a CPP call stack trace so that we can copy paste that to you in our issues.

**Additional context**
See https://github.com/arbor-sim/arbor/issues/1895

**Comment by thorstenhater** [comment]
Sadly, C++ does _not generate_ stacktraces on exceptions. Sorry, nothing to be done here :(
