### ISSUE TITLE
Sending events to self: net_send(delay, flag)

### ISSUE THREAD

**Issue by w-klijn** [arbor-sim/arbor#19]
net_send(delay, flag)

Allows a NetCon object to send an event to self with delay and flag (Neuron book 294 - 295.)
This function is used primarily in the NET_RECEIVE block (neuron book 288), which implements how a NetCon object reacts to events

delay : unit time
flag  : unit ?int?
    Flag is called by value (unlike the the explicit arguments declared inside the parenthesis, which are "call by reference")
    From the NEURON documentation it not clear: but it appears that flag is an int and multiple flag values are valid

Typicall use case (iaf neuron refract period) pseudo code:

```
PARAMETER {
    refract_period = 5 (ms)
    refractionary = 0
}

NET_RECEIVE (w) {
  if (refractionary == 0) {
    <update neuron state>
    if (state == spike) {
        refractionary = 1
        net_send(refract_period, refractionary) : send self event with delay
    } 
  }
  else if (flag == 1)  { : self event received
        refractionary = 0
        <reset neuron state>  
  } : else ignore external events
}
```

Found at least in the following blocks:
INITIAL
NET_RECEIVE

Example usage:
http://neuralensemble.org/trac/PyNN/browser/trunk/src/neuron/nmodl/netstim2.mod?rev=888

**Comment by bcumming** [comment]
I can see that implementing it in the INITIAL block will be more problematic, because INITIAL is applied in parallel.

**Comment by bcumming** [comment]
This pattern is motivated by plasticity, which we don't yet support. We will add suppot in SGA3, and there is a very high likelihood that we will use a different approach.
