### ISSUE TITLE
More neuroscience: a showcase of some neuroscience.

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1998]
In order to beef up demonstrations of Arbor in scientific research, we could have a common workload worked out into a Jupyter Notebook. @llandsmeer has a student who'll use Arbor to match physiological data to an existing model, a common workload for new students. For modellers this showcases how Arbor can enable neuroscience research.

**Comment by thorstenhater** [comment]
This isn't really a code issue, but an ongoing strategic goal.
