### ISSUE TITLE
User defined synaptic kernels for LIF cells

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#2027]
LIF cells support only delta synapses at the moment. It would be good if user defined synaptic kernels could be defined. Most flexible would be if point mechanisms formulated in NMODL (just as for cable cell) could be used.

**Comment by thorstenhater** [comment]
Hi.
Thanks for bringing this up, it'll also be important when translating NML2. There, however, the way forward
seems to be converting to a single CV cable cell and making a bespoke POINT_PROCESS. Would that also be
an option here?

**Comment by schmitts** [comment]
Yes, I think that would be in option (not withstanding #1517).

**Comment by thorstenhater** [comment]
Despite some issues with that approach, I think it's the cost-efficient way to go, for NML2 at least.

**Comment by thorstenhater** [comment]
This can now be achieved by using a 
- VOLTAGE_PROCESS density
- single CV/soma-only cable cell
- and any synapse you like.

If more is needed, please re-open.
