### ISSUE TITLE
Parallel sort for cthread backend

### ISSUE THREAD

**Issue by apeyser** [arbor-sim/arbor#206]
A parallel sort should be written for our code. The cthread backend needs it.

**Comment by halfflat** [comment]
Note for reference: Intel's parallel stable sort implementation has been removed owing to incompatibilities with `nvcc`. The aim is to have a portable, C++ thread-backed implementation.

**Comment by bcumming** [comment]
For reference:
http://www.drdobbs.com/parallel/parallel-in-place-merge-sort/240169094

**Comment by apeyser** [comment]
That's what I was thinking, since it falls easily into the task-based approached.
Maybe @YachaoShao ?

**Comment by bcumming** [comment]
And there are some nice little challenges like parallel in place merge.
