### ISSUE TITLE
Arbor crashes on GPU if a mechanism is probed that is not placed

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#2066]
Arbor crashes with `IndexError: _Map_base::at` on GPU if a mechanism is probed that is not placed. This is different from the behaviour on CPU where Arbor runs and, as expected, samples are empty when retrieved after the simulation. The attached script reproduces the bug on `27db9a7f700bb05680a811ba3445e734d61aacf6`. 

The line that triggers is:

https://github.com/arbor-sim/arbor/blob/b63cca1c50a2a4d0d7d24f1b8de1fdd5581806cf/arbor/fvm_lowered_cell_impl.hpp#L1062

script:

[single_cell_recipe.py.gz](https://github.com/arbor-sim/arbor/files/10226552/single_cell_recipe.py.gz)

stack trace:

[gdb.txt.gz](https://github.com/arbor-sim/arbor/files/10226580/gdb.txt.gz)

**Comment by jlubo** [comment]
A suggestion: I think it would be nice to throw a warning any time a mechanism is probed which has not been placed. That may save some development time for CPU setups as well.
