### ISSUE TITLE
Pressing Ctrl-C during Arbor simulation in a Python process will not stop the process

### ISSUE THREAD

**Issue by llandsmeer** [arbor-sim/arbor#2068]
To reproduce:

 - start a long running arbor simulation run()
 - press Ctrl-C
 - nothing will happen, until the simulation is done

To fix, we should call Py_CheckSignals() in the mainthread and then propagate the error in pybind, which will then result in a KeyboardInterrupt error

 - [Python documentation on CheckSignals](https://docs.python.org/3/c-api/exceptions.html#c.PyErr_CheckSignals)
 - [PyBind11 documentation on propagating exceptions](https://pybind11.readthedocs.io/en/stable/advanced/exceptions.html#handling-exceptions-from-python-in-c)

Eg

```c++
if (PyErr_CheckSignals() != 0)
    throw py::error_already_set();
```

In practice, this might be a bit more complicated. We could for example replace the current

```c++
arb::time_type run(arb::time_type tfinal, arb::time_type dt) {
    return sim_->run(tfinal, dt);
}
```

with

```c++
arb::time_type run(arb::time_type tfinal, arb::time_type dt) {
    arb::time_type tepoch = 0;
    while (true) {
        if (PyErr_CheckSignals() != 0) {
            throw py::error_already_set();
        }
        tepoch += dt * 100;
        arb::time_type res = sim_->run(std::min(tepoch, tfinal), dt);
        if (tepoch >= tfinal) {
            return res;
        }
    }
}
```

ie checking every 100 timesteps for a signal. 

Alternatively, we could check every timestep or decide we don't want this.

I'll happily write the PR but I think we should first decide how we go about this.

**Comment by schmitts** [comment]
What about sending SIGQUIT with Ctrl-\ instead of SIGINT with Ctrl-C?

**Comment by llandsmeer** [comment]
Ctrl-\ doesn't seem to work, but indeed usually killing the process works. Still very annoying in a jupyter notebook, which will then also delete all stored variables

**Comment by llandsmeer** [comment]
Copying the note from #2070:

> So we decided that the ^C check needs to happen in the epoch callback. Problem is that the epoch callback only gets called in simulations with spikes (also affecting the progressbar.. ). So that doesnt solve the problem. No idea how to proceed, maybe close for now

So first #2089 needs to be solved before tackling this issue

**Comment by thorstenhater** [comment]
This an artifact of our binding from Python to C++ and cannot be fixed, even with a custom
epoch callback. Unless said callback hands control back to Python, the interpreter will not
propagate signals (more accurately, not until the GIL is released). I neither tried nor do I think
it a particularly good idea to release the GIL around `sim::run`.

See here: https://pybind11.readthedocs.io/en/stable/faq.html#how-can-i-properly-handle-ctrl-c-in-long-running-functions
