### ISSUE TITLE
Add MPI support for dry run mode

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#213]
Currently the dry run mode performs simulation on a single domain, which corresponds to an MPI rank for the MPI global communication back end. This is an appropriate abstraction when using 1 MPI rank per node, however it can't be used to gain insight into performance when there is more than 1 MPI rank per node.

Such scenarios include
* 1 MPI rank per CPU core on a multi-core system
* 1 MPI rank per quadrant on a KNL node (i.e. 4 ranks per node)
* 1 MPI rank per GPU on a multi-GPU node

The dry run mode should be extended to work with MPI so that projections can be made from simulations with multiple MPI ranks on a node, or simulations running on a small number of nodes.

**Comment by apeyser** [comment]
Why would you ever run more than 1 mpi rank per node? You're re-doing all the spike work, and copying all the spikes which eat up a large amount of memory.

The only thing I can think of is that the spike injection code would be parallel -- but wouldn't that be done better by parallelizing the exchange step?

**Comment by bcumming** [comment]
On KNL we might want 4 ranks per node, because of the Quadrants.
On a dual socket system we want two MPI ranks per node.
It might be interesting to use a small set of nodes for a dry run.

**Comment by bcumming** [comment]
Also, the GPU case where we have more than one rank per node if there are multiple GPUs per node. The PCI bus and memory bandwidth are then shared resources between multiple ranks, so you want to have those in your model.
