### ISSUE TITLE
Strange looking doc section

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#2136]
Something seems off here: https://docs.arbor-sim.org/en/stable/concepts/simulation.html#configuring-data-extraction

**Comment by Helveg** [comment]
Also the signature of `set_ion` looks funky: https://docs.arbor-sim.org/en/latest/python/cable_cell.html#arbor.cable_cell_global_properties.ion_reversal_potential

And the top right logo is broken for that page as well.

**Comment by boeschf** [comment]
Thanks @Helveg for reporting. Should be fixed now.
