### ISSUE TITLE
PyPI secret and workflow notification issue

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#2361]
I saw some release prep going on today and I realised I still has full control over the (Test)PyPI Arbor packages. I removed myself from the projects, but now I see my personal PyPI secret was still in use: https://github.com/arbor-sim/arbor/actions/runs/10128317070/job/28203289503#step:3:60

Until recently, those secrets had to be tied to a personal account, so you can either generate one yourself, or setup a PyPI org.

Also: I still get notified of `https://github.com/arbor-sim/arbor/blob/master/.github/workflows/build-pip-wheels.yml` CI results; do you? Upon reading the [docs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/notifications-for-workflow-runs) more closely, you need to not only touch the file but specifically update the cron conditions in order to redirect the notifications.

**Comment by thorstenhater** [comment]
Thank you, the update to test-pypi has been failing for stacked reasons: Storage exhausted and now an issue with the token/login. Both should now be resolved.
I now get notifications for these workflows.

**Comment by brenthuisman** [comment]
Ah yes, every now and then TestPyPI needs a culling. OK, good to hear it worked out, so far I haven't been notified again :)

**Comment by brenthuisman** [comment]
BTW, I see that the cron part hasn't been touched yet.

Also, I noticed that Ben hasn't set up 2F on PyPI. At one point, they locked down such projects for a while, so you may encourage him to do so if you don't want to be a victim of their anti-abuse measures.

**Comment by thorstenhater** [comment]
Looks like everything is fine now.
