### ISSUE TITLE
modcc: && not recognized as a boolean operator

### ISSUE THREAD

**Issue by w-klijn** [arbor-sim/arbor#25]
Using the && to chain two boolean statement leads to an error:

error: unexpected character '&' at (line 55,col 22)
./offset_current.mod:(line 55,col 22)
  unexpected token &

Codeblock:

```
    if (t >=  delay  && t <  duration  +  delay) {
        i = amplitude : standard OnCondition
    }
```

**Comment by bcumming** [comment]
Can you please add this feature @w-klijn ?
