### ISSUE TITLE
modcc: ELECTRODE_CURRENT Not recognized as an nmodl feature

### ISSUE THREAD

**Issue by w-klijn** [arbor-sim/arbor#26]
`ELECTRODE_CURRENT` is currently not recognized by modcc.

The documentation regarding this feature is sparse. It appears to be a direct injection of current in the cell. Not passing the cell membrane.

The NEURON book does have an entry, but does not describe anything about it.
The mention I found online:

intracellular stimulating electrode

An intracellular stimulating electrode is similar to a shunt in the sense that both are localized
sources of current that are modeled as point processes. However, the current from a stimulating
electrode is not generated by an opening in the cell membrane but instead is injected directly into
the cell. This particular model of a stimulating electrode has the additional difference that the
current changes discontinuously, i.e. it is a pulse with distinct start and stop times.

```
: Current clamp
NEURON {
    POINT_PROCESS IClamp1
    RANGE del, dur, amp, i
    ELECTRODE_CURRENT i
}
UNITS { (nA) = (nanoamp) }
```

Figure 4
Hines and Carnevale: Expanding NEURON with NMODL
Revised 4/6/2000 Page 12

```
PARAMETER {
    del (ms)
    dur (ms)  < 0, 1e9 >
    amp (nA)
}
ASSIGNED { i (nA) }
INITIAL { i = 0 }
BREAKPOINT {
    at_time(del)
    at_time(del+dur)
    if (t < del + dur && t > del) {
        i = amp
    } else {
        i = 0
    }
}
```

Listing 3. iclamp1.mod

The NEURON block

This mechanism is identical to the built-in IClamp model. Calling it IClamp1 allows the
reader to test and modify it without conflict with the existing IClamp point process.
This model of a current clamp generates a rectangular current pulse whose amplitude amp in
nanoamperes, start time del in milliseconds, and duration dur in milliseconds are all adjustable
by the user. Furthermore, these parameters are individually adjustable for each separate instance
of this mechanism. Therefore they are declared as RANGE variables in the NEURON block.
The current i delivered by IClamp1 is declared in the NEURON block to make it available for
examination. The ELECTRODE_CURRENT statement has two important consequences: positive
values of i will depolarize the cell (in contrast to the hyperpolarizing effect of positive
transmembrane currents), and when the extracellular mechanism is present there will be a
change in the extracellular potential vext. Further discussion of extracellular fields is beyond the
scope of this paper.

**Comment by bcumming** [comment]
Please take some time to format the tickets clearly. In particular, try to put code snippets in code blocks with indentation.

**Comment by bcumming** [comment]
We support a similar feature in NMODL called `NONSPECIFIC_CURRENT`. The difference between `NONSPECIFIC_CURRENT` and `ELECTRODE_CURRENT` might be that one is a current density, and the other is a current. So supporting it shouldn't be too hard.

**Comment by bcumming** [comment]
We actually have such current clamps (we call them `stimuli`, neuron calls them `iclamp`) built into nest-mc. They are available in the C++ model description. Below is a bit of code from our testing framework that creates a simple cell and attaches a current clamp

```C++
inline cell make_cell_soma_only() {
    cell c;

    auto soma = c.add_soma(18.8/2.0);
    soma->mechanism("membrane").set("r_L", 123);
    soma->add_mechanism(hh_parameters());

    c.add_stimulus({0,0.5}, {10., 100., 0.1});

    return c;
}
```

**Comment by w-klijn** [comment]
I'm currently testing with the following mod file:

[electrode_current.txt](https://github.com/eth-cscs/nestmc-proto/files/539009/electrode_current.txt)

With some copy past coding modcc currently produces:
[test.txt](https://github.com/eth-cscs/nestmc-proto/files/539029/test.txt)

**Comment by bcumming** [comment]
Could you please put the code inline in comment.

**Comment by bcumming** [comment]
I would recommend just using `add_stimulus`, instead of a custom mechanism like this.

What you have is a good start. You have to hook `i` up as a current, similarly to what is done for a `nonspecific_current`. In fact, I think you could just define it as a `nonspecific_current` in `parser.cpp`.

For a hint, have a look at the code that is generated for a `nonspecific_current` for `expsyn.mod`.

**Comment by w-klijn** [comment]
bcumming 4:23 PM 
to find out how to call generated code, have a look at `expsyn`.  hunt through the nestmc source for everywhere `expsyn` appears.

1. you have to add your new .mod file to the mechanisms path
2. add rules for generating the .hpp file into `CMakeLists`
3. let the `mechanism_catalogue` know about your new mechanism
4. insert it like we insert a synapse

Some notes:
1. the generated code currently does not update the currents. Have a look at the generated code for `expsyn`

2. to use `add_stimulus`, have a look in the corresponding neuron python scripts in the repo, and look for an iclamp
then look again at the C++ code that add stimuli.

**Comment by bcumming** [comment]
Sam and I have had a look at `ELECTRODE_CURRENT`, and it isn't really required. It can be implemented using a non-specific current and a bit of slight of hand.

This still won't work because of the requirement that the current update must involve `v`, which is there for legacy reason. You could do something like `i = i_clamp + 0*v`, and make a ticket for me to fix this (or try to remove the v dependence yourself.)

```
NEURON {
    POINT_PROCESS offset_current
    NONSPECIFIC_CURRENT i
    RANGE delay
    RANGE duration
    RANGE amplitude
}

UNITS {
    (nA) = (nanoamp)
}

PARAMETER {
    delay = 0 (ms)
    duration = 200 (ms)
    amplitude = 0.0025 (nA)
}

ASSIGNED {
    i_clamp
}

INITIAL {
}

BREAKPOINT {
    if (t <  delay) {
        i_clamp = 0 
    }   

    if (t >=  delay ) { 
        i_clamp = amplitude
    }   

    if (t >=  duration  +  delay) {
        i_clamp = 0 
    }   

    i = i_clamp
}
```

**Comment by w-klijn** [comment]
"so a soft error with a nice little message explaining how we do things might be the best solution" (Ben)
