### ISSUE TITLE
Add regression test suite

### ISSUE THREAD

**Issue by w-klijn** [arbor-sim/arbor#271]
During the implementation of issue 241 it became clear that it is time to add a regression test suite:
Some of the changes were not caught by the existing tests.

This issue will add scripts to run the standard miniapp recipes.
It will also add three blessed spike data sets, to compare against.
The tests should run without environment settings, thus a runner script with absolute paths should
be generated.
The tests will be added to the cmake environment and can be started with:

make regression test

**Comment by halfflat** [comment]
Commenting now, because it is still relevant: unit tests and nsuite validation aside, we don't have a basic make-sure-the-spikes look correct test.

**Comment by halfflat** [comment]
Renamed issue, to be specific to spike output test. Not exactly a unit test, but we can shove it under there for convenience.

**Comment by thorstenhater** [comment]
Once we have more comprehensive NML support, we should hook into this here
https://github.com/OpenSourceBrain/osb-model-validation

**Comment by thorstenhater** [comment]
Given that NSuite is now tied in with Arbor and our examples are now to be checked before each merge, I consider this done for now.
