### ISSUE TITLE
Implement GPU backend of LIF neurons. [10]

### ISSUE THREAD

**Issue by kabicm** [arbor-sim/arbor#337]
Implement GPU backend of LIF cell groups. Test the performance of LIF cells using Brunel Network of LIF cells (miniapp). Compare the performance with the CPU backend of LIF neurons.

**Comment by bcumming** [comment]
We don't need this feature, at least until somebody wants to run LIF cells in Arbor, and we make our communication back end an order of magnitude more efficient ;).

**Comment by halfflat** [comment]
I'd like to keep this issue open: we can mark it as low priority, but Brunel network benchmarks are a thing, and running these guys on GPU is a component of making that run fast.

Spike wrangling may dominate, but that will be a common problem for many classes of simple cells on GPU, and I don't think it should be a reason to dismiss this feature.
