### ISSUE TITLE
Test failures in dryrun mode.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#339]
1. Test failures in `global_communication.exe`

    To replicate, configure with `-DNMC_DISTRIBUTED_MODEL=dryrun`, build `global_communication.exe` and run the communicator tests with a dryrun size greater than 1, e.g.
    ```
    % ./tests/global_communication.exe --gtest_filter=communicator\* -d 5
    ```
    Tests `communicator.ring` and `communicator.all2all` will fail with expected event checks.

2. The `domain_decomposition` unit tests in `test.exe` will also fail (and segfault), as the unit test driver does not configure the dryrun size.

**Comment by bcumming** [comment]
The global communication context is no longer a compile time configuration, so the tests will (rightly) never be configured this way.
