### ISSUE TITLE
Extend CI to check vector, CUDA compilation.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#364]
The current suite of Travis tests does not confirm that the CUDA target or vectorization (e.g. AVX2) targets compile or run, which can allow errors to creep into the code base more easily, especially given the extra load on the developer to build and test on these platforms.

Extending the Travis tests to at minimum check that these configurations build will help.

**Comment by thorstenhater** [comment]
CUDA targets are checked semi-automatically by commenting `bors try`.
