### ISSUE TITLE
Negative memory amount in model-simulate meter

### ISSUE THREAD

**Issue by w-klijn** [arbor-sim/arbor#371]
When running a single or multi GPU MPI run a negative amount of memory is displayed for the model-simulate meter.

Running on Juron:
```
#!/bin/bash
#BSUB -q normal
#BSUB -n 2
#BSUB -R "rusage[ngpus_shared=1] span[ptile=1]"
#BSUB -e "stderr.%J"
#BSUB -o "stdout.%J"
#BSUB -W 00:10
#BSUB -J Arbor_multi_gpu

module load cuda
module load gcc
module load cmake
module load openmpi/3.0.0-gcc_5.4.0-cuda_8.0.61

export ARB_NUM_THREADS=2
mpirun /gpfs/homeb/pcp0/pcp0016/code/arbor/feature/2d_dynamics/cuda_build/miniapp/miniapp.exe -n 10000 -s 4000
```
output:

```
=========================================
  Arbor miniapp
  - distributed : 2 (MPI)
  - threads     : 2 (CThread Pool)
  - gpus        : 1
==========================================
---- meters ------------------------------------------------------------
                             time (s)     memory (MB) memory-gpu (MB)
------------------------------------------------------------------------
setup                          0.0002          0.0241          0.0000
model-init                     6.5071        828.8546        780.1405
model-simulate                86.1912      -2825.3320        243.2696
-----------------------------------------------------------
```

**Comment by halfflat** [comment]
`mallinfo` has essentially been deprecated in GNU libc, but the replacement `malloc_info` provides data (in XML!) that is both undocumented and incomplete.

Links:
* `mallinfo` 64-bit unclean discussion from 2004: https://www.sourceware.org/ml/libc-alpha/2004-08/msg00008.html
* In 2005 bug report, Drepper tells the reporter they should write a dynamically loaded shim to capture `malloc`, `realloc`, `free` calls and count the allocations.
* Drepper on the new interface: http://udrepper.livejournal.com/20948.html
  Note that this XML output has a version number (yay) but there is _no schema for this document_ nor is there any documentation regarding the semantics.

Looks like `malloc_stats()` actually provides the information, but this is _hard-coded to write to stderr_, I shit thee not.

**Comment by halfflat** [comment]
It's not entirely safe versus other threads attempting to write to `stderr`, but here's a wrapper that seems to do the job. Only works with GNU libc (it reads/writes the global `stderr` variable), and parsing is left as an exercise to the reader.

```
extern "C" {
#include <malloc.h>
#include <stdio.h>
#include <stddef.h>
}

#include <string>
#include <mutex>

std::string malloc_stats_wtf() {
    static std::mutex mux;
    std::lock_guard<std::mutex> g(mux);

    // Saving/restoring `stderr` is GNU libc-specific.
    FILE* saved_stderr = stderr;
    char* buf = nullptr;
    std::string data;

    try {
        size_t buflen = 0;
        stderr = open_memstream(&buf, &buflen);

        if (stderr) {
            malloc_stats();
            fflush(stderr);
            data = std::string(buf, buf+buflen);
        }
    }
    catch (...) {}

    stderr = saved_stderr;
    if (buf) free(buf);
    return data;
}
```

**Comment by bcumming** [comment]
We both found the same horrors in our research.

I am minded to quote "You have a problem that you try to solve with XML. Now you have two problems."

**Comment by halfflat** [comment]
>  "You have a problem that you try to solve with XML. Now you have two problems."
<quite />

**Comment by bcumming** [comment]
How CP2K does it:
https://github.com/cp2k/cp2k/blob/master/cp2k/src/base/machine_posix.f90#L93

**Comment by thorstenhater** [comment]
Where available we use `mallinfo2`, which does not have this issue.
