### ISSUE TITLE
Use SI units everywhere

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#375]
Arbor uses a similar approach to NEURON for choosing the units of basic quantities: i.e. using units like `ms` and `um` that have a scale appropriate for modelling cells.

This causes a lot of pain for everyone:
* modelers have to add magic numbers of 10^n throughout models, and nobody wins
* modelers and developers have to constantly fret over the units on currents, distances, etc.

NMODL makes the situation worse by allowing users to use arbitrary units for variables.

We should move all variables to standard SI units.

Steps:
1. investigate whether/where using base SI units would introduce numeric issues
2. implement

**Comment by thorstenhater** [comment]
This is largely resolved by having a unit-safe API.
