### ISSUE TITLE
Poisson input cell_group

### ISSUE THREAD

**Issue by w-klijn** [arbor-sim/arbor#397]
A typical neuroscientific model has some for of input spike trains at regular (2 to 20hz) spike rate.
Issue #396 is a refactoring of the rss_cell_group which has great overlap.
Implement the drawing of random number from independent number generators for each simulation timestep and use the propabilities to generate spikes, to be distributed using the normal spike distribution.

Tasks:
1. Discuss the usage of main simulation seed.
2. Discuss how to do the per neuron seed
3. Implement the run function
4. Add unit test for the run function
4. Implement the cell description
5. Documentation 

Time estimation: 30Hrs

**Comment by halfflat** [comment]
We have event generators now that can supply spikes to a given cell according to a Poisson process starting from a given time point. But we don't have artificial cells that spike according to such a process.

Is what we have sufficient? Or do we need the latter (for correlated Poisson spike inputs to other cells, for example)?

**Comment by brenthuisman** [comment]
With permission from @w-klijn
