### ISSUE TITLE
modcc SIMD printer does not understand conditionals

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#405]
If the SIMD printer encounters a conditional test, for example in the context of an `if` condition, `modcc` fails with an ICE.

Generated vectorized code should play fancy tricks with masks or failing that, fall back to scalar code if a conditional cannot be handled with vector operations.

Example mechanism:
```
NEURON {
    SUFFIX demo
    NONSPECIFIC_CURRENT i
    RANGE r, s
}

STATE {
    r
    s
}

BREAKPOINT {
    SOLVE rs METHOD sparse
    if (r>0) {
	i = r*v
    }
    else {
	i = 0
    }
}

INITIAL {
    r = 0
    s = 1
}

DERIVATIVE rs {
    r' = s
    s' = -r
}
```

`modcc -t cpu demo.mod` produces expected code; `modcc -t cpu -s avx2 demo.mod` gives the error:
```
internal compiler error: SimdPrinter: Unknown binary operator: > @ (line 14,col 10)
```

**Comment by noraabiakar** [comment]
Discussed in #836
