### ISSUE TITLE
CI support using Jenkins on CSCS systems [6].

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#436]
CSCS has unofficial Jenkins support that can interact with Github.

We should add Jenkins support for testing Arbor on:
1. daint-mc  (Broadwell AVX2)
2. daint-gpu  (P100 GPU)
3. tave (KNL AVX512)

**Comment by thorstenhater** [comment]
Is this solved by `bors`?

**Comment by thorstenhater** [comment]
Subsumed by bors and GithuB CI.
