### ISSUE TITLE
Documentation and name tidying of range utilities

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#50]
Point estimate: 4
Feature: #65 

The functionality and semantics of our range-like utilities are under-documented and thus hard to use for anyone who isn't the author of the range code (ahem). We also have some inconsistencies in the names of some of these utilities and classes which should be resolved.
- Document concepts and semantics of range-related code.
- Consider how to best rename/renamespace the code for clarity and consistency from the user perspective. Implement.
- Document naming, namespace conventions.

**Comment by halfflat** [comment]
When C++20 becomes a viable target, we can switch our range-like code to standard library versions.

**Comment by thorstenhater** [comment]
We are -- in my eyes -- too close to C++20 to warrant the effort.
