### ISSUE TITLE
Optimise spike walking

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#502]
The spike walk is a currently serialised, and for small cells (i.e. cells that run much 10-100x faster than real time) it becomes the main bottleneck.

For example, when running the artificial benchmark on daint-mc with the following parameters:

```
    "num-cells": 50000,
    "duration": 20,
    "fan-in": 10000,
    "min-delay": 10,
    "spike-frequency": 20,
    "cell-overhead": 10
```

with the following command

```
srun -n2 -c18 --hint=nomultithread ./example/bench.exe test.json
```

gives the following profiler output

```
model-run                       5.657        1886.162           0.843

_p_ REGION                     CALLS      THREAD        WALL       %
_p_ root                           -      16.437       0.913   100.0                                     
_p_   communication                -      11.402       0.633    69.4
_p_     enqueue                    -       6.163       0.342    37.5
_p_     walkspikes                 5       5.236       0.291    31.9
_p_   advance                      -       5.035       0.280    30.6
_p_     bench                      -       5.026       0.279    30.6
```

`walkspikes` is serial, unlike the `enqueue` and `bench` operations, which are parallelized over all threads.

The reason that it requires 5 seconds is because the operation of `push_back` each event onto the `pending_events_` vector for the target cell is not cache friendly (we have 25,000 queues on each rank, which are being chosen at random to write into because of the random nature of the network).
However, the deeper problem is that it is not parallelised: the walkspikes would have to be about 20x faster to overlap fully with the `advance` and `enqueue` work.

**Comment by bcumming** [comment]
The benchmark above was running with 2 ranks on 1 node. If I vary the number of ranks, I get the following scaling for the `walkspikes`:
```
ranks   walkspikes  speedup                                
 2      5.147        1.00
 4      2.606        1.98
 9      1.193        4.31
18      0.580        8.87
36      0.282       18.25
```
It scales close to perfectly. Each MPI rank is walking over the same number of spikes in each case, yet generating proportionally fewer events as the number of ranks increase.

Because all ranks are on the same node, I don't think that this looks like an L3 cache effect (because they all share L3).

So, probably L2? Which is good and bad news: good because it is amenable to parallelization (no shared L3 bottlneck), and bad for micro optimizing the event writes (because L2 doesn't give us much wriggle room).

**Comment by halfflat** [comment]
Does indeed look like L2! We should run perf and get some stats.

**Comment by noraabiakar** [comment]
Duplicate issue #510 
> Parallelize and improve the cache friendliness of the spike walking -> post-synaptic spike event part of the exchange task.
This is non-trivial, because the obvious parallelization strategies are worse for cache (loading more cache lines per event write).
