### ISSUE TITLE
Consolidate pretty printers

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#514]
We've got a number of string-formatter/print helpers in the code, generally but not exclusively used for logging or debugging purposes. These should be unified.

In terms of interface, I suggest we use something like the proposed C++ formatting as a guideline.

Merging `modcc` print helpers with the `arbor` ones though may be problematic, as the most straightforward way of doing this would introduce a dependency between the two source trees which is not especially desirable.

**Comment by thorstenhater** [comment]
This is part of #1451, closing for duplication
