### ISSUE TITLE
Rename range utilities

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#544]
We've called our various views and filters by one set of names, but these are different from the names used in the proposed ranges TS. We should align our names to those names in order to reduce confusion.

**Comment by halfflat** [comment]
No reason why we can't pick one at a time.

* `span`, for example, looks now to be a class in the standard library in C++20 (it's a pointer+size wrapper), and we should probably move to something like `iota` for the counting functionality, or `indices` for the 0..n-1 counting to match the ranges library choice.

* The ranges TS uses 'Range' where we (in comments) use 'Sequence'. It would be clearer if we used the same meanings of Range, BoundedRange and View. What we call a `range` object is in the library an `iterator_range`, and what we call `make_range` is there, `all`.

And so on. We can take one off the list every now and again as we go along.

**Comment by thorstenhater** [comment]
I'll close this: It's quite a bit of work that should be done once we consider formally using C++20.
