### ISSUE TITLE
In-library support for hashing pseudo RNG

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#558]
Arbor is currently PRNG agnostic, and we may well wish it to remain so, but there are certainly advantages in using a hashing PRNG such as Random123 in distributed simulations.

As hashing PRNGs are not available as part of the standard C++ library, we can encourage and even privilege their use through providing an interface to one or more implementations through the Arbor library itself. Once in place, we may find the advantages sufficiently compelling so as to make them the only source of in-library pseudo random numbers for random processes in mechanisms or cell group implementations.

Tasks:
* Evaluate and pick one or more hashing PRNGs to wrap within the library. Depending on IP concerns, we may or may not be able to simply include the original source, and we should be wary of reimplementation of algorithms without also a very sturdy set of unit tests.
* Make at least a demo of a Poisson spiking cell or event source that uses same.

**Comment by noraabiakar** [comment]
Partially addressed by #944 - Random123 has been added to Arbor

**Comment by thorstenhater** [comment]
I consider this done. Feel free to re-open.
