### ISSUE TITLE
Prototype new mechanism representation language

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#559]
There is a longer term goal to replace NMODL as the primary means of mechanism description with a description language that is
* less ambiguous than NMODL,
* able to represent (a subset of) LEMS,
* is amenable to programmatic transformation, with the promise, ultimately, of run-time code generation via LLVM or similar.

The first part of this process is to prototype an intermediate representation. For ease of experimentation, this prototype will:
1. have an S-expression representation,
2. only support single-assignment representations of dynamics and state initialization,
3. only support density mechanisms without event handling or state transitions.

The task will be broken up into three parts:
1. Run-time/interpreted representation with explicit Euler time-stepping (#569).
2. Add code generation for C++ and/or LLVM IR for compile-time solver generation.
3. Add support for other integrators, specifically backwards Euler for linear ODE systems.

**Comment by halfflat** [comment]
Updated issue to reflect current approach/status.

**Comment by thorstenhater** [comment]
We have a prototype and more issues. Closing this to avoid duplication.
