### ISSUE TITLE
Trial `symengine` in `modcc`

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#57]
How easy to incorporate or robust is [symengine](https://github.com/symengine/symengine)?

Let's trial it for the computation of the derivative in the `cnexp` processing in `modcc`.

**Comment by vkarak** [comment]
I have just had a look at it. It is not very well documented, I've gone through some of the unit tests to understand how it works. It seems to support a wide range of mathematical expressions. I suppose you  mean constructing the expressions AST using this library or also adopting its front-end syntax for expressions?

**Comment by halfflat** [comment]
Yep, considering it for the AST expression manipulation and algebra. May well fall under task #64.

**Comment by halfflat** [comment]
Conclusion: we do things with AST manipulations now, and will rejig everything when arblang lives.
