### ISSUE TITLE
Use fixed gid in event_generator

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#581]
There are some `event_generator` instances, e.g. `explicit_generator` that can return a sequence of events that have different `gid`.

However, `event_generators` are always used in a "cell-local" context, where the `gid` is that of the cell to which they are attached.

It would simplify event generators significantly if they were refactored to be a wrapper around a `gid` and a `sequence` of time points.
* type erasure would only be on the `sequence`, without a second level of erasure on the `event_generator`.
* construction would always be `gid` + `sequence`.

**Comment by bcumming** [comment]
What I am proposing is to make what the current `schedule_generator` the `event_generator` implementation.

**Comment by noraabiakar** [comment]
This has been partially resolved by #1467, but is also related to #1488.

**Comment by noraabiakar** [comment]
This is no longer relevant since #1504 was merged.
