### ISSUE TITLE
Full-cell sampling for mc_cell

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#589]
LFP use cases look like they will want to sample membrane voltage or current at the same spatial resolution as the simulation. Setting up probes one for each compartment will comprise a lot of redundant data and make for very long sampler event queues.

Proposed solution:
1. Extend mc_cell probe address to also admit a cell-wide 'vector' sampling.
2. Provide a new sample representation for vector samples that contain the multiple values per time-point.
3. Provide a mechanism for associating the indexed values in the returned vectors with morphological locations (segment index, normalized position) — one option is to have this be supplied directly in the sample representation provided to sampler callbacks.
4. Implement wide-sampling for cpu and gpu back-ends.

I think the only unclear bit is part 3. As we're trying to keep separate the mechanics of the FVM discretization from the morphology specification, we're faced with a trade-off:
* Do we bake in knowledge of the discretization into the `mc_cell` class, allowing this information to be queried from the user code when recipes construct them, for later reference by samplers? This is unattractive from a design point of view, as it increases both coupling in arbor and complexity in user code.
* Do we add sample location information to the information passed to the sampler from `mc_cell_group`? A slightly more generic approach could replace the `tag` data sent to samplers with a pointer/reference to probe meta-data, comprising per-probe constant data including the tag and per-cell-group metadata such as cell gid and morphology info in the `mc_cell` case, wrapped in an `arb::any`.

I'm currently leaning towards the second option, especially as it would simplify sampler usage from the user side (they would no longer have to maintain per-probe metadata themselves for the benefit of samplers).

**Comment by bcumming** [comment]
I agree that baking knowledge of the discretization in the `mc_cell` would create discretization-specific coupling.
At some point in the nearish future we need to nail down our morphology representation.

**Comment by halfflat** [comment]
Okie doke. Going with option b.

**Comment by halfflat** [comment]
Pausing development on this for a bit: turns out our current measurements don't actually capture the trans-membrane currents. Fixing some of the numerical stability issues will also change how we recover the currents, so let's leave this until after that.
