### ISSUE TITLE
test_exception unit tests fail on OS X

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#603]
The unit tests fail on OS X with Apple Clang 9 (gcc 6 passes).

```
[----------] 14 tests from test_exception
[ RUN      ] test_exception.single_task_no_throw
[       OK ] test_exception.single_task_no_throw (2 ms)
[ RUN      ] test_exception.single_task_throw
libc++abi.dylib: terminating with uncaught exception of type error
./scripts/travis/build.sh: line 65:  2970 Abort trap: 6  
```
Other tests in `test_exception` also crash the test runner, with the same cause: an expected `error` is not caught.

**Comment by bcumming** [comment]
This isn't a solution, but it is pointing to the source of the problem.

For the case of `single_task_throw`, I annotate the `task_group` implementation with some printfs:

```
      // wait till all tasks in this group are done
      void wait() {
+         std::cout << this << ": wait loop" << std::endl;
          while (in_flight_) {
              task_system_->try_run_task();
          }
          if(auto ex = exception_status_.get()) {
+             std::cout << this << ": there was an error" << std::endl;
              try {
+                 std::cout << this << ":     rethrow " << std::endl;
                  std::rethrow_exception(ex);
              }
              catch (...) {
+                 std::cout << this << ":     error rethrowing... " << std::endl;
                  throw;
              }
          }
      }

      // Make sure that all tasks are done before clean up
      ~task_group() {
+         std::cout << this << ": destructing" << std::endl;
          wait();
      }
```

To get the following output:

```
0x7fff5e56b580: wait loop
0x7fff5e56b580: there was an error
0x7fff5e56b580:     rethrow
0x7fff5e56b580:     error rethrowing...
0x7fff5e56b580: destructing
0x7fff5e56b580: wait loop
0x7fff5e56b580: there was an error
0x7fff5e56b580:     rethrow
0x7fff5e56b580:     error rethrowing...
libc++abi.dylib: terminating with uncaught exception of type error
Abort trap: 6
```

When we rethrow the exception, the destructor of `task_group` is called, which in turn calls `wait`... which determines that there is still an exception, despite calling `get()` in the first `wait`.

**Comment by bcumming** [comment]
Final hint: everything works if we ensure that the `exception_ptr` is NULLed before returning:
```
 117         std::exception_ptr get() {
 118             error_.store(false, std::memory_order_relaxed);
 119             auto ex = exception_;
 120             exception_ = nullptr;
 121             return ex;
 122         }
```

**Comment by bcumming** [comment]
Using `std::move` does not guarantee that `exception_` will be left null.

**Comment by halfflat** [comment]
I feel we should not be `wait()`ing or rethrowing in the destructors: in WIP patch, I have `~task_group()` call `std::terminate()` if there is a `run()` without a subsequent `wait()`, analogous to the behaviour of `std::thread::~thread()` when the thread is neither joined nor detached.

Further testing/fixing from me is on hold while I arrange a working development environment with libc++.
