### ISSUE TITLE
Parallelise construction of cell groups with many cells

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#634]
Model building parallelises cell group construction over cell groups.
Models with few cell groups with many cells in each group don't benefit from this optimization.
The most extreme example of this is a model on the GPU with a single cell group with thousands of cells.

There are two parts to the fvm lowered cell construction:
* 60% of time is in getting the vector of cell groups from the recipe
* 40% of time is then spent building the lowered back end cell group data structures

The 60% in recipe querying is trivial to parallelise, however the remaining 40% is considerably more difficult.
So at least we should parallelise the recipe querying, which would require making the task system available to the lowered fvm cell.

**Comment by halfflat** [comment]
The discretization step (part of the 40%) is serialized, but I think making this more parallel will be fairly straightforward if we make a concatenation function for `fvm_mechanism_data` and `fvm_discretization` objects — this is mostly appending vectors and offsetting segment or cv indices accordingly.
