### ISSUE TITLE
Clean up fine GPU solver

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#643]
Refactor the GPU fine matrix solver:
* move more code into `forest.cpp` and expose minimal interface.
* remove deprecated parameters from fine matrix kernels.
* investigate rumours of alleged branch limit issue.

**Comment by brenthuisman** [comment]
See also #644

**Comment by thorstenhater** [comment]
I'll close this; the corresponding file have been largely untouched for quite some time.
