### ISSUE TITLE
Move thread/rank/gpu device wrangling out of core arbor library

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#647]
Based on discussion between @bcumming and @halfflat:

In terms of separating concerns and code hygiene, we're thinking it would be cleaner to have the environment inspection for data such as GPU ids, thread counts, core counts, etc. and their default assignments to allocated resources in a context be separate from the core library. E.g.

1. Application uses non-core routines to determine operating environment, including number of available or desired threads.
2. Application creates a context based on that determination.

The motivation for this is the problem of determining a sane default allocation of GPUs to ranks in the instance that multiple ranks on a node may see multiple shared GPUs — while we can pick a reasonable guess as to an appropriate assignment of resources, this is ultimately going to be very dependent upon the system configuration, batch environment, etc. etc. and we shouldn't hard code any such guess into Arbor itself.

Options:

1. We move this stuff into `sup`, and install it in parallel with `libarbor.a`. Downsides:
    * There are things in sup which are convenient for our examples and tests, but are otherwise fairly specific to our needs.
    * `sup` includes a JSON library dependency which we should avoid baking into an install.
    * Installing `sup` reduces our freedom in putting useful test/example helper code in there, and adds a documentation burden.

2. We move this into `sup`, and _don't_ install it. It then acts as example code for how an application might want to do this sort of resource query, but we're not providing any installed code to do it.

3. We make another library, e.g. `arbordrv` or `arborenv` (I dunno, we have options here) that does this resource wrangling and maybe some other related convenience code. This gets installed, and `sup` remains our personal playground.

My personal preference is option 3.

**Comment by halfflat** [comment]
Reopening for the arbor sup library public/private split.

**Comment by halfflat** [comment]
Going through the `sup` includes (as proxies for the include file and corresponding sources):

*Definitely install*
* `affinity.hpp`: used for `thread_concurrency()` — could be rolled all into `concurrency.hpp`.
* `concurrency.hpp`
* `gpu.hpp`: needs a better name though.

*Maybe install*
* `with_mpi.hpp`:  convenient convenience wrapper.
* `scope_exit.hpp`: used by `with_mpi`.
* `io_util.hpp`: `mask_stream` is used in all our examples to simply MPI output; `open_or_throw` probably not necessary. If installed, would split out `mask_stream` and change header name,

*Shouldn't install*
* `tinyopt.hpp`: maybe consider installing replacement/extension if it simplifies nsuite examples.
* `strsub.hpp`
* `spike_emitter.hpp`
* `path.hpp` and `glob.hpp`
* `json_params.hpp`
* `json_meter.hpp`

Thoughts?

If this is a sound division, then I think we can call the installed library `arborenv` and use a corresponding top-level namespace `arbenv` or `arborenv`, keeping `sup` internally for everything else.

**Comment by bcumming** [comment]
*Definitely install* looks good.

*Maybe install* remove `ioutil.hpp`, because that  is easy enough to implement with the usual `if (rank==0)` logic, and it isn't really something Arbor has any right to export!

*Shouldn't install* I agree with them all. I would go further and say that `spike_emitter.hpp` should be expunged completely, because it is as ugly as home made sin.
