### ISSUE TITLE
Validation of basic models

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#66]
There are currently some discrepancies between our results, the results of NEURON and the results of our numeric validation models.

The nature of these discrepancies needs to be determined, and if necessary, the discrepancies addressed, so that we can have confidence in our implementations.

Concretely:
* NEURON single-compartment H–H model converges to a close, but distinct solution to that given by our existing Julia ODE implementation, and that of `nestmc`.
* We cannot currently test convergence in space well for multi-compartment models in `nestmc`, as we have only a first-order in time solver implemented, and time discretization errors dominate.

Tasks may include:
* Investigating numeric behaviour of a simplified single compartment model across NEURON and `nestmc`.
* Maybe implement an adaptive or higher-order integrator.

**Comment by bcumming** [comment]
Implementing a higher-order integrator would have additional benefits
* it would improve the quality of our software!
* it would exercise our design

**Comment by halfflat** [comment]
Migrated to GitHub project; keeping issue open for comments, milestone info etc.

**Comment by bcumming** [comment]
It isn't easy to see what the "solved" state would be for this issue. I think it can be closed, and replaced with issues that address specific convergence tests, or new solution methods (many such tickets already exist).
