### ISSUE TITLE
Unit tests for GPU assignation code in sup

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#666]
In the interests of getting functionality into the code base in advance of python wrapper work, PR #659 was merged without any corresponding unit tests, and we really ought to aim to maintain our unit test coverage.

Task is to provide the minimal refactoring required to expose the non-environment-dependent functionality introduced in this PR for testing, and provide the tests. This would correspond to the writing/parsing of UUIDs and the algorithm that allocates GPUs from the rank-partition list of GPU ids.

**Comment by brenthuisman** [comment]
Lib is now `arborenv`

**Comment by thorstenhater** [comment]
This code has been used for about two years now and is battle hardened by now.
