### ISSUE TITLE
Python infrastructure merge

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#667]
ZAdding the Python wrapper can be broken into two steps:
1. The Python infrastructure (directory structure, python binding interface, CMake integration, documentation format, etc)
2. Wrapping the individual parts of the Arbor public API in Python and documenting them.

To avoid a messy merge process, these steps will be performed separately, so that the discussion about the infrastructure can be separated from discussions about the python interface for each component.

## TODO list

- [x] Directory structure
- [x] Unit tests
- [ ] Documentation
- [x] Doc strings
- [x] Error handling (exceptions)
- [x] CMakeLists (compilation options, pybind11 CMake integration)

**Comment by akuesters** [comment]
Created PR #668 to discuss after holiday (back on 21st January)
