### ISSUE TITLE
Hard coded CUDA libraries in exported CMake package

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#678]
In order to work around the transitive CUDA language dependency imposed by CMake 3.13 and before, in our generated `arbor-config.cmake` we remove CUDA from the `IMPORTED_LINK_INTERFACE_LANGUAGES` property of our installed libraries, and add the required CUDA run-time libraries manually (see [CMake issue #18614](https://gitlab.kitware.com/cmake/cmake/issues/18614#note_485632).)

However, we add the libraries by their found paths, making the installed arbor brittle: if the location of the CUDA libraries changes (e.g. after an update or reinstall), linking against arbor and its declared dependencies will fail.

If we do not use an absolute path, then we require that arbor-using projects correctly set their library search path to find the CUDA libraries, even if that project itself does not use CUDA.

We could dynamically search for the CUDA libraries in the installed `arbor-config.cmake`, with the caveat that this might find a _different_ version of CUDA, depending on the environment of the arbor-using project, which would be hilarious.

Maybe add the CUDA library path to the `INTERFACE_LINK_DIRECTORIES` property, and add the required CUDA libraries by name rather than path?

**Comment by thorstenhater** [comment]
This issue is no longer relevant given the upgrades/changes in CMake's CUDA support. Closing for now.
