### ISSUE TITLE
Rename `mc_cell` class and `cable1d_cell` kind to `cable_cell`

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#701]
For consistency and clarity, let's just call both the class and the kind 'cable_cell'.
* Rename enum value in `cell_kind`.
* Rename associated classes and source files for `mc_cell`.

**Comment by noraabiakar** [comment]
I propose to rename the enum values in `cell_kind` to the following:
```
enum class cell_kind {
    cable,
    lif,
    spiking,
    benchmark, 
};
```
