### ISSUE TITLE
SONATA support (part II)

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#721]
1) Parse all relevant information from HDF5 files including: 
- cell populations
- cell ids
- cell types (type ids - keys in csv file)
- cell groups and parameter overrides  (if available)
- edge populations
- edge types (type ids - keys in csv file)
- edge ids
- edge sources and targets
- edge groups and parameter overrides (if available)

Parse some information from CSV files: 
- node types
- which population each node type belongs to
- edge types
- which population each edge type belongs to
- all available and relevant edge type information

This should include wrapping up the HDF5 and CSV readers in helpful structures

2) Use parsed information to create recipe, mainly: get_cell_description()  and connections_on()

**Comment by halfflat** [comment]
Complete in prototype https://github.com/noraabiakar/arbor_sonata
