### ISSUE TITLE
Verify/support large Akemann and Knoepfel sodium channel mechanism

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#731]
The resurgent sodium channel model of Akemann and Knöpfel 2006 ([doi:10.1523/JNEUROSCI.5204-05.2006](https://dx.doi.org/10.1523/JNEUROSCI.5204-05.2006)) comprises a real world example of a large, linear kinetic scheme.

The corresponding mod file is [available on ModelDB](https://senselab.med.yale.edu/ModelDB/showModel.cshtml?model=80769&file=/AkemannKnopfelPurkinje_cell_model/Narsg.mod).

Tasks:
* What enhancements, if any, are required to support this model in `modcc`?
* How does the compiled mechanism perform numerically? Does the symbolic implicit Euler solution that `modcc` generates experience any overflow issues due to the large size? Do we need to renormalize against the `CONSERVE` term to maintain the invariant?

**Comment by noraabiakar** [comment]
I tested the `Narsg` mechanism linked above, it can be compiled with `modcc` and it runs on a simple single cell model without any problems. All the required features were added when we were trying to support the purkinje cell mechanisms (specifically in: #840, #829)
