### ISSUE TITLE
Allow specification of mechanisms on partial sections.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#732]
The current API associates density mechanisms with the entirety of an unbranched section. In order to support e.g. SONATA, we will need to associate mechanisms with subsections.

* Extend API to support start and end positions within an unbranched section for a density mechanism.
* Use this information in the FVM discretization to set the corresponding weight values.

**Comment by halfflat** [comment]
We'll incorporate this with the new morphology spec and API.

**Comment by bcumming** [comment]
Fixed in #941
