### ISSUE TITLE
Augment morphology representation to support SWC lables.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#733]
(Note: a more thorough revamp of morphology representation is underway.)

For SONATA support, density mechanism will need to be associated with subsets of the morphology tree according to SWC labels. While issue #732 concerns itself with the mechanism association API, there must also be a way of keeping track of which parts of the tree correspond to the given SWC labels.

Noting that this will be revised with the new morphology API, proposal is:
1. Represent connected, unbranched subsets of the tree by a start and end location, with location given by section index (NB: we call these 'segments' in Arbor, but this is not consistent with NEURON terminology, and we should change the name to be less confusing) and proportional proximal position (0.0–1.0).
2. When reading SWC, also supply a table mapping SWC labels to lists of subsets as described in (1).

**Comment by halfflat** [comment]
Going to shelve this one; we'll use the new morphology infrastructure which is well underway.

**Comment by bcumming** [comment]
The new morphology infrastructure addresses this.
