### ISSUE TITLE
Hang with sequential use of `arb::gpu::reduce_by_key` on V100/CUDA 10.1

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#736]
In at least one circumstance, calling `reduce_by_key` twice in succession within a kernel causes the kernel to hang. This behaviour is exhibited on a V100 with CUDA 10.1.

This is triggered in the GPU code with the stability correction.

* Try to isolate this in a unit test.
* Fix it.

**Comment by halfflat** [comment]
It looks like the problem lies in the `while` loop that does the reduction; the `get_from_lane` function can request data from a thread that is not participating in the `shfl`.

**Comment by halfflat** [comment]
There's some test code in https://github.com/halfflat/arbor/tree/bugfix/reduce-by-key-v100 `test_reduce_by_key.cu` that exercises the problem.

**Comment by bcumming** [comment]
The problem can't be reproduced on older GPUs.

**Comment by bcumming** [comment]
Once this problem has been fixed, there will still be a performance issue: the key range calculation is now calculate twice (once for current, once for conductance). I can extend the interface to `reduce_by_key` to perform reduction for more than one array using the same index. In fact, I think that an old version of this that I wrote for another project had exactly this feature.

**Comment by halfflat** [comment]
Sounds very useful!

**Comment by bcumming** [comment]
I have a fix here:

https://github.com/bcumming/arbor/blob/gpu-reduction/arbor/backends/gpu/reduce_by_key.hpp

It works for the "reduce twice" test case.

I am still a bit uncertain on whether I can rely on the `__activemask` call on line 57. It certainly requires that the constructor for `run_length_type` is called by all active threads. But I don't know if calling it immediately after calling `__syncwarp` ensures that all active threads are used... if it doesn't then we have to pass the mask in from outside, which would require additional code generation in modcc.

**Comment by halfflat** [comment]
The cuda docs say we shouldn't rely upon `__activemask` behaving that way - probably because we can't be sure the calling context isn't within a branch - but in practice we should be okay, I think, given that the kernel is only called from the wrapper.

**Comment by halfflat** [comment]
Looking at the amended code, can there not be the situation where a high lane id has a high width, meaning its source lane in the shuffle wraps to a low lane, but that low lane has a small width and has fallen out the loop?

**Comment by bcumming** [comment]
My solution needs work.

There need to be two masks:
1. the mask currently used to select all threads in the current warp involved in reduction, used for the shit+ballot used to determine the range of threads that share the same key.
2. a second mask that selects the threads with the same key, used in the reduction loop.

The second mask can be computed using 2 shifts + 1 bitwise-and. However, it might be time to consider precomputing the key range information during setup. This could be encoded in a single 32-bit value per synapse.

**Comment by halfflat** [comment]
An alternative would be to avoid divergence in the accumulation loop: each thread participates in each shuffle, but will ignore the result if the loop iteration is past their own limit.
