### ISSUE TITLE
Poisson spike train generator

### ISSUE THREAD

**Issue by w-klijn** [arbor-sim/arbor#75]
A large number of neuro scientific models have a source of random spikes:  We do not model the whole brain and the activity of the non-modeled neurons is typically injected as a uncorrelated poisson spike train on each modeled neuron. The typical rate of spike generation for this use-case can be in the order of 20000Hz or higher.

In NEST this feature is implemented as a node that generates independent spike trains to each synapse connected. Optimizing by generating the spikes on the target node it self. 
http://www.nest-simulator.org/py_sample/sinusoidal-poisson-generator-example/
![poisson generator](https://cloud.githubusercontent.com/assets/15797269/20210686/08f65eee-a7fb-11e6-83be-3fe03a568d10.png)

 Introduction:
D. Heeger. "Poisson Model of Spike Generation" 2000 Doi: 10.1.1.37.6580

Possible features of the spike generator, (cheap compared to the implementation of the basic version)
- Bursting behavior (With probability P a burst of spike is inserted)
- Refractionary period ( A neuron is silent after spike, cause science)
- Renewal process / Gamma distribution
- Sinusoidal rate change

Observations based on 'current' version of code:
add_artificial_spike() 
- expects an existing/valid source neuron
- Can only insert spikes for the next time slot (looking at the implementation)

class model {}
- Only supports a single cell type (not a possible 'fake' spike generator and HH)

**Comment by halfflat** [comment]
The DOI doesn't appear to be attached to anything; however the technical report can be found at: http://www.cns.nyu.edu/~david/handouts/poisson.pdf

**Comment by halfflat** [comment]
Another generation option to consider Markov-modulated Poisson processes, to capture larger time-scales of high versus low activity.

**Comment by bcumming** [comment]
Depends on #106

**Comment by bcumming** [comment]
Support for proxy cells and event generators that generate spike input  was added with `spike_source_cell` and `event_generator` features of Arbor some time ago.
