### ISSUE TITLE
Common generation of __repr__ and __str__ in Python wrapper

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#753]
The `__repr__` and `__str__` attributes of wrapped types are the same, which may or may not be a good thing. The C++ functions that generate the string representations are also in different locations, some are inline where the wrappers are defined, and others are in `python/strings.{hc}pp`

We should decide the following:
1. a common way to format the `__repr__` and `__str__` strings, preferably based on standard/common/accepted Python practices, if they exist.
2. a common location and format for where and how the C++ functions that generate the string representations are defined.

**Comment by akuesters** [comment]
see #774
