### ISSUE TITLE
Python wrapper: tests

### ISSUE THREAD

**Issue by akuesters** [arbor-sim/arbor#769]
Add tests to `python/test`:

- [ ] test_recipe
- [x] test_domain_decomposition
- [ ] test_cells
  - [ ] test_cable_cell
    - [ ] test_segment
    - [ ] test_synapses
  - [ ] test_lif_cell
  - [ ] test_benchmark_cell
  - [ ] test_spike_source_cell
- [x] test_probes
- [x] test_spikes

**Comment by thorstenhater** [comment]
Done.
