### ISSUE TITLE
Ionic currents in NMODL are presented with inconsistent units

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#793]
The Arbor internal representation of a current density is in A/m², while for NEURON modules, the value is in mA/cm². This difference is handled correctly when currents are accumulated, as density mechanisms have their weight contribution scaled by 10.

When a mechanism reads an ionic current, however, they are presented with the value that Arbor stores internally, which is implicitly in Arbor's units, not NEURONs. When these currents are used to compute e.g. concentration updates in a mod file, the rates computed by that mod file will be out by a factor of 10.

Possible fixes:
* We change the internal representation of currents to mA/cm² — this is a right pain, as it requires the correct conversion factor to be inserted in all the different voltage computation matrix implementations, not to mention all the documentation.
* `modcc` adds a 0.1 scaling term to reads of external ion current variables, to match NEURON units. The downside to this is that it is asymmetric: the generated code will read values in A/m² but write them in mA/cm².
* All ionic current values are scaled by 0.1 in the back-end before any mechanism state updates are called. Mechanisms then see consistent (NEURON) units, but it's another touch-all-the-data processing step inside the integration loop.
* We make mechanisms see consistent Arbor units (i.e. A/m²), and have the generated code from `modcc` scale by 0.1 on read and by 10 on update. This adds essentially another multiplication to each mechanism kernel described by NMODL, but has the benefit of consistent units across both the internal representation and the (implicit) mechanism API.
* We throw out readable ionic currents and make everyone use species fluxes instead. This allows people to deal with flows of uncharged species! But also is much more invasive, with almost every mod file needing to be adjusted. We'd also, for good or ill, be baking in values for the Faraday constant; this though, at least, could be specified as a run-time parameter and applied consistently across mechanisms, avoiding the situation where different mechanisms may have differing values for this constant.
* Or  as a variation on the above, we: make the internal state and mechanism interface deal in fluxes and currents; make `modcc` convert fluxes to and from currents automatically in generated code, using a fixed value for the Faraday constant.

**Comment by halfflat** [comment]
Happy to debate this, but I'm going to push the option that mechanisms see Arbor units (i.e A/m²) , and NMODL sees NEURON units (mA/cm²), with modcc adding the conversions when generating mechanism code.

**Comment by bcumming** [comment]
Fixed in #800
