### ISSUE TITLE
NMODL mechanism-initialized ionic currents are not weighted

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#798]
Demo with unit test: https://github.com/halfflat/arbor/tree/bugdemo/ionic-current-init

Initialization of ionic currents iX for an ion X do not get multiplied by the mechanism weights. This gives a factor of 10 error in scalar and GPU implementations, and a SIMD-width x 10 fold error in vector implementations.

**Comment by halfflat** [comment]
Oops, forgot to commit before push *ahem*. Now the link should be correct.

**Comment by bcumming** [comment]
#800
