### ISSUE TITLE
cmake doesn't check for python headers

### ISSUE THREAD

**Issue by apeyser** [arbor-sim/arbor#812]
No python header check when python is on in cmake

**Comment by bcumming** [comment]
Can you give some more details about this issue?

The relevant `CMakeLists.txt` for checking Python is in the `python` path:
https://github.com/arbor-sim/arbor/blob/master/python/CMakeLists.txt

We delegate looking for Python to pybind11, which is configured by including its path on line 15.

**Comment by bcumming** [comment]
The pybind11 packaged tests for all the Python accessories.
