### ISSUE TITLE
Make the soma a separate CV

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#814]
Currently, the discritization code splits up the CVs along a cell in a way that makes the soma's CV extend to include a part of any dendrites extending from it: 
```
CV: |  0        |  1  |  2  |  3  |4|
    [soma (0)][    segment (1)      ]
```
This causes some problems in verifying performance, especially when comparing to Neuron. When we measure the voltage at the soma, we are measuring the average voltage of the first CV, which includes parts of the segments branching from the soma. 

To fix the issue, we can treat the soma in a special way, giving it a dedicated CV. 
The new discritization would look like this: 
```
CV: |  0      |1|  2  |  3  |  4  |5|
    [soma (0)][    segment (1)      ]
```

CV0 represents only the soma. To keep the rest of the discritization unaffected, we would need to take care of how we represent CV1: it would have half the physical length of the a regular CV (2,3,4); CV1 would belong to segment (1), but the proximal CV of the segment would be CV2.

**Comment by halfflat** [comment]
Resolved in #816.
