### ISSUE TITLE
modcc: parse and process COMPARTMENT statements 

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#838]
Compartment statements are only relevant in KINETIC blocks and have the following format: 
```
COMPARTMENT volume {state_1 state_2 . . . }
```
According to the Neuron Book: 
`volume` only multiplies the `d(state_x)/dt` of the equivalent differential equations.

**Comment by bcumming** [comment]
Can you share the mechanism that requires this?

**Comment by noraabiakar** [comment]
This is from `cdp5.mod` from the purkinje model.

**Comment by noraabiakar** [comment]
The Backward Euler equation is derived as follows: 

Let's say the `state_x` variables are represented by the vector `s` and the coefficients of the right-hand side of the differential equation are coded in the matrix `M` such that the original differential equations are represented by: 

```
ds/dt = M*s 
``` 
When we add the `COMPARTMENT` statement, we multiply the left-hand side by `volume_x` of the corresponding state variable. Let's say the `volume_x` variables are represented by vector `v`. The differential equation becomes: 

```
v*ds/dt = M*s
```
or 
```
ds/dt = (v^-1 * M)*s 
``` 
where `v^-1 = [1/v1, 1/v2, ... 1/vn]`

if we apply implicit Euler, we get: 

```
(I - v^-1*M*dt)*s' = s
``` 
So, the problem turns into a system of equations . 

Example: 
```
COMPARTMENT ca {a}
COMPARTMENT cb {b}
a <-> b (f, r)
```
becomes: 
```
[1 + (f/ca)*dt]*a  + [  - (r/cb)*dt]*b = a_prev
[   -(f/ca)*dt]*a  + [1 + (r/cb)*dt]*b = b_prev
```
This system will still satisfy any `CONSERVE` statements associated with the kinetic scheme
