### ISSUE TITLE
Arbor/nsuite integration

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#849]
With some added support on the NSuite side, replace the current validation tests in the Arbor tree with an invocation of the NSuite validation tests.

Once NSuite has the required bits and bobs:
1. Set up a copy of NSuite in the Arbor build tree as a configure-time option.
2. Add a new target that will generate the appropriate env script for NSuite to match the built Arbor library (and in-tree includes), and then invoke the NSuite install and validation process.

Once this is working, migrate any required existing validation tests to NSuite equivalents, and then remove the tests from Arbor.

**Comment by brenthuisman** [comment]
#1316

**Comment by thorstenhater** [comment]
This can be added to (Github) CI/CD, but I would want to have a version of NSUITE able to run with an installed version of arbor.

**Comment by thorstenhater** [comment]
Hey,

we have turned this inside out, NSuite now has CI to build Arbor master.
