### ISSUE TITLE
Zero radius soma for soma-less cells causes bad discretization

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#858]
With the new implementation for discretizing cells with a dedicated CV for the soma, the trick of using a zero-radius soma for soma-less cells no longer works.

With NewMorpho the Wonder Dog, this won't be a problem. But as an interim solution, we should check for the zero-radius case and modify the discretization accordingly.

**Comment by bcumming** [comment]
Fixed in #941
