### ISSUE TITLE
`net_send` and `net_event` support

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#86]
These keep popping up in different examples, so they have to be added in some form.

Two questions
1. what is the difference between the two?
  * `net_send(d, w)` will send an event to "self" at `t+d`.
  * `net_event(t)` sends an event over any netcon that is attached to the point process that calls it.
2. how can they be implemented?
  * `net_send` should be straightforward: just push an event into the local event queue, taking care to avoid race conditions on the queue (possible complications on GPU)
  * `net_event` is a pain, because we made the naive assumption that synapses are targets, not sources of spikes/source events. We might work around this in most cases, because it might be a category mistake to allow a point process to generate "spikes" in our network model.

see #18 and #19

**Comment by bcumming** [comment]
Closing along with #19, pending future support for plasticity.

**Comment by halfflat** [comment]
Might be a bit premature: just had a chat with Robin; some of the synapses appear to have use self events.
