### ISSUE TITLE
modcc: support inlining functions containing if/else statements

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#862]
The modcc compiler does not allow inlining functions containing if/else statements. 
We can extend support to allow functions containing a single, possibly nested if/else statement as long as: 
1. Every branch of the nested if/else leads to a single assignment
2. Every if has an associated else

**Comment by halfflat** [comment]
I'm just a bit surprised by the restrictions. What is the barrier to full support for function inlining?

**Comment by noraabiakar** [comment]
The barrier is multiple statements, we don't have any of the infrastructure needed to support that in the current function inliner. I believe we can add support for multiple statements on top of this later on.

**Comment by halfflat** [comment]
Implemented in #861
