### ISSUE TITLE
Restarting simulations

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#873]
Ideally, we'd be able to run a simulation up to time <i>t<sub>1</sub></i>, muck about with the simulator state in some well-defined ways, and then continue simulation up to time <i>t<sub>2</sub></i> &gt; <i>t<sub>1</sub></i>. Such functionality will potentially be useful also for check-pointing.

Currently, calling `sim.run(t)` will always reset the start time to zero.

Considerations include the correct handling of spikes that are 'in-flight'.

**Comment by apeyser** [comment]
Also very important for integration with external processes -- robotics, other simulators, data analysis.

**Comment by halfflat** [comment]
Totally agree.
