### ISSUE TITLE
Python: wrap cable_cell

### ISSUE THREAD

**Issue by akuesters** [arbor-sim/arbor#875]
Once morphology and cable cell implementations in C++ API are finished, update and wrap missing features in `python/cells.cpp`.

**Comment by bcumming** [comment]
- [ ] primitives
- [ ] sample tree
- [ ] morphology
- [ ] regions
- [ ] locsets
- [ ] label dictionary
- [ ] mechanism descriptions
- [ ] cable_cell_local_parameter
- [ ] cable cell
  - [ ] constructor
  - [ ] paint
  - [ ] place
  - [ ] views of synapses, gap junctions, etc.

**Comment by bcumming** [comment]
Implemented in PR #948.
