### ISSUE TITLE
Modcc: fabs support

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#887]
The `fabs` function seems to be commonly used, we can add support to call the underlying C++ function. 
Edit: the `abs` token calls `fabs`, we can just extend that to accept fabs as well

**Comment by halfflat** [comment]
If `fabs` is put in, we'll probably need a signum function too to represent the derivative.

**Comment by halfflat** [comment]
I had completely forgotten that we had an `abs`. Just for compatibility, I think we should just replace `abs` with `fabs` just in case someone has used `abs` as a variable somewhere in their NMODL.

On the differentiation front, `abs` is currently regarded as 'opaque'; this can be replaced with the appropriate `signum` function, but it's really a different issue.
