### ISSUE TITLE
Bug: modcc silently fails to inline function invocation in inner block

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#89]
Demo: replace `BREAKPOINT` block in `pas.mod` with the following:
```
BREAKPOINT {
    if (1 == 1) {
        i = identity(g)*(v - e)
    }
}

FUNCTION identity(x) {
    identity = x + 0
}
```

Generated (cpu) code from `modcc` fails to compile:
```
.../mechanisms/multicore/pas.hpp:95:21: error: use of undeclared identifier 'identity'
                i = identity(i_, g[i_])*(v-e[i_]);
```

**Comment by noraabiakar** [comment]
This now fails with `current update expressions must be linear in v` due to the `if` statement

**Comment by noraabiakar** [comment]
This actually no longer fails (not sure when exactly it was fixed).
