### ISSUE TITLE
Reintialize mechanisms after ion write

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#896]
**Scenario 1:**
Assume mechanism `A` updates ion concentrations in its `INITIAL` block, while another mechanism `B` reads these ion concentrations in its `INITIAL` block.
Currently, mechanisms are initialized prior to writing any ion concentrations. So, mechanism `B` ends up reading incorrect values of the ion concentrations in its `INITIAL` block. To circumvent that, we can initialize mechanisms twice: 
- First initialize: `A` updates ion concentrations, `B` reads incorrect ion concentrations
- Write ions: `A`'s updated ion concentrations are written in arbor
- Second initialize: `B` reads correct ion concentrations. 

**Scenario 2:**
Assume mechanism `A` updates ion concentrations in its `BREAKPOINT` block, while another mechanism `B` reads these ion concentrations in its `INTIAL` block.
This will cause an error. `B` will read incorrect ion concentrations even if we initialize the mechanisms twice similar to scenario 1. 
We will have an error even if the ion concentrations are given an initial value in the arbor simulation.
There is no _simple_ way around this.

**Comment by bcumming** [comment]
We should build a dependency graph for ions. I think that we will have to assert that the graph is a DAG (i.e. acyclic). Would such a DAG be sufficient to determine a safe `nrn_init` and `nrn_current` evaluation ordering?

**Comment by noraabiakar** [comment]
I think a DAG would help us reason about things and would make sure `nrn_init()` and `write_ions()` happen in the correct order between mechanisms. For example, in Scenario A above, we would be able to call: 
```
A->nrn_init()
A->write_ions()
B->nrn_init()
```
instead of: 
```
A->nrn_init()
B->nrn_init()
A->write_ions()
A->nrn_init()
B->nrn_init()
```
Which would save a couple of function calls at initialization. I don't know whether having this transformation is worth the effort of building the DAG. I don't know if I am missing some other benefits, maybe it's useful for the revpot mechanisms? 

Using a DAG wouldn't fix Scenario B, which is a different problem related to how we initialize ion concentrations from the simulation side and when this initialization is viable.
