### ISSUE TITLE
Allow using system pybind11

### ISSUE THREAD

**Issue by sanjayankur31** [arbor-sim/arbor#915]
Hello,

Would it be possible to allow the usage of system installations of pybind11 instead of the included submodule please? For downstream distributions, that would make packaging arbor a lot easier.

(We're working on including arbor in [NeuroFedora](https://neuro.fedoraproject.org), and that's where this came up. The tracker ticket is [here](https://pagure.io/neuro-sig/NeuroFedora/issue/190))

Cheers!

**Comment by bcumming** [comment]
Thanks for the heads up.
Pybind11 is header only, so do we need to rely on the system version?

**Comment by sanjayankur31** [comment]
We can continue to unbundle it downstream, but it would be nice to have a simple way of switching to system versions (of all dependencies in general).

**Comment by schmitts** [comment]
Cf. https://github.com/arbor-sim/arbor/pull/1198

**Comment by brenthuisman** [comment]
Sebastians PR implemented this.
