### ISSUE TITLE
Version generated shared objects

### ISSUE THREAD

**Issue by sanjayankur31** [arbor-sim/arbor#916]
Hello,

Are the public shared objects/libraries meant to be versioned (ABI version)? Only a `libarbor.so` is generated, for example, not the accompanying `libarbor.so.X.Y.Z`, and I don't see any instructions in the CMakeLists files to version the shared object either. 

Cheers!

**Comment by halfflat** [comment]
Hello!

We've only been developing/testing Arbor with static libraries, and haven't as yet put any effort into properly supporting versioned shared libraries. It should produce `libarbor.a` by default, unless `BUILD_SHARED_LIBS` has been set to `ON` at configure time.

We should definitely add something to the documentation indicating that we're not supporting the generation of shared libraries yet, and make that explicit in the `add_library` commands in the various `CMakeLists.txt` files.

**Comment by sanjayankur31** [comment]
Ah, that would be good. Is there a reason we're preferring static libraries to shared ones?

**Comment by halfflat** [comment]
The main reason for using static libraries is ease of development: while we're still in early version 0.x.y territory, we are able to more freely make ABI-breaking changes without worrying that we'll break existing arbor-linked programs in the process.

Longer term, and certainly by 1.0 release, we'll be strict about versioning requirements, and consequently will be able to support shared library installation without much extra effort.

Is this going to constitute a packaging problem? We can make it a higher priority if so.

**Comment by sanjayankur31** [comment]
That makes sense. No, it isn't a problem at all. Shared libraries are preferred but we can ship static libraries too. Whenever you start providing them, I can include them in the Fedora package too.

The relevant packaging guideline is here: https://docs.fedoraproject.org/en-US/packaging-guidelines/#packaging-static-libraries
