### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#935]
Is there an Arbor logo already?

**Comment by halfflat** [comment]
We do have one, but it's hard to find as we haven't really properly published it. We should and will!

**Comment by bcumming** [comment]
I will update the docs so that they have a logo.

**Comment by bcumming** [comment]
If you want the logo while you wait for the PR to be merged, you can find it in my branch:
https://github.com/arbor-sim/arbor/blob/0de346b47b9b6dbf84293604a910f0bfbfc57a46/doc/images/arbor-logo.svg
