### ISSUE TITLE
name and functionality of `z_dist_from_soma_[lg][te]`

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#947]
These region types are very use-case specific, and it isn't clear to me if they are general enough.

There is no region named `soma` by default on cells, and the soma location is also ambiguous. Maybe these should take a specific location and extend from that location in the z direction?

**Comment by halfflat** [comment]
It's a bit misnamed — it should be `…from_root…`.

Displacement 'up' or 'down' does seem to have some plausibility as a generally useful metric, given neuron anisotropy, but we deliberately didn't make a general projection (as opposed to just the z axis) pending concrete use cases.

**Comment by halfflat** [comment]
Pending discussion with modellers, let's call this done with a rename `soma`→`root`, and revisit the set of awkwardly specific operations in a future review.
