### ISSUE TITLE
spack package

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#956]
Add an Arbor package to the official Spack.

I have a work in progress version, which when run with `spack install arbor` will build and install Arbor with python support, so that Arbor works out of the box with Python.

https://github.com/bcumming/spack/blob/arbor/var/spack/repos/builtin/packages/arbor/package.py

For the time being it only works with `master`, so we should wait until Arbor v0.3 is released before submitting with Arbor 0.3 as the first officially supported version of Arbor.

**Comment by schmitts** [comment]
With 0.3 released, are there any outstanding issues with the spack package that you know of? I'm happy to test as well before submitting to upstream spack.

**Comment by schmitts** [comment]
The check on the variant for `extends` is missing:
`extends('python', when='+python')`

**Comment by bcumming** [comment]
@schmitts, let's aim for support with v0.4 of Arbor.
How about releasing Arbor v0.4, then making a PR to the main spack repository that supports minimum version v0.4?

**Comment by schmitts** [comment]
> @schmitts, let's aim for support with v0.4 of Arbor.
> How about releasing Arbor v0.4, then making a PR to the main spack repository that supports minimum version v0.4?

Sounds good!

**Comment by bcumming** [comment]
This was merged in Spack: thanks @schmitts !
https://github.com/spack/spack/commit/bc9baac720d23b526ec91218cd15514c26f802d2
