### ISSUE TITLE
More generic probe location specification

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#957]
Currently the probe interface associates each `probe_id` with a single `mlocation`. This isn't sufficient to support the following sampling scenarios:

1. sampling on a set of locations defined by a `locset`, particularly if the number of locations in the locset is not know before the model is instantiated (which is possible with `join`s and random number generators).
2. sampling voltage over an entire cell (or region).

**Comment by halfflat** [comment]
Presuming #1034 goes through more or less as is, probe ids are associated with a single probe address, but that probe address may represent a non-scalar quantity, such as the membrane voltages across every CV in a cell.

We may be able to avoid changing the 1-1 association with probe ids and probe addresses for the first scenario, also:
* It is probably not necessary to have the `recipe:::num_probes()` interface.
* The probe matching predicates that are used to tie probes with samplers and sampling schedules could be extended to match not just against probe ids, but also against probe tags.

Dispatching to sampler callbacks based on tag, together with the new metadata that is available for callbacks to distinguish between different probes tied to the same sampler function, is possibly all we need.
