### ISSUE TITLE
Shorthand functions for common or conventional sets of labels

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#959]
Functions that return conventional sets of labels, for example for the SWC convention (soma = 1, axon = 2, dendrite = 3) could reduce the boilerplate and typing when a user is experimenting in an interactive environment such as IPython.

**Comment by brenthuisman** [comment]
.swc loader could return a morph and a preseeded label dict as per swc 'spec'.

**Comment by thorstenhater** [comment]
We have that as of #1911
