### ISSUE TITLE
Build fails for the ring example  

### ISSUE THREAD

**Issue by Kaveh01** [arbor-sim/arbor#962]
make fails for the ring example (only for mpi):   
```
[ 91%] Built target arborenv
[ 94%] Building CXX object sup/CMakeFiles/arbor-sup.dir/json_meter.cpp.o
[ 97%] Linking CXX static library ../lib/libarborsup.a
[ 97%] Built target arbor-sup
Scanning dependencies of target ring
[100%] Building CXX object example/ring/CMakeFiles/ring.dir/ring.cpp.o
   .../arbor/example/ring/ring.cpp: In constructor ‘cell_stats::cell_stats(arb::recipe&)’:
   .../arbor/example/ring/ring.cpp:156:28: error: ‘class arb::cable_cell’ has no member named ‘num_branches’
```
I guess line 156 of ring.cpp should be something like
 `nsegs_tmp += c.morphology().num_branches();`
 instead of   
`nsegs_tmp += c.num_branches();`

**Comment by bcumming** [comment]
Thanks for that. Indeed, it should be
```C++
nsegs_tmp += c.morphology().num_branches();
```
This slipped through because we don't compile the examples in our CI.

**Comment by bcumming** [comment]
To fix this, I suggest just scrapping the `cell_stats` step.

**Comment by Kaveh01** [comment]
Thanks for the replay.

**Comment by bcumming** [comment]
Let's keep this open until we have fixed the problem.
