### ISSUE TITLE
Documentations mention CMAKE_INSTALL_PREFIX only after cmake

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#972]
While trying out #971 and using this cmake:

```
cmake .. -DARB_WITH_PYTHON=ON \
               -DARB_PYTHON_PREFIX=$(pyenv root)/versions/3.7.6 \
               -DPYTHON_EXECUTABLE=$(pyenv root)/versions/3.7.6/bin/python \
               -DARB_WITH_MPI=ON
```

The `make install` command threw this error:

```
CMake Error at cmake_install.cmake:46 (file):
  file cannot create directory: /usr/local/share/doc/arbor.  Maybe need
  administrative privileges.


Makefile:73: recipe for target 'install' failed
make: *** [install] Error 1

```

Although everybody on Linux is probably very used to slapping a sudo in front there, I was wondering if this isn't a problem for people without sudo rights? The documentation also doesn't seem to mention any flags or options that are aimed towards people that don't have sudo access to avoid this error.

(Or did I screw up some permissions on a normally accessible folder?)

**Comment by Helveg** [comment]
Also if you do install it with sudo, that means that now you have a folder owned by `root` in your site-packages folder, which stands out.

**Comment by bcumming** [comment]
You can `make` Arbor without sudo, however the `install` phase in `make install` won't work.

Arbor is a C++ library, and the compiled library and header files will be installed in the default `CMAKE_INSTALL_PREFIX` path, in `/usr/local` on your system, which requires `sudo`.

By adding `ARB_PYTHON_PREFIX` we allow installing parts of the library in a location that might have different permissions. I don't want to "break" installation of the C++ library to accommodate an already unorthodox approach.

We have to be careful that we don't start making CMake do things that are "non-standard" for CMake users (avoid magic!). We might have to wait for the pip dragon to be slayed.

**Comment by halfflat** [comment]
Just to add to Ben's comment, we have to by default accommodate as best we can the variety of possible installation environments while adhering to Unixy conventions for layout. Consequently, we have to rely upon the user to specify an appropriate installation prefix with `CMAKE_INSTALL_PREFIX`, and trust them to use an appropriate permissions scheme (e.g. install as root, or install to a setgid directory with a user in an appropriate group, or install in a user-local directory hierarchy, etc.)

For installation as a python module, I think we should aim to make it play well with pip (if it doesn't already - I haven't kept up with Ben's work on this today), so that the question of correct install prefixes and permissions is broadly taken out of users' hands.

**Comment by Helveg** [comment]
Ok, and is it a problem to mention that you can specify a different `CMAKE_INSTALL_PREFIX` for those without root access? I don't have sudo rights on any of the HPC resources I use for example? What would my options be to `make install` arbor in that case?

**Comment by Helveg** [comment]
I think as an important cmake flag it should be explained before the introduction of `make install`

**Comment by bcumming** [comment]
`CMAKE_INSTALL_PREFIX` is the standard way to specify where to install software with CMake, and is usually taken a given knowledge for installation guides. (A bit like virtualenv and user site packages are assumed knowledge for pip users). I don't know how much we want to document this.

This is making it more obvious that we also need to play nice with pip, and leave the CMake path as the "advanced full-control" method for installing everything.

**Comment by Helveg** [comment]
Ok!

**Comment by bcumming** [comment]
I added a little "note" box to the docs for the Python install that should help people who have this issue.
```
+ 395 .. Note::
+ 396     By default CMake sets ``CMAKE_INSTALL_PREFIX`` to ``/usr/local`` on Linux and OS X.
+ 397     The compiled libraries are installed in ``/usr/local/lib``, headers are installed in
+ 398     ``/usr/local/include``, and the Python module will be installed in a path like                                                                                                              
+ 399     ``/usr/local/lib/python3.7/site-packages``.
+ 400     Because ``/usr/local`` is a system path, the installation phase needs to be run as root,
+ 401     i.e. ``sudo make install``, even if ``ARB_PYTHON_PREFIX`` is set to a user path
+ 402     that does not require root to install.

```
