### ISSUE TITLE
Talk to the owner of arbor 0.0.1 on PyPI

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#973]
The name arbor seems to be taken by a certain David Cheperdak (https://github.com/djbchepe) and could be contacted maybe through LinkedIn (linkedin.com/in/davidcheperdak/) for a liberation of the name on PyPI once @bcumming slays the pip dragon.

**Comment by bcumming** [comment]
I have written to David on LinkedIn (well, I made a contact request with a custom message, because I don't have LinkedIn premium). Let's see.

**Comment by bcumming** [comment]
The Arbor package on PyPI:
   https://pypi.org/project/arbor/
qualifies as "invalid" according to pep-541:
  https://www.python.org/dev/peps/pep-0541/#id27
I will wait a bit longer for a reply from the author, and if I don't get a reply, I will try to claim the name here
  https://github.com/pypa/pypi-support/issues

**Comment by bcumming** [comment]
It has been two weeks, and i haven't received a reply from `djbchepe`, so I have filed a request for transfer of Arbor.
https://github.com/pypa/pypi-support/issues/257

**Comment by bcumming** [comment]
The arbor package was transfered to me after I applied to pypi support.

And now `pip install arbor` is available to the world!
