### ISSUE TITLE
Execution contexts with GPU and many threads in unit tests

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#982]
Currently all out unit tests that create an `execution_context` create it with default `proc_allocation` values for threads and gpu which are `num_threads=1` and `gpu_id=-1`. This means that we never test our gpu backend or task system in action in the simulator (even when we intend to). We should use `arbenv::get_env_num_threads()` and `arbenv::default_gpu()` when suitable for more representative unit tests.

**Comment by bcumming** [comment]
Threading and GPU should only be turned on when the unit test is explicitly testing these. Making the unit test behavior change according to combinations of core count and environment variables could make it more difficult to reproduce unit test behavior.

Do we have an example of a unit test that intend to use multi-threading or GPU that don't?

**Comment by noraabiakar** [comment]
Yes, we do. 
from `test/unit/test_domain_decomposition.cpp` line 116:
```
TEST(domain_decomposition, homogenous_population)
{
    proc_allocation resources;
    resources.num_threads = 1;

    if (resources.has_gpu()) {
...
    }
}
```
`resources.has_gpu()` will always return -1

**Comment by bcumming** [comment]
That certainly looks like a bug in that code, probably a hang over from when we used to automatically detect the GPU.
Now you could use `arbenv::default_gpu()` to detect the GPU when creating `resources`.
https://arbor.readthedocs.io/en/latest/cpp_hardware.html#_CPPv4N6arbenv11default_gpuEv

**Comment by noraabiakar** [comment]
Yes, I've already changed it so we find the correct `gpu_id` when creating a `proc_allocation`. I was also considering setting `num_threads` to match the number of available threads on the system we're running on. But I'm not sure whether we want to test multi-threaded or single-threaded behavior in the unit tests, or both. @halfflat suggested we test both by setting `proc_allocation.num_threads` to the total number of available threads and then run the tests in a single-threaded and multi-threaded environment.
